GLOBAL_EXCLUDE_KEYWORDS = [
    "lotificacion",
    "lotificación",
    "proyecto habitacional",
    "consultorio",
    "clinica dental",
    "laboratorio clinico",
    "taller mecanico",
    "taller automotriz",
    "servicios de mantenimiento",
    "dj ",
    " dj",
    "disc jockey",
    "agencia de viajes",
    "remesas",
    "funeraria",
    "funerales",
    "cancha",
    "futbol",
    "peluqueria",
    "salon de belleza",
    "estetica",
    "mcdonals",
    "burger king",
    "kfc",
    "pizzahut",
    "dominos",
    "mcdonalds",
    "inversiones",
    r"\binv\b",
]
FINAL_KEYWORD_EXCLUDE_KEYWORDS = [
    "#NAME?",
    "꧁𝓐𝓷𝔂𝓾𝓵𝓲 𝓕𝓻𝓪𝓷𝓬𝓸꧂",
    "100 Montaditos",
    "24 Seven",
    "5ta Avenida, playa del Carmen",
    "7-Eleven",
    "Abodato",
    "Acabados",
    "Acces",
    "Accesorio",
    "Accesorios",
    "access",
    "Aceite",
    "ACEITERA EL NICA",
    "ACERLUB",
    "Aceros",
    "Acertemos",
    "Acondicionados",
    "Acopio Olam",
    "ACOPIO PROMAR",
    "Acopios",
    "ACORDES SOUND",
    "Acrílico",
    "Acuarela",
    "Acústicos",
    "Adhesive",
    "Adidas",
    "Admi",
    "Administración",
    "Administrativas",
    "Administrativo",
    "Adorno",
    "Aduanales",
    "Aduanas",
    "Aero",
    "AeroExpress",
    "Aerospace",
    "Afiliación",
    "Agencia",
    "Agencia de pollo đuart",
    "Agencia la perfecta",
    "Agricenter",
    "Agrícola",
    "Agroalimentación",
    "Agroalimentario",
    "Agroambiental",
    "Agrobiología",
    "Agrobiotecnología",
    "Agrocadena",
    "Agrocentro",
    "Agrocítricos",
    "Agroclimático",
    "Agrocomercial",
    "Agroconsultoría",
    "Agrocooperativa",
    "Agrodesarrollo",
    "Agroecológico",
    "Agroeconomía",
    "Agroecosistema",
    "Agroempacadora",
    "Agroempresa",
    "Agroenergía",
    "Agroequipos",
    "Agroexportación",
    "Agroferretería",
    "Agrofilters",
    "Agrofinanciera",
    "Agroforestal",
    "Agrogestión",
    "Agrohidrología",
    "Agroindustria",
    "Agroinformática",
    "Agroinsumos",
    "Agroinsumos",
    "Agroinversión",
    "Agroinversiones",
    "Agrologística",
    "Agromarketing",
    "Agrometeorología",
    "Agromineral",
    "Agronómico",
    "Agroparque",
    "Agropastoril",
    "Agropecuaria",
    "Agropecuaria",
    "Agropecuario",
    "Agroproducción",
    "Agroquímico",
    "Agrosanidad",
    "Agroseguridad",
    "Agrosilvicultura",
    "Agrosostenible",
    "Agrotecnia",
    "Agrotecnología",
    "Agrotrazabilidad",
    "Agroturismo",
    "Agroveterinario",
    "Agua Inmaculada Vital Mind",
    "Ahold Delhaize",
    "Aircool",
    "Aircool",
    "Aire",
    "Airguns",
    "Ajna.tulum",
    "Alambre",
    "Alarmas",
    "Alberca",
    "Alcalde",
    "Alcaldia",
    "Alcancias",
    "Alcohólicos Anónimos",
    "Alianza",
    "ALIZEÉ Productos de belleza",
    "Allcell",
    "Almacén Del Gas",
    "Almohadas",
    "Alpargata",
    "Alpina",
    "Alquileres",
    "Alumbra",
    "Alumbrado",
    "Aluminio",
    "Alumino",
    "Alumino",
    "Amarres",
    "Ambientadores",
    "Amoblados",
    "Amortiguadores",
    "Amplicación",
    "Análisis",
    "Ancestrales",
    "Anclajes",
    "Andamios",
    "Android",
    "Anexo",
    "Animal",
    "Animales",
    "Animalito",
    "Anime",
    "Animepixan",
    "Anteojos",
    "Antiguedades",
    "ANTIGÜEDADES",
    "Anuncios",
    "Apicultura",
    "Apple",
    "Applebee's",
    "Apuestas",
    "Aqua",
    "Aquanimal",
    "Arcilla",
    "Arcolores",
    "Areneras",
    "Arícola",
    "Armase",
    "Armería",
    "Army",
    "Arqui",
    "Arquitectónico",
    "Arreglo",
    "ARRENDADORA",
    "Arroz",
    "Artes",
    "Artesanía",
    "artesanía",
    "Artesanias",
    "Artesanías",
    "Artículos",
    "Arts",
    "Asadores",
    "Ascensor",
    "Aseo",
    "Asepticos",
    "Aserradero",
    "Aserrío",
    "Asertec",
    "Asesor",
    "Asociación",
    "Asociados",
    "Astillera",
    "Astillero",
    "Astronomía",
    "Astronomía",
    "Asuntos",
    "AT&T",
    "Atrapasueños",
    "Audio",
    "autoboutique",
    "autobuses",
    "autofinanciamiento",
    "Autolavado",
    "Autolote",
    "Automagic",
    "Automotores",
    "Automotriz",
    "automotriz",
    "automotriz",
    "autopartes",
    "Autos",
    "autos",
    "Autos Felix",
    "AutoServicio",
    "AutoVal",
    "Aventuras",
    "Aventuras",
    "AVIA",
    "Aviaciones",
    "Avianca",
    "Aviario",
    "Avicola",
    "Avícola",
    "Aviones",
    "Avon",
    "Awastic",
    "AWAY INTERNATIONAL NICARAGUA S.A",
    "Baby",
    "Bags",
    "Balanzas",
    "Baleros",
    "Balloon",
    "Balneario",
    "Balones",
    "Baloon",
    "Banana",
    "Bananeras",
    "Bananeras",
    "Bananeros",
    "Bananos",
    "Banco",
    "Banco",
    "Bañññño",
    "Baños",
    "Banquetes",
    "Baranetos",
    "Barba",
    "Barber",
    "Barbería",
    "Barbers",
    "Barbershop",
    "Barrera municipal",
    "Básculas",
    "Batería",
    "Batt",
    "Batteries",
    "Battery",
    "Bautizos",
    "Beautiful",
    "Beauty",
    "Beauty Salon",
    "Beauty Store",
    "bebabussiness",
    "Bebe",
    "BEBÉ",
    "Bebés",
    "Bebitos",
    "BeFitWorld",
    "Belleza Profesional abastos",
    "BELLEZA PROFESIONAL ORIENTE",
    "Berbalifes",
    "Betterware",
    "Bici",
    "Bici",
    "Bicicletas",
    "Bicirefaccionaria",
    "bienes",
    "Bienestar",
    "bike",
    "Bikes",
    "Bimbo",
    "Bio",
    "Birretes",
    "Bisutería",
    "Bless",
    "Bloques",
    "blu grand x",
    "Blusa",
    "BMN Consultores",
    "Bocinas",
    "body shop",
    "Bolsa",
    "Bolsas",
    "Bolso",
    "Bomba",
    "Bomberos",
    "Bombones",
    "Books",
    "Bordado",
    "Bordados",
    "BOSQUES DE SOLIDARIDAD",
    "Botanic",
    "Botánico",
    "Botas",
    "Botica",
    "Botones",
    "Boulevard Sierras Doradas",
    "Brands",
    "Brands",
    "Bronce",
    "Brujula",
    "BryKen",
    "Bullring",
    "Bunker",
    "Burbujas",
    "Burger King",
    "Bus",
    "Buses",
    "Business",
    "BW Servicios, Puerto Cabezas",
    "C.I",
    "c.i.",
    "Caballo",
    "Cabina",
    "Cacharrería",
    "Caja",
    "Cajeros",
    "Calcetería",
    "Calcetines",
    "Calco",
    "Calcomanias",
    "Calcomanias",
    "Calcomanías",
    "Calderas",
    "Calentadores",
    "Calimax",
    "Call",
    "Calle",
    "Calypso",
    "Calypso",
    "Calza",
    "Calzado",
    "Camara",
    "Cámara de Comercio",
    "Camiones",
    "Camisas",
    "Camisetas",
    "Camping",
    "camping",
    "Canchas",
    "Canino",
    "Canje",
    "Cannabis",
    "Capacitación",
    "Capilares",
    "Car Rent",
    "Car Wash",
    "Car Wash",
    "Carbón",
    "Carboneria",
    "Carbonería",
    "Cárcel",
    "Cardio",
    "Caretas",
    "Carga Internacional",
    "Cargadores",
    "Cargo",
    "Caricaturas",
    "Carl's Jr.",
    "Carnival Cruiselines Dock & Pier",
    "Carolina Herrera",
    "Carpas",
    "Carpinteria",
    "Carpintería",
    "Carpintería",
    "Carpintería",
    "Carpintero",
    "Carrefour",
    "Carrocerias",
    "Carrocerías",
    "Cars",
    "Cartelera",
    "cartón",
    "Cartuchos",
    "CarWash",
    "Casa Gala",
    "Cascos",
    "Caserio",
    "Cash",
    "Casilleros",
    "Casting",
    "Caterpillar",
    "Cauchos",
    "Causas Justas",
    "Caza",
    "CEDIS DDS MARS WRIGLEY",
    "CEL BENDICIÓN DE DIOS",
    "Cell",
    "Cell",
    "Celu",
    "Celu",
    "Celular",
    "Celular",
    "Celulares",
    "Cementos",
    "CEMEX",
    "Center",
    "Center Plaza",
    "Central De Productores",
    "Centro Comercial",
    "Centro Cultural",
    "Centro de Compras",
    "Centro De Servicio",
    "Centro Naturista",
    "Centro Norte",
    "Centro Plaza",
    "Centrocomercial",
    "Cepillos",
    "Ceramica",
    "Cerámica",
    "Ceramico",
    "Ceramics",
    "Cereales",
    "Cerrajería",
    "Cerrajería",
    "Cerrajes",
    "Cervecera",
    "Cesantías",
    "Chalecos",
    "Champiñones",
    "Chancla",
    "Chaqueta",
    "CHATARRERIA",
    "Chatarrería",
    "Cheffs",
    "Chemical",
    "CHEVYFORD",
    "Chic & Pink store",
    "Chimeneas",
    "Chuck E. Cheese's",
    "Ciber",
    "Ciclista",
    "Científica",
    "Cigar",
    "Cigarreía",
    "Cigarro",
    "Cimentación",
    "Cimentación",
    "Cine",
    "Cinemas",
    "Cinépolis",
    "Cinnabon",
    "Cinta",
    "Cinturones",
    "Circle K",
    "Circuitos",
    "Circular",
    "Cirugía",
    "City Hall Altabrisa",
    "CityColor",
    "Claro",
    "Claro que si la Bendición",
    "Clean",
    "Climas",
    "Clinderm Mérida by Dra. Tania de la Vega",
    "Clini",
    "Clínica",
    "Closet",
    "Cloth",
    "Clothes",
    "Cloud",
    "Club De Nutrion",
    "Cocer",
    "Cochez",
    "Cocinas",
    "Código De Barras",
    "Cohete",
    "Cojín",
    "Colchas",
    "Colchón",
    "Colchones",
    "Colección",
    "Coleccionables",
    "Colecciones",
    "Collectibles",
    "Collection",
    "Collection",
    "Color",
    "Color",
    "Combustibles",
    "Comercial",
    "Comercial Center",
    "Comisariato",
    "Comite",
    "Commercial Planet",
    "Community",
    "Comodidad",
    "Compañía",
    "Complejo",
    "Complejo",
    "Componentes",
    "Compra oro",
    "Compras onliline",
    "Compresores",
    "Compro Oro",
    "Compu",
    "Compu",
    "Computador",
    "Computadora",
    "Computadoras",
    "Computadores",
    "Cómputo",
    "Comunal",
    "Comunicacion",
    "Comunicaciones",
    "Comunicaciones",
    "COMUNICACIONES",
    "COMUNICAIONES",
    "Comunidad",
    "Concepción",
    "Concept",
    "Concepto",
    "Concretos",
    "Condicionartes",
    "Condominios",
    "Conducción",
    "Conectora Solar Kin Oficina Suegro",
    "Conexión",
    "Conexiones",
    "Confecciones",
    "Confecciones",
    "Confectionary",
    "Confitería",
    "Congeladora",
    "Conjunto Residencial",
    "Consejo",
    "Conservas",
    "constitucion",
    "Constru",
    "Constru",
    "Construcción",
    "Construcciones",
    "Constructor",
    "Constructora",
    "Constructora",
    "Constructora",
    "Consulado",
    "Consulting",
    "Consultor",
    "Consultores",
    "Consultoría",
    "Consultorio",
    "Contaminación",
    "Contenedor",
    "Contrataciones",
    "Contratista",
    "Coo",
    "Coopel",
    "Cooperativa",
    "Cooperativas",
    "Cooprogreso",
    "Coperatiba",
    "Copia",
    "Copiado",
    "Copiadoras",
    "Copias",
    "Coppel",
    "Copy",
    "Cordones",
    "Corporación",
    "Corporativo",
    "Correa",
    "Correas",
    "Correo de México",
    "Cortadora",
    "Corte y Confección",
    "Cortemetal",
    "Cortesano",
    "Cortinas",
    "Coser",
    "Cosmetic",
    "Cosmético",
    "Cosmético",
    "Cosmético",
    "Cosméticos",
    "COSMO FACIAL LEVIR",
    "Cosmopolitan",
    "Costrucción",
    "Costura",
    "Costurero",
    "COUNTERPARTS STORE",
    "Creaciones",
    "Creative",
    "Creativos",
    "Crédito",
    "Creditos",
    "Créditos",
    "Créditos",
    "Crema",
    "creurmack",
    "Criadero",
    "Cristal",
    "Cromados",
    "Cromatic",
    "crystalaccesorios",
    "Cuadros",
    "Cuarzos",
    "Cubiertas",
    "Cubreboca",
    "Cuero",
    "Cultura",
    "Curiosidad",
    "Cursos",
    "Customizado",
    "Customs Agents",
    "Cyber",
    "Cycle",
    "Cyclene",
    "Cycling",
    "Data",
    "Datos",
    "Deco",
    "Decor",
    "Decoraciones",
    "Decoraciones",
    "Decorarte",
    "Decorativas",
    "Defender",
    "Defensoría",
    "Delegación",
    "DellStores",
    "DellStores",
    "Dental",
    "dental",
    "Departamentos",
    "Deporte",
    "Deportes",
    "Deportes",
    "Deportivas",
    "Deportivos",
    "Depósitos",
    "Depósitos",
    "Desarrollo",
    "Descargue",
    "Descargue",
    "Desconocido",
    "desechable",
    "Desechable",
    "Desechables",
    "deshuesadero",
    "Desig",
    "Design",
    "Desing",
    "Desing",
    "Desmanteladora",
    "Despacho",
    "Desponchado",
    "Detalles",
    "Detectives",
    "Detergente",
    "Diabe",
    "Diagnostico",
    "Diagnóstico",
    "Dibujo",
    "Didácticos",
    "Diesel",
    "Digital",
    "Digital",
    "Digitales",
    "Dinero",
    "Dinero",
    "Directivo",
    "Diseña",
    "Diseño",
    "Disfraces",
    "Disfraz",
    "Dish Venta e Instalacion",
    "Dispensadores",
    "Distribuidora Adoriss",
    "Distribuidora de productos de belleza Girasoles",
    "Distribuidora De Souvenirs Don Chiles",
    "DISTRIBUTIONS",
    "Dj Industries",
    "DMS MERGIL",
    "Dobladora",
    "Dobleces",
    "Doc Stereo",
    "Doit Center",
    "Domésticos",
    "Domino's Pizza",
    "DONATO STONE",
    "Dreams",
    "Dubai girls",
    "Dubai girls",
    "Dunkin' Donuts",
    "E-MARKET.COM",
    "E-MARKET.COM",
    "ebanistería el chele",
    "ebenezer cell-zay",
    "Ecológica",
    "Ecológica",
    "Ecological",
    "Econo",
    "Economía",
    "Ecosistemas",
    "Ecoturistico",
    "Edif",
    "Edificio",
    "Edificio",
    "Edificio",
    "Editoriales",
    "Educación",
    "Educativas",
    "Educatodo",
    "Efecti",
    "Efectivo",
    "Efecty",
    "Effectos",
    "Ejes y Componentes",
    "El CampeÃ³n",
    "El ciclista",
    "El Fuerte",
    "El Güerito Tienda Infantil -Plaza Praderas Sandino",
    "El mundo de las uñas",
    "El mundo de las uñas Managua, Nicaragua",
    "Elaboración de Ollas",
    "Electric",
    "Electríca",
    "Eléctrica",
    "ELECTRICOL",
    "Eléctricos",
    "Eléctricos",
    "Electrics",
    "Electro",
    "Electro",
    "Electrónica",
    "Electrónica",
    "Electrónica Electro Luminati",
    "Electrónicos",
    "Electrónicos",
    "ElectroWorld",
    "EleganceShop",
    "Elegancia",
    "Elektra",
    "Elevadores",
    "Elezctrzic",
    "Emergencias",
    "EMICELL",
    "Empacadora",
    "Empalme de la Cruz",
    "Empaques",
    "Empaques Y Productos Plásticos S.A.",
    "Empeños",
    "Emplastamos",
    "Empres Avícola",
    "Empresa",
    "Empresariales",
    "Empresarios",
    "Encargos",
    "Encomia",
    "Energía",
    "ENERGON",
    "Enmarcación",
    "Ensamble",
    "Enterprises",
    "Entrada Avenida Cupules del Hotel Fiesta Americana",
    "Entrega",
    "envases",
    "Envases Y Tapas De Mexico | Mérida",
    "Envios",
    "Envios",
    "Equimep",
    "Equipales",
    "Equipment",
    "Equipo",
    "Erectus",
    "Erótica",
    "Erótica",
    "Escaleras",
    "Escencia",
    "Escencia",
    "Escobas",
    "Escobillas",
    "Escola",
    "Escolar",
    "Esencias",
    "Esmaltados",
    "Esmalteria",
    "Esoterico",
    "Esotérico",
    "Esotericos",
    "Esotéricos",
    "ESPECTACULAR ECO",
    "Esquina de El fogón. El fogón kúchil koonol",
    "Essence",
    "Estación",
    "Estación De Carretera Yalagüina",
    "Estacionamiento",
    "Estacionamiento Plaza Granada",
    "Estadero",
    "Estampados",
    "Estanterias",
    "Esterica ByAndy MuRan",
    "Estética",
    "Estética",
    "Estética",
    "Estéticas",
    "Estilista",
    "Estilistas",
    "Estilos",
    "Estíos",
    "Estructuras",
    "Estudios",
    "Estufas",
    "EuroElectríca",
    "Eurotec",
    "Eventos",
    "Exhibidores",
    "Expo",
    "Exports",
    "EXTINGUIDORES",
    "Extintores",
    "Extra",
    "Extrategias",
    "Fajas",
    "Familia",
    "Fantacias",
    "Fantasía",
    "Fantasy",
    "Farmacia",
    "Farmacias Arrocha",
    "Farmacias del Ahorro",
    "Farmacias Metro",
    "Farolas",
    "Farolas",
    "Fashion",
    "fashion",
    "Fedex",
    "Femco",
    "Femini",
    "Ferre",
    "Ferre",
    "FERRETERIA",
    "Ferretería",
    "Ferreteros",
    "Ferro",
    "Ferro",
    "ferro",
    "Ferro",
    "Fertilizantes",
    "fhasion",
    "Fibras",
    "Fiesta",
    "Figuras",
    "Filters",
    "Filtros",
    "Financiera",
    "Finanzas",
    "Finders Keepers PM",
    "Finijewerly",
    "Firestone",
    "Fiscalia",
    "fisio",
    "Fits",
    "Flamingo Amigo",
    "Flor",
    "Floreria",
    "Floristería",
    "Flowers",
    "FM",
    "Foldex",
    "Fondos",
    "Fordex",
    "Forestal",
    "Forjados",
    "Forrajes",
    "Forros",
    "Foto",
    "Foto-Servicio",
    "Fotocopia",
    "Fotocopias",
    "fotocopias NASH",
    "Fotografía",
    "Fotográficos",
    "Fraccionamiento",
    "Fragancia",
    "Fragancias",
    "Free Info Center",
    "Freno",
    "Friki",
    "Fruta",
    "Frutas",
    "Frutas",
    "Fuerzas Militares",
    "Fumigación",
    "Fumigaciones",
    "Fundaci",
    "Fundación",
    "Fundición",
    "Funeraria",
    "Funeraria",
    "Furgones",
    "furniture",
    "Fussion Acustic",
    "G&D Accesories",
    "Galería",
    "Gallery",
    "Gallos",
    "Gamer",
    "Games",
    "Gaming",
    "Ganaderos",
    "Garabatos",
    "Garage Sales",
    "Gardenia",
    "Gato",
    "Generadores",
    "Geólogo",
    "Geometry",
    "Gift Shop",
    "Gift Shop",
    "Gifts",
    "GiftShop",
    "Glamour",
    "Glamour Virtual",
    "Glass",
    "GNC (General Nutrition Centers)",
    "Gobernación",
    "Goodwill Industries",
    "Gorra",
    "Gorras",
    "Graf",
    "Gráficas",
    "Graneros",
    "Granjas",
    "Grano",
    "Granos",
    "Graphic",
    "Grifos",
    "Grua",
    "Grupo",
    "Grupo Modelo",
    "Guadañas",
    "Guadañas",
    "Guantes",
    "Guardería",
    "Guitarra",
    "Guns",
    "H2ONicaragua",
    "Habano Shop",
    "Hamacas",
    "Handmade",
    "Handmade & More",
    "HARDWARDSTORS BRANDGYERDSON",
    "Hats",
    "Health",
    "Healthy",
    "Helio",
    "Helvex SPEC Showroom",
    "Herbalife",
    "Herbalife",
    "Herbolaria",
    "Herrajes",
    "Herrería",
    "Hewlett Packard",
    "Hidrogel",
    "Hidroservicios",
    "Hielera",
    "Hierbas",
    "Hierberia",
    "Hierbería",
    "Hierro",
    "Higiénico",
    "Hipódromo",
    "HMP CONSULTORES EN SEGURIDAD Y SALUD EN EL TRABAJO",
    "Hogar",
    "Hollywood",
    "Home",
    "HomeCell",
    "honda",
    "Hooters",
    "Hortalizas",
    "Hospital",
    "Hotelería",
    "House Of Wabi",
    "Hp store",
    "HR pop mart",
    "Huaracheria",
    "Huerta",
    "Hugo Boss",
    "Hyatt Centric",
    "HYDRAULIC CONNECTIONS AND HOSE AND LUBRINORTE",
    "I-Showroom",
    "Iconos",
    "Iconstick",
    "Idea",
    "Identicard",
    "identidad",
    "Iglesia",
    "Iglesia",
    "Ilumi",
    "Ilumin",
    "iluminación",
    "Iluminaciones",
    "ilusión",
    "Imagen",
    "Imágenes",
    "Images",
    "Imagination",
    "Impermeables",
    "Import",
    "Importación",
    "Importaciones",
    "Importadora",
    "Impre",
    "Impresión",
    "Impresiones",
    "Impresores",
    "Impresos",
    "Impressiona",
    "Impulsora",
    "Incendios",
    "Inciensos",
    "Industriales",
    "Industrials",
    "Industrias",
    "Industry",
    "Inflables",
    "infonavit",
    "Informática",
    "Ingeniería",
    "Ingeniería Y Riegos Del Sureste",
    "Ingenieros",
    "Ingenio",
    "Ingenio",
    "INJETECH",
    "Ink",
    "inmobiliaria",
    "Inmobiliarios",
    "innova",
    "Innovatech Store Caucel",
    "Inspección",
    "Instalaciones",
    "Instrume",
    "Instrumentadora",
    "Instrumentos",
    "Insumos Pecuarios",
    "Intecom",
    "INTECOM",
    "INTEQ",
    "Interllantas",
    "Internacional",
    "Internet",
    "Interprises",
    "Intima",
    "Intimas",
    "Inver",
    "INVERBONIC",
    "Invernadero Tunkas",
    "Inversiones",
    "Investigaciones",
    "Investigadores",
    "Investigadores Privados",
    "Investments",
    "Investments",
    "Invitaciones",
    "iOS graphicos",
    "iphone",
    "Ivrería Y Variedades Hercon",
    "Jabones",
    "Jardin",
    "Jardín del Emprendedor Canaco",
    "Jardines",
    "Jeans",
    "Jehova",
    "Jewelry",
    "Joya",
    "joye",
    "Joyería",
    "Joyería",
    "joyeros",
    "JUEGOS XBOX",
    "Jugadores Anónimos UN DÍA A LA VEZ",
    "Juguetería",
    "Juguetería",
    "Junta",
    "K-",
    "kenneth cole",
    "Kenneth Cole",
    "kfc",
    "KFC",
    "Kids",
    "KING COLOR",
    "Kiss",
    "Kitty",
    "Krispy Kreme Doughnuts",
    "La Chancletería",
    "La llave con chip",
    "Laboratorio",
    "Lacio",
    "lacoste",
    "Lacoste",
    "Lácteo",
    "Lacteos",
    "Lácteos",
    "Lácteos",
    "Ladrillera",
    "Ladrilleria",
    "Ladrillos",
    "Laminas",
    "Lamparas",
    "Lanas",
    "Languages",
    "Lantera",
    "Laparoscopía",
    "Láser",
    "Latin Lover",
    "Lava",
    "Lavadero",
    "Lavandería",
    "Leather",
    "Lechona",
    "LEGO",
    "Legos",
    "Legumbrería",
    "Legumbres",
    "Lens",
    "Lentes",
    "Liberad",
    "Libre",
    "Librería",
    "Librería",
    "Libros",
    "Libros",
    "Licuadoras",
    "LIDEART",
    "Liderazgo",
    "Limpieza",
    "Limpiosos",
    "little caesars",
    "Little Caesars",
    "Llanta",
    "llanta",
    "Llantas",
    "Llantera",
    "Llantimarcas",
    "Llave",
    "Lociones",
    "Lockers",
    "Lógico",
    "Logís",
    "Logística",
    "Logístico",
    "LOGISTICS",
    "Lonas",
    "Lotería",
    "Lottery",
    "ltda",
    "Lubricación",
    "Lubricante",
    "Lubricante",
    "Lubricantes",
    "Luces",
    "Lujo",
    "Lustra",
    "Luxury",
    "M&M",
    "MAC Cosmetics",
    "Machete",
    "Macrochapas",
    "Macroplaza",
    "Madera",
    "Magazine",
    "Mágia",
    "Magic",
    "Magneto",
    "make up",
    "make_up",
    "Makeup",
    "Malabares",
    "Malecon",
    "Maleta",
    "Maletines",
    "Mall",
    "Mango",
    "Manguera",
    "Mantenimientos",
    "Manualidades",
    "Manufactura",
    "Maquila Die Cuts And Slitting",
    "Maquiladora",
    "Maquinaria",
    "Maquinarias",
    "Maquinas De Control Sa De Cv",
    "maranatha",
    "Marathon",
    "Mariachi",
    "Marijuana",
    "Marketing",
    "Marmol",
    "Marquetería",
    "Marro",
    "Marvel",
    "MasCelular",
    "Mascota",
    "masideasrotulosytoldos, soluciones tecnologicas",
    "Material",
    "Materiales",
    "Materiales",
    "Materiales de Construcción",
    "Materiales ópticos",
    "Maxihome",
    "Mazda",
    "Mazorcas",
    "McDonald's",
    "Mecánico",
    "Medias",
    "Medic",
    "Médicas",
    "Medicinales",
    "Médico",
    "Mega Health",
    "MEI LING Mayoreo, Catedral Valladolid",
    "Memetica",
    "Mensajería",
    "Mercadeo",
    "Mercantil",
    "Mesas",
    "Metal",
    "Metal",
    "Metalicas",
    "Metálicas",
    "Metalurgia",
    "Metrologia",
    "Mexytul SA de CV",
    "Micropigmentación",
    "Miel de Abeja",
    "Miele",
    "Militar",
    "minera",
    "Mini Super El Costo",
    "Mining",
    "MINISO International",
    "Mobile",
    "Mochila",
    "Mochila Golden Star",
    "Moda",
    "Modas miranda",
    "Modelos",
    "Módulo Oficial de Venta Xcaret",
    "Módulos Susy",
    "Moldes",
    "Molduras",
    "Molinos",
    "MOMOXVIP",
    "Montacargas",
    "Montaje",
    "Montalvan Servicios Personalizados",
    "Montura",
    "Moto",
    "moto",
    "Motores",
    "Motorespuesto",
    "Motos",
    "Motul",
    "movies",
    "Móvil",
    "Mr. Precio",
    "Mueble",
    "Mueblería",
    "Muebles",
    "Muebles",
    "Muelle",
    "Mujer",
    "Multicentro",
    "Multimodal",
    "multiplaza",
    "Multiservicio",
    "Multivisiones",
    "Mundo de juguete",
    "Music",
    "My Baby Fish",
    "Nail",
    "Nails",
    "Nano",
    "Natura Gift Shop and Stanhome",
    "Natural",
    "Natural",
    "Naturaleza",
    "Naturista",
    "Náutica",
    "NAUTIMUNDO",
    "Negocio",
    "Negocio Varios",
    "Negocios",
    "Negocios",
    "Netitas",
    "Network",
    "Networks",
    "Neumática",
    "Neumáticos",
    "New Collection,bolsos y más",
    "Nike",
    "Niño Jesus",
    "Nintendo",
    "No depositen es fraude",
    "No sé",
    "Notaría",
    "Noticias",
    "Novias",
    "Novias",
    "Nursery",
    "Nutrición",
    "Obra",
    "Office",
    "Ofice",
    "Oficentro",
    "Oficina",
    "Oficina",
    "oficnas",
    "Olímpica",
    "Omnilife",
    "On the Run",
    "Opti",
    "óptica",
    "Ópticas",
    "Ópticas",
    "Optics",
    "Orgánicos",
    "Ornamenta",
    "Ortopédico",
    "Orvel - Orvelplast",
    "Otaku",
    "Outlet",
    "OXXO",
    "P.F. Chang's China Bistro",
    "Pabellón Bonampak",
    "pacho movies",
    "Pacifex",
    "Pagos",
    "Paint",
    "Paint",
    "Pallets",
    "Pañalera",
    "Pañalera",
    "Pañales",
    "Panda Express",
    "Panela",
    "Panoramic",
    "Pantalón",
    "Pantalones",
    "Pantuflas",
    "Papa John's",
    "Papel",
    "Papel",
    "Papelería",
    "Papeles",
    "Papers",
    "Paquetería",
    "Paradero Combis Cielo Nuevo",
    "Parador Turístico",
    "Parasoles",
    "Parfums",
    "Parque",
    "Parqueaderos",
    "party",
    "Pasaje",
    "Paseo",
    "Pasión",
    "Pasta Flexible Geral Jimenez",
    "Pasteurizadores",
    "Patio Minero",
    "Patrimonial",
    "Pavimentaciones",
    "Payless Shoesource",
    "PC",
    "Pelea",
    "Película",
    "Película",
    "Peluches",
    "Peludos",
    "Peluquería",
    "Peluquerìa",
    "Peluquero",
    "Penitenciarias",
    "Pensiones",
    "Pepsico",
    "Perforación",
    "Perfume",
    "Perfumería",
    "Periferico",
    "Persiana",
    "Personalizadas",
    "Pesquera",
    "Pet Food",
    "PET SHOP",
    "Pet Store",
    "Petroleros",
    "phone",
    "Photo",
    "Photography",
    "Piel",
    "Pieldeluxxe",
    "Pieles",
    "Pijamas",
    "Piñata",
    "Piñatas",
    "Piñatas",
    "Piñatería",
    "Pintor",
    "Pintor",
    "Pintores",
    "Pintu",
    "Pintura",
    "Pinturas",
    "Pinturas",
    "Pirotecnia",
    "Pirotécnia",
    "Pisos",
    "pizza hut",
    "Pizza Hut",
    "Placita",
    "Planta Purificadora Angeles",
    "Plantas",
    "Plantas Purificadoras Rocamar",
    "Plasa",
    "Plast",
    "Plastic",
    "Plastic",
    "Plástica",
    "Plástico",
    "plástico",
    "Plásticos",
    "Plátano",
    "PLAYA DEL CARMEN",
    "Plaza",
    "Plazuela",
    "PlomDepot",
    "Plotter",
    "Polarizado",
    "Policia",
    "Polímeros",
    "Polímeros",
    "Poliplastic",
    "Poliplastics",
    "pollo campero",
    "Pollo Campero",
    "Pontelo Store",
    "Pool",
    "Portería",
    "Postales",
    "Predio de itzimcab",
    "Predios",
    "Premezclados",
    "Premiaciones",
    "Prenda",
    "Presta",
    "Presto",
    "PriceSmart",
    "PrimeMX",
    "Princesas",
    "Print",
    "PRO HERIDAS",
    "Procesadora",
    "Producciones",
    "Producto de belleza Adelaida Cruz",
    "Productos Tropicales",
    "Profedet",
    "Professional Safety Group",
    "Promocionales",
    "Promocionales",
    "Pronnosticos",
    "Pronosticos",
    "prosesadora",
    "Protein",
    "Protein",
    "Protokimica",
    "Proyecciones",
    "Proyectos",
    "PTG WAREHOUSE",
    "Public",
    "Publicaciones",
    "PUBLICENTER",
    "Publicidad",
    "Publicitario",
    "Puertas",
    "Puma",
    "Punto Diamante MOTUL",
    "Punto Yastás",
    "Puppies",
    "Puritronic Valladolid",
    "Pyrolac",
    "quarium",
    "Quick Vip",
    "Quicksilver",
    "Quimica Real",
    "Químicas",
    "Químico",
    "Quiropractico",
    "Quiropráctico",
    "Racing",
    "Radiadores",
    "Radio",
    "Raiisa S.a. de C.V.(P. Ramos)",
    "Real Ensueño Sala de Fiestas",
    "Recargas",
    "Recaudos",
    "Reciclables",
    "Reciclaje",
    "ReciklArte-Bisutería • Plaza Inter",
    "Reconstructora",
    "Recreacionales",
    "rectif",
    "Rectificación",
    "Recubiertos",
    "Recubrimientos",
    "Recuperadora",
    "Refacción",
    "REFACCIONARIA",
    "Refrigeración",
    "Refrigeración",
    "Refriservicios",
    "Regalo",
    "Regalos",
    "Rejillas",
    "Religión",
    "Religioso",
    "Relojes",
    "Renault",
    "Rent",
    "Renta",
    "Renta de Sombrillas",
    "Renta-Lav",
    "Rental",
    "Reparación",
    "Reparaciones",
    "Repowering",
    "Representaciones",
    "Repuesto",
    "Resoldar",
    "Resortes",
    "Restauraciones",
    "Revistas",
    "Riba Smith",
    "Riba Smith Express",
    "Riders",
    "Riders",
    "Rines",
    "Rines",
    "Rituales",
    "Rodamientos",
    "Rodamientos",
    "ROGER ARMY",
    "Rollet",
    "Ropa",
    "ross",
    "Ross",
    "Rotulos",
    "Royal Caucel Square",
    "Rueda",
    "Rzepzair",
    "S.A.S",
    "Safetec",
    "Sala de Belleza",
    "Saldos",
    "Salon",
    "Salón",
    "Salon Vanity",
    "Saloon",
    "Samsung",
    "Samsung",
    "sandalia",
    "Sanitario",
    "Sastreria",
    "Sastreria",
    "Sastrería",
    "SayraModa",
    "Scooter",
    "Scooter",
    "Scooters",
    "Secretos",
    "Secretos",
    "Security",
    "Security",
    "Segurenta - Cancún",
    "Seguridad",
    "Seguros",
    "Sellado",
    "Sellados",
    "Sellos",
    "Semaforización",
    "Semillas",
    "señalizaciones",
    "Sensual",
    "Sensual",
    "Sensuales",
    "Sentimientos",
    "Sercom",
    "Servicio",
    "Servicio Fotográfico",
    "Servicios",
    "Servicios Publicos",
    "SERVICONTROLES",
    "Servientregas",
    "Servifiestas",
    "Sex",
    "Sexshop",
    "SHEIN",
    "Shell",
    "Shoe Repair",
    "Shoes",
    "Shooping",
    "Shopping",
    "Shopping Center",
    "Showroom",
    "Silla",
    "Silver Shop",
    "Sindicato",
    "Singer",
    "Siste",
    "Sistemas",
    "Sitio de taxis Valladolid a Temozón",
    "Sixspeed HD",
    "Skates",
    "SKECHERS",
    "Skin Care",
    "SKINNY COLIMA",
    "Sleep",
    "Smart",
    "Smart Vision Security",
    "smile",
    "Smoke",
    "Social",
    "Sociedad",
    "Software",
    "Solar",
    "Solares",
    "Soldaduras",
    "SOLICIONES MILENIO DIST. DE PROD. IMPAC",
    "Soluciones",
    "Soluciones Técnicas Peninsulares",
    "Solutec",
    "Solution",
    "Sonido",
    "Soporte",
    "Sorpresas",
    "Sounds",
    "SoundTech",
    "Spa",
    "Spa",
    "Sport",
    "sport bar bb",
    "Sportline",
    "SPotes",
    "starbucks",
    "Starbucks",
    "Stereo",
    "Sterling",
    "Stickers",
    "Streaming",
    "Streaming",
    "Studio",
    "Styles",
    "Subasta",
    "Sublimación",
    "Sublimación",
    "SubliMid Artículos Personalizados",
    "subway",
    "Subway",
    "Suelas",
    "Sujeciones Unidas",
    "Super 24",
    "Super 99",
    "Super Carnes",
    "Super Centro 5 de Mayo",
    "Super Kosher",
    "super max",
    "Super Max",
    "Super Mercado Romero",
    "Supermercado Jumbo",
    "Supermercado Los Andes",
    "Supermercado Machetazo",
    "SuperMini",
    "Suplitex",
    "Surtidora",
    "Surtidora Los Gatitos",
    "Suspensiones",
    "suzuki",
    "Suzuki",
    "Swap Meet",
    "Sweet seduction",
    "Swim",
    "Sysco",
    "System",
    "System Garage",
    "Systems",
    "Tablets",
    "taco bell",
    "Taco Bell",
    "Tactical",
    "Táctico",
    "Tai Chi",
    "Talabartería san antonio",
    "Talentos",
    "Talentos",
    "Taller",
    "Tanques",
    "Tapetes",
    "Tapicería",
    "Tarjeta",
    "Tattoo",
    "tattoo",
    "Tattoos",
    "tatuaje",
    "Taxis",
    "Tec",
    "Tech",
    "Tech",
    "Tech",
    "Técnicos",
    "tecno frio auto servicio",
    "tecnodzay",
    "TecnoGamers",
    "Tecnología",
    "Tegnología",
    "TEKNOVA DISTRIBUCIONES S.A DE C.V.",
    "Telas",
    "Telcel",
    "Telecomunicaciones",
    "Telefonía",
    "Telefono",
    "Telescopios",
    "Telev",
    "Televentas",
    "Televisión",
    "Telita",
    "Tenderos",
    "Tenis",
    "Tenis",
    "Tennis",
    "Tentación Boutique",
    "Térmicos",
    "Terminal",
    "Ternuras",
    "Terraza Temozón - Locales con Terraza, Mercadito y Jardín Sensorial para Mascotas",
    "Terreno",
    "Terrores",
    "Texaco",
    "Textil",
    "Textiles",
    "Textiles",
    "Textos",
    "Thermal And Plumbing",
    "Tienda China",
    "Tienda de Belleza",
    "Tienda de celulares",
    "tienda de celulares y electrodomésticos nikooll",
    "Tienda de Ropa",
    "Tienda el divino niño xtepen Yucatán",
    "Tiendas",
    "Tiendas Delta",
    "Tilapia",
    "TIME IS ART",
    "Tinta",
    "Tintas",
    "Tintura",
    "Tires",
    "Todo en Danza | Mérida",
    "todomática",
    "Togas",
    "Tonalidades",
    "Tónicos",
    "Tools",
    "Tools",
    "Tornería Wilberth",
    "Tornillos",
    "Totto",
    "Toyota",
    "Toys",
    "Trabajo",
    "Trade",
    "Trading",
    "Tramites",
    "Trans",
    "Transferencia",
    "Tránsito",
    "Transporte",
    "Transportes",
    "Traperas",
    "Traperos",
    "Travesuras",
    "Trofeos",
    "Tronick",
    "tronics",
    "Tropigas",
    "Trsggs",
    "Trust",
    "Tupcomunicaciones",
    "Tupperwares",
    "Turismo",
    "Tury Transfers",
    "TV",
    "UBERS",
    "Uñas",
    "Unidades",
    "uniformarte",
    "Uniformes",
    "Uniplaza",
    "University",
    "UPS",
    "Urban",
    "Urban",
    "Urbana",
    "Válvulas",
    "Vape",
    "Vapes",
    "Vapes",
    "Vapor",
    "Vapor",
    "Vasos",
    "Vehicular",
    "Vehiculos",
    "Veiculos",
    "Velas",
    "Velcam",
    "venta de celulares",
    "Venta de Garaje",
    "Venta de Materiales",
    "venta el guapo",
    "Venta por catálago",
    "Ventiladores",
    "Verduras",
    "Vestido",
    "Vestidos",
    "Vestir",
    "Vet Shop",
    "veterinaria",
    "Veterinario",
    "Veterinarios",
    "Veterinary",
    "Viales",
    "Vida Terapias Alternativas",
    "Video",
    "Videojuegos",
    "Vidrería",
    "Vidriera",
    "Vidrio",
    "Vigilancia",
    "Vision",
    "Vision",
    "Viste",
    "Vitality",
    "Vitrinas",
    "Vulcanizadora",
    "Vv...vv",
    "walmart",
    "Walmart",
    "Water",
    "Wear",
    "welldex",
    "Wellmedic Mayakoba",
    "Wendy's",
    "Western Union",
    "Western Union",
    "Whirpool",
    "Wi-Fi",
    "Wireless",
    "Wood",
    "Woodshop",
    "Workshop",
    "World Of Make-Up",
    "Xbox",
    "Xenon",
    "Xerox",
    "Xports",
    "Xtra",
    "Xxx",
    "Yanbal",
    "Yesos",
    "Yonque sksjsikaka",
    "Zapateria",
    "Zapatería",
    "Zapatillas",
    "Zapato",
    "Zapato",
    "Zapteria 1",
    "Zerej",
    "Zigzag",
    "Zona Cool",
    "Zoo",
    "Zoológico",
    "Zoológico",
    "بابلو الياس",
    "متجر",
    "متجر سجاد",
    "متجر كتب نادرة",
    "理发店",
    "sucursal",
]
