# config/patterns.py  —  REPÚBLICA DOMINICANA  (v2, investigación profunda)
# =============================================================================
#
# Notas de uso:
#  - Texto normalizado a minúsculas.
#  - Variantes con y sin tilde ([eé], [ií], [oó], [aá], [uú]).
#  - "# ambiguo" = alto riesgo de falso positivo (ver AMBIGUOUS_PATTERNS).
#  - "# rebrand" = la marca cambió de nombre; útil para colapsar histórico.
#  - "# razón social" = aparece en glosas de tarjeta en vez de la marca.
# =============================================================================

CHAIN_REGEX = [
    # =========================================================================
    # SUPERMERCADOS — GRUPOS NACIONALES Y FORMATOS
    # =========================================================================
    r"\bla\s?sirena\b",
    r"\bsirena\b",
    r"\bmulticentro\s?la\s?sirena\b",
    r"\bmulticentro\s?sirena\b",
    r"\bsirena\s?market\b",
    r"\baprezio\b",
    r"\bgrupo\s?ramos\b",
    r"\bmultiplaza\b",
    r"\bsuper\s?pola\b",
    r"\bsuperpola\b",
    r"\bsupermercados?\s?pola\b",  # rebrand -> Sirena Market
    r"\bsupermercados?\s?nacional\b",
    r"\bsuper\s?nacional\b",
    r"\bcentro\s?cuesta\s?nacional\b",
    r"\bccn\b",
    r"\bjumbo\b",
    r"\bjumbo\s?express\b",
    r"\bmerca\s?jumbo\b",
    r"\bmercajumbo\b",
    r"\bla\s?despensa\b",
    r"\bcasa\s?cuesta\b",
    r"\bla\s?bodega\b",
    r"\bsupermercados?\s?bravo\b",
    r"\bsuper\s?bravo\b",
    r"\bhipermercados?\s?ol[eé]\b",
    r"\bsupermercados?\s?ol[eé]\b",
    r"\bhiper\s?ol[eé]\b",
    r"\bgrupo\s?ol[eé]\b",
    r"\bmercadal\b",
    r"\bfarma\s?ol[eé]\b",
    r"\bplaza\s?lama\b",
    r"\bsuper\s?lama\b",
    r"\belectrolama\b",
    r"\belectro\s?lama\b",
    r"\bpricesmart\b",
    r"\bprice\s?smart\b",
    r"\bcarrefour\b",
    r"\bcarrefour\s?market\b",
    r"\bcarrefour\s?city\b",
    r"\bsupermercados?\s?la\s?cadena\b",
    r"\bla\s?cadena\b",
    r"\bmercatodo\b",
    r"\bsuper\s?fresh\s?market\b",
    r"\bfresh\s?market\b",
    r"\btiendas?\s?ritmo\b",
    r"\bd1\b",
    r"\btiendas?\s?d1\b",
    # =========================================================================
    # SUPERMERCADOS REGIONALES Y LOCALES
    # =========================================================================
    r"\bhipermercados?\s?iberia\b",
    r"\biberia\s?supermercado\b",
    r"\bhiper\s?iberia\b",
    r"\bhipermercados?\s?la\s?fuente\b",
    r"\bsupermercados?\s?la\s?fuente\b",
    r"\bla\s?fuente\s?fun\b",
    r"\bsupermercados?\s?jos[eé]\s?luis\b",
    r"\bus1\b",
    r"\bus\s?1\s?supermercado\b",
    r"\bsupermercados?\s?soberano\b",
    r"\bsuper\s?soberano\b",
    r"\bcontigo\s?supermercados?\b",
    r"\bsupermercados?\s?garrido\b",
    r"\bwilmarket\b",
    r"\bwil\s?market\b",
    r"\bsuper\s?diverso\b",
    r"\bjanet'?s\s?supermarket\b",
    r"\blas\s?ca[nñ]as\s?market\s?place\b",
    r"\bel\s?drag[oó]n\s?de\s?oro\b",
    r"\bsuper\s?amigo\b",
    r"\bsuper\s?caribe\b",
    r"\bsuper\s?hong\s?kong\b",
    r"\bdbl\s?market\b",
    r"\balpha\s?market\b",
    r"\bcity\s?market\b",
    r"\bsuper\s?bohi[oó]\b",
    r"\bsuper\s?amistad\b",
    r"\bsuper\s?el\s?palacio\b",
    r"\bsuper\s?macor[ií]s\b",
    r"\bsuper\s?indiana\b",
    r"\bgran\s?porvenir\b",
    r"\bsuper\s?estrella\b",
    r"\bcomercial\s?carlos\b",
    r"\bsupermercado\s?pueblo\b",
    r"\bsupermercado\s?tit[aá]n\b",
    r"\bsupermercado\s?el\s?coloso\b",
    r"\bcasa\s?vel[aá]zquez\b",
    r"\bsupermercado\s?elah\b",
    r"\bmoncho'?s\b",
    # =========================================================================
    # MAYORISTAS Y DISTRIBUIDORES DE CONSUMO MASIVO
    # =========================================================================
    r"\bmercasid\b",
    r"\bmerca\s?sid\b",
    r"\bgrupo\s?sid\b",
    r"\binduveca\b",
    r"\bmanuel\s?gonz[aá]lez\s?cuesta\b",
    r"\bmgc\b",
    r"\bc[eé]sar\s?iglesias\b",
    r"\balmacenes?\s?hatuey\b",
    r"\balmacenes?\s?checo\b",
    r"\balmacenes?\s?le[oó]n\b",
    r"\balmacenes?\s?am[eé]rica\b",
    r"\balmacenes?\s?continente\b",
    r"\bcomercial\s?fila\b",
    r"\bempresas\s?morel\b",
    r"\baltacopa\b",
    r"\bsurtidora\s?suriel\b",
    r"\bgrupo\s?rodrigo\b",
    r"\bdilevsa\b",
    r"\bcolmado\b",
    r"\bcolmad[oó]n\b",
    r"\bsuper\s?colmado\b",  # categoría genérica RD
    # =========================================================================
    # COMBUSTIBLE, CONVENIENCIA DE ESTACIÓN Y GLP
    # =========================================================================
    r"\bshell\b",
    r"\bisla\s?dominicana\s?de\s?petr[oó]leo\b",
    r"\bisla\s?petr[oó]leo\b",
    r"\bidp\b",
    r"\besso\b",
    r"\bsol\s?investments\b",
    r"\bsol\s?petroleum\b",
    r"\btexaco\b",
    r"\bgulfstream\b",
    r"\bgulfstream\s?petroleum\b",
    r"\bgpd\b",
    r"\bchevron\b",
    r"\btotalenergies\b",
    r"\btotal\s?energies\b",
    r"\bestaci[oó]n\s?total\b",
    r"\bgasolineras?\s?total\b",
    r"\bsunix\b",
    r"\bsunix\s?petroleum\b",
    r"\bv\s?energy\b",
    r"\bestaci[oó]n\s?next\b",
    r"\bgasolineras?\s?next\b",
    r"\bdipsa\b",
    r"\bsigma\s?petroleum\b",
    r"\bsigma\b",
    r"\bpetrom[oó]vil\b",
    r"\bpetromovil\b",
    r"\beco\s?petr[oó]leo\b",
    r"\bpetronan\b",
    r"\brilix\b",
    r"\bunited\s?petroleum\b",
    r"\baxxon\b",
    r"\brefidomsa\b",
    r"\bcoastal\b",
    r"\bgrupo\s?mart[ií]\b",
    r"\bgrupo\s?lluberes\b",
    r"\bgasoil\s?xpress\b",
    r"\btransoil\b",
    r"\btrans[\s\-]?diesel\s?del\s?caribe\b",
    r"\bsynergy\s?group\b",
    r"\binterqu[ií]mica\b",
    r"\bmevosa\b",
    r"\bgaepell\b",
    r"\bbonjour\b",
    r"\bshell\s?select\b",
    r"\bsmart\s?shop\b",
    r"\bsmartshop\b",
    r"\bsmart\s?wash\b",
    r"\bquartz\s?auto\b",
    r"\btropigas\b",
    r"\bpropa[\s\-]?gas\b",
    r"\bpropagas\b",
    r"\bm[eé]trogas\b",
    r"\bcredigas\b",
    r"\bnativa\s?gas\b",
    r"\bonegas\b",
    r"\bone\s?gas\b",
    r"\brojo\s?gas\b",
    r"\bweni\s?gas\b",
    r"\bplater\s?gas\b",
    r"\balejo\s?gas\b",
    r"\bcoopegas\b",
    r"\bsolgas\b",
    r"\bgreigas\b",
    r"\bgas\s?caribe\b",
    r"\bgas\s?antillano\b",
    r"\b[oó]ptimo\s?gas\b",
    r"\benvasadora\s?de\s?gas\b",
    # =========================================================================
    # DELIVERY Y QUICK COMMERCE
    # =========================================================================
    r"\bpedidosya\b",
    r"\bpedidos\s?ya\b",
    r"\bpeya\b",
    r"\buber\s?eats\b",
    r"\bdidi\s?food\b",
    r"\bglovo\b",
    r"\bhugo\s?app\b",
    r"\bdeliverys\s?rd\b",
    r"\bcolmapp\b",
    r"\bkomida\b",
    r"\bfoodelise\b",
    r"\btable\s?hood\b",
    # =========================================================================
    # COMIDA RÁPIDA INTERNACIONAL
    # =========================================================================
    r"\bmc\s?donald'?s?\b",
    r"\bmcdonald'?s?\b",
    r"\bburger\s?king\b",
    r"\bburguer\s?king\b",
    r"\bwendy'?s\b",
    r"\bkfc\b",
    r"\bkentucky\s?fried\s?chicken\b",
    r"\bsubway\b",
    r"\btaco\s?bell\b",
    r"\bpizza\s?hut\b",
    r"\bdomino'?s?\s?pizza\b",
    r"\bdominos?\b",
    r"\bpapa\s?john'?s?\b",
    r"\blittle\s?caesars\b",
    r"\bkrispy\s?kreme\b",
    r"\bbaskin\s?robbins\b",
    r"\bh[aä]agen[\s\-]?dazs\b",
    r"\bhard\s?rock\s?caf[eé]\b",
    r"\btgi\s?fridays?\b",
    r"\bchili'?s\b",
    r"\btony\s?roma'?s\b",
    r"\b100\s?montaditos\b",
    r"\banthony'?s\s?coal\s?fired\b",
    r"\bsweet\s?frog\b",
    r"\byogen\s?fr[üu]z\b",
    r"\bjuan\s?valdez\b",
    r"\bfroots\b",
    r"\bquiznos\b",
    r"\bhooters\b",
    r"\bdenny'?s\b",
    r"\bihop\b",
    r"\bjohnny\s?rockets\b",
    r"\bshort\s?chicken\b",
    r"\bpopeye'?s?\b",
    r"\bcinnabon\b",
    # =========================================================================
    # COMIDA RÁPIDA Y RESTAURANTES DOMINICANOS
    # =========================================================================
    r"\bpollos?\s?victorina\b",
    r"\bvictorina\b",
    r"\bpollos?\s?rey\b",
    r"\bpica\s?pollo\b",  # categoría genérica, no cadena
    r"\bbarra\s?pay[aá]n\b",
    r"\bpanader[ií]a\s?pay[aá]n\b",
    r"\bpay[aá]n\b",
    r"\bbarra\s?el\s?pr[ií]ncipe\b",
    r"\bbarra\s?piantini\b",
    r"\bbarra\b",  # ambiguo
    r"\brico\s?hot\s?dog\b",
    r"\bemparedado\b",
    r"\bchef\s?pepper\b",
    r"\bpizza\s?man[ií]a\b",
    r"\bpizzamania\b",
    r"\bpala\s?pizza\b",
    r"\bpizza\s?house\b",
    r"\bpizzarelli\b",
    r"\bjade\s?teriyaki\b",
    r"\bjade\b",
    r"\badri[aá]n\s?tropical\b",
    r"\bel\s?conuco\b",
    r"\bbuche\s?perico\b",
    r"\bjalao\b",
    r"\bokra\b",
    r"\bviralata\b",
    r"\balegr[ií]a\b",
    r"\bel\s?mes[oó]n\s?de\s?la\s?cava\b",
    r"\bmes[oó]n\s?de\s?bari\b",
    r"\bvesuvio\b",
    r"\bvesubio\b",
    r"\bil\s?capo\b",
    r"\bbottega\b",
    r"\bmitre\b",
    r"\blul[uú]\s?tasting\b",
    r"\bpat'?e\s?palo\b",
    r"\bpate\s?palo\b",
    r"\bsbg\b",
    r"\bla\s?cassina\b",
    r"\bpeperoni\b",
    r"\bcentral\s?gastron[oó]mica\b",
    r"\bajual[aá]\b",
    r"\blaurel\b",
    r"\bboga\s?boga\b",
    r"\btrattoria\s?martini\b",
    r"\bangiolino\b",
    r"\bel\s?lina\b",
    r"\bsamur[aá]i\b",
    r"\bmakoto\b",
    r"\bnau\s?sushi\b",
    r"\btakumi\b",
    r"\bunagui\b",
    r"\brobata\b",
    r"\bshibuya\b",
    r"\bokazu\b",
    r"\bhoshi\b",
    r"\bsalseao\b",
    r"\byao\b",
    r"\ba\s?bocado\s?sushi\b",
    r"\balheli\s?sushi\b",
    r"\bsushi\s?ya\b",
    r"\bmesa\s?suprema\b",
    r"\bpapagayo\b",
    r"\bpositano\b",
    # =========================================================================
    # CAFETERÍAS, PANADERÍAS, REPOSTERÍA Y HELADOS
    # =========================================================================
    r"\bcaf[eé]\s?santo\s?domingo\b",
    r"\binduban\b",
    r"\bla\s?cafetera\b",
    r"\bpanavisa\b",
    r"\bcasa\s?barista\b",
    r"\bflor\s?de\s?caf[eé]\b",
    r"\bnocciola\b",
    r"\baffogato\b",
    r"\bciao\s?cafetteria\b",
    r"\bfresh\s?fresh\s?caf[eé]\b",
    r"\bla\s?linda\b",
    r"\bmamey\b",
    r"\bbaksa\b",
    r"\balterno\s?caf[eé]\b",
    r"\bsegafredo\b",
    r"\bnespresso\b",
    r"\bbuenhorno\b",
    r"\bbuen\s?horno\b",
    r"\bboulangerie\s?opera\b",
    r"\bbaked\s?by\s?rose\b",
    r"\bamable\s?pasteles\b",
    r"\bcandy\s?express\b",
    r"\bpan\s?(?:y|&)\s?m[aá]s\b",
    r"\bla\s?europea\b",
    r"\bcocoroco\b",
    r"\bdulcer[ií]a\s?dominicana\b",
    r"\bbany'?s\b",
    r"\bbimbo\b",
    r"\bhelados?\s?bon\b",
    r"\bhelados?\s?valentino\b",
    r"\bhelados?\s?sarita\b",
    r"\bla\s?dolcerie\b",
    r"\bla\s?desserterie\b",
    r"\bloretta\b",
    r"\btime\s?vegetarian\b",
    # =========================================================================
    # OPERADORES / FRANQUICIADOS (aparecen como razón social en glosas)
    # =========================================================================
    r"\bconservisa\b",
    r"\braya\s?food\b",
    r"\bgrupo\s?raya\b",
    r"\balimentos\s?raag\b",
    r"\braag\b",
    r"\balimentos\s?mac\b",
    r"\bheladom\b",
    r"\bcaribbean\s?catering\b",
    r"\bgrupo\s?conuco\b",
    # =========================================================================
    # FARMACIAS
    # =========================================================================
    r"\bfarmacias?\s?carol\b",
    r"\bcarol\b",  # ambiguo (nombre propio)
    r"\bfarmacias?\s?los\s?hidalgos\b",
    r"\blos\s?hidalgos\b",
    r"\bmedicar\s?gbc\b",
    r"\bfarmacias?\s?gbc\b",
    r"\bgbc\b",
    r"\bfarmax\b",
    r"\bfarmaxtra\b",
    r"\bfarma\s?xtra\b",
    r"\bfarmavalue\b",
    r"\bfarma\s?value\b",
    r"\bfarmacias?\s?el\s?sol\b",
    r"\bpharmangel\b",
    r"\bfarmacias?\s?del\s?pueblo\b",
    r"\bpromese\b",
    r"\bpromese\s?cal\b",
    r"\bfarmacias?\s?nepo\b",
    r"\bmassalud\b",
    r"\bfarmacia\s?macorix\b",
    r"\bfarmacias?\s?mima\b",
    r"\bfarmaplan\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    # =========================================================================
    # TIENDAS POR DEPARTAMENTO Y MULTITIENDAS
    # =========================================================================
    r"\balmacenes?\s?el\s?canal\b",
    r"\bel\s?canal\b",
    r"\btiendas?\s?la\s?isla\b",
    r"\bla\s?isla\b",
    r"\btiendas?\s?garrido\b",
    r"\bhipertiendas?\s?zaglul\b",
    r"\bzaglul\b",
    r"\balmacenes?\s?unidos?\b",
    r"\btiendas?\s?la\s?bomba\b",
    r"\bla\s?bomba\b",
    r"\balmacenes?\s?el\s?encanto\b",
    r"\btiendas?\s?sema\b",
    r"\bmax\s?comercial\b",
    r"\bcasa\s?ivelisse\b",
    r"\bcasa\s?colombia\b",
    r"\bleonardo\s?ahorro\b",
    r"\btiendas?\s?minaya\b",
    r"\balmacenes?\s?la\s?70\b",
    r"\baliss\b",
    r"\bla\s?baratosa\b",
    r"\bcasa\s?nader\b",
    r"\bmulticentro\s?ochoa\b",
    r"\btiendas?\s?ochoa\b",
    r"\bgrupo\s?ochoa\b",
    # =========================================================================
    # FERRETERÍAS Y MEJORAMIENTO DEL HOGAR
    # =========================================================================
    r"\bferreter[ií]a\s?ochoa\b",
    r"\bferreter[ií]a\s?americana\b",
    r"\bferreter[ií]a\s?bell[oó]n\b",
    r"\bferreter[ií]a\s?popular\b",
    r"\bferreter[ií]a\s?hach[eé]\b",
    r"\bferreter[ií]a\s?cuesta\b",
    r"\bferreter[ií]a\s?mc\b",
    r"\binnovacentro\b",
    r"\bla\s?innovaci[oó]n\b",
    r"\bikea\b",
    r"\bnaterial\b",
    r"\bepa\b",
    r"\bferreter[ií]a\b",
    # =========================================================================
    # TECNOLOGÍA, ELECTRO Y VARIEDADES
    # =========================================================================
    r"\btiendas?\s?corripio\b",
    r"\bcorripio\b",
    r"\bdistribuidora\s?corripio\b",
    r"\bradiocentro\b",
    r"\bla\s?curacao\b",
    r"\bla\s?cura[cç]ao\b",
    r"\bl\s?(?:y|&)\s?r\s?comercial\b",
    r"\bmultic[oó]mputos\b",
    r"\bmulticomputos\b",
    r"\bminiso\b",
    r"\bmumuso\b",
    r"\bilahui\b",
    r"\bjuguet[oó]n\b",
    r"\bcuesta\s?libros\b",
    r"\bbebemundo\b",
    r"\bbebe\s?mundo\b",
    r"\boptimax\b",
    r"\b[oó]ptica\s?caroni\b",
    r"\bvita\s?salud\b",
    r"\bmail\s?boxes\b",
    # =========================================================================
    # MODA, CALZADO, DEPORTE Y LUJO
    # =========================================================================
    r"\bzara\b",
    r"\bpull\s?(?:and|&)?\s?bear\b",
    r"\bmassimo\s?dutti\b",
    r"\bbershka\b",
    r"\bstradivarius\b",
    r"\boysho\b",
    r"\buterq[uü]e\b",
    r"\baldo\b",
    r"\bsteve\s?madden\b",
    r"\bu\.?s\.?\s?polo\b",
    r"\bpayless\b",
    r"\bego\b",
    r"\bbakers\b",
    r"\bcrocs\b",
    r"\bbarone\b",
    r"\btotto\b",
    r"\bsportline\b",
    r"\bsport\s?line\b",
    r"\bsport\s?city\b",
    r"\bsportcity\b",
    r"\bswarovski\b",
    r"\btous\b",
    r"\bparfois\b",
    r"\bl'?occitane\b",
    r"\bmac\s?cosmetics\b",
    r"\blouis\s?vuitton\b",
    r"\bcartier\b",
    r"\bferragamo\b",
    r"\bcarolina\s?herrera\b",
    r"\bbenetton\b",
    r"\bnautica\b",
    r"\btommy\s?hilfiger\b",
    r"\bnike\b",
    r"\badidas\b",
    r"\bskechers\b",
    r"\bforever\s?21\b",
    r"\bh&m\b",
    # =========================================================================
    # AUTOMOTRIZ
    # =========================================================================
    r"\bgrupo\s?viamar\b",
    r"\bviamar\b",
    r"\bdelta\s?comercial\b",
    r"\bautozama\b",
    r"\bsanto\s?domingo\s?motors\b",
    r"\bavelino\s?abreu\b",
    r"\bperavia\s?motors\b",
    r"\bbonanza\s?dominicana\b",
    r"\bmagna\s?motors\b",
    r"\bautogerm[aá]nica\b",
    r"\bpeynado\b",
    r"\breid\s?(?:y|&)\s?compa[nñ][ií]a\b",
    r"\bagencia\s?bella\b",
    r"\bautobrit[aá]nica\b",
    r"\bedom\b",
    r"\bt[eé]cnica\s?cxa\b",
    # =========================================================================
    # BANCA
    # =========================================================================
    r"\bbanreservas\b",
    r"\bbanco\s?de\s?reservas\b",
    r"\bbanco\s?popular\b",
    r"\bpopular\s?dominicano\b",
    r"\bbpd\b",
    r"\bbhd\b",
    r"\bbhd\s?le[oó]n\b",
    r"\bbanco\s?bhd\b",
    r"\bbanco\s?le[oó]n\b",
    r"\bbanco\s?santa\s?cruz\b",
    r"\bbanco\s?caribe\b",
    r"\bscotiabank\b",
    r"\bcitibank\b",
    r"\bbanesco\b",
    r"\bbanco\s?promerica\b",
    r"\bpromerica\b",
    r"\bbanco\s?bdi\b",
    r"\bbanco\s?l[oó]pez\s?de\s?haro\b",
    r"\bbanco\s?vimenca\b",
    r"\bvimenca\b",
    r"\bbancam[eé]rica\b",
    r"\bbanco\s?ademi\b",
    r"\bademi\b",
    r"\bbanco\s?agr[ií]cola\b",
    r"\bbagr[ií]cola\b",
    r"\bbandex\b",
    r"\bqik\b",
    r"\bqik\s?banco\b",
    r"\bbaninter\b",
    r"\bbanco\s?intercontinental\b",
    r"\bbancr[eé]dito\b",
    r"\bbanco\s?mercantil\b",
    r"\bbanco\s?nacional\s?de\s?cr[eé]dito\b",
    r"\bbanco\s?del\s?progreso\b",
    r"\bdominicano\s?del\s?progreso\b",
    r"\brepublic\s?bank\b",
    r"\baltas\s?cumbres\b",
    r"\bbanco\s?peravia\b",
    r"\badopem\b",
    r"\bbanco\s?confisa\b",
    r"\bmotor\s?cr[eé]dito\b",
    r"\bbanco\s?r[ií]o\b",
    r"\bfihogar\b",
    r"\bbancotu[ií]\b",
    r"\bbanco\s?atl[aá]ntico\b",
    r"\bbanco\s?bonanza\b",
    r"\bbanco\s?empire\b",
    r"\bbanco\s?uni[oó]n\b",
    r"\bbanco\s?federal\b",
    r"\bgruficorp\b",
    r"\bcofaci\b",
    r"\bbanco\s?atlas\b",
    r"\bbanco\s?bda\b",
    r"\bbellbank\b",
    r"\bidecosa\b",
    r"\bbanaci\b",
    r"\bapap\b",
    r"\basociaci[oó]n\s?popular\b",
    r"\bacap\b",
    r"\basociaci[oó]n\s?cibao\b",
    r"\bla\s?nacional\b",
    r"\balnap\b",
    r"\balaver\b",
    r"\basociaci[oó]n\s?la\s?vega\s?real\b",
    r"\basociaci[oó]n\s?duarte\b",
    r"\basociaci[oó]n\s?bonao\b",
    r"\basociaci[oó]n\s?mocana\b",
    r"\basociaci[oó]n\s?romana\b",
    r"\basociaci[oó]n\s?barahona\b",
    r"\basociaci[oó]n\s?maguana\b",
    r"\basociaci[oó]n\s?hig[uü]eyana\b",
    r"\basociaci[oó]n\s?noroestana\b",
    r"\basociaci[oó]n\s?peravia\b",
    r"\bbanco\s?central\b",
    r"\bsuperintendencia\s?de\s?bancos\b",
    # =========================================================================
    # COOPERATIVAS
    # =========================================================================
    r"\bcooperativa\s?vega\s?real\b",
    r"\bcoopnama\b",
    r"\bcoopsano\b",
    r"\bcooperativa\s?herrera\b",
    r"\bmomesa\b",
    r"\bcoop[\s\-]?central\b",
    r"\bidecoop\b",
    r"\bcooperativa\b",
    # =========================================================================
    # MEDIOS DE PAGO Y REMESAS
    # =========================================================================
    r"\bcardnet\b",
    r"\bazul\b",  # ambiguo (color)
    r"\bvisanet\b",
    r"\btpago\b",
    r"\bt[\s\-]?pago\b",
    r"\bwestern\s?union\b",
    r"\bcaribe\s?express\b",
    r"\bria\b",  # ambiguo
    r"\bremesas\s?quisqueyana\b",
    r"\bquisqueyana\b",
    r"\bbm\s?cargo\b",
    r"\bagente\s?de\s?cambio\b",
    r"\bcasa\s?de\s?cambio\b",
    # =========================================================================
    # SEGUROS, ARS Y AFP
    # =========================================================================
    r"\bseguros\s?universal\b",
    r"\bseguros\s?reservas\b",
    r"\bla\s?colonial\b",
    r"\bmapfre\b",
    r"\bmapfre\s?bhd\b",
    r"\bhumano\s?seguros\b",
    r"\bhumano\b",
    r"\bseguros\s?sura\b",
    r"\bsura\b",
    r"\bproseguros\b",
    r"\bseguros\s?pep[ií]n\b",
    r"\bpep[ií]n\b",
    r"\bworldwide\b",
    r"\bla\s?monumental\b",
    r"\bangloamericana\b",
    r"\batl[aá]ntica\s?seguros\b",
    r"\bgeneral\s?de\s?seguros\b",
    r"\bpatrimonial\b",
    r"\bcoop[\s\-]?seguros\b",
    r"\bbmi\b",
    r"\bars\s?humano\b",
    r"\bars\s?palic\b",
    r"\bpalic\b",
    r"\bars\s?universal\b",
    r"\bsenasa\b",
    r"\bars\s?futuro\b",
    r"\bars\s?renacer\b",
    r"\bars\s?primera\b",
    r"\bars\s?monumental\b",
    r"\bars\s?reservas\b",
    r"\bars\s?meta\s?salud\b",
    r"\bars\s?simag\b",
    r"\bars\s?yun[eé]n\b",
    r"\bsemma\b",
    r"\bars\s?aps\b",
    r"\bars\s?cmd\b",
    r"\bars\s?gma\b",
    r"\bars\b",
    r"\bsisalril\b",
    r"\bafp\s?popular\b",
    r"\bafp\s?reservas\b",
    r"\bafp\s?siembra\b",
    r"\bafp\s?crecer\b",
    r"\bscotia\s?crecer\b",
    r"\bafp\s?romana\b",
    r"\bafp\s?atl[aá]ntico\b",
    r"\bafp\b",
    r"\bsipen\b",
    # =========================================================================
    # TELECOMUNICACIONES
    # =========================================================================
    r"\bclaro\b",
    r"\bclaro\s?dominicana\b",
    r"\bcodetel\b",
    r"\bcompa[nñ][ií]a\s?dominicana\s?de\s?tel[eé]fonos\b",
    r"\bverizon\b",
    r"\baltice\b",
    r"\baltice\s?dominicana\b",
    r"\borange\b",
    r"\btricom\b",
    r"\bviva\b",
    r"\btrilogy\b",
    r"\bcentennial\b",
    r"\bwind\s?telecom\b",
    r"\bwind\b",
    r"\bsky\b",
    r"\baster\b",
    r"\bstar\s?cable\b",
    r"\bonemax\b",
    r"\btelecable\b",
    r"\bcablevisi[oó]n\b",
    r"\bindotel\b",
    r"\bstarlink\b",
    # =========================================================================
    # ELECTRICIDAD Y AGUA
    # =========================================================================
    r"\bedesur\b",
    r"\bedenorte\b",
    r"\bedeeste\b",
    r"\bede\s?este\b",
    r"\bcdeee\b",
    r"\bcde\b",
    r"\beted\b",
    r"\begehid\b",
    r"\bege\s?haina\b",
    r"\bege\s?itabo\b",
    r"\bcepm\b",
    r"\bconsorcio\s?energ[eé]tico\s?punta\s?cana\b",
    r"\baes\s?dominicana\b",
    r"\bpunta\s?catalina\b",
    r"\bsie\b",
    r"\bcaasd\b",
    r"\binapa\b",
    r"\bcoraasan\b",
    r"\bcoraapplata\b",
    r"\bcoraaplata\b",
    r"\bcoraamoca\b",
    r"\bcoraarom\b",
    r"\bcoraavega\b",
    r"\bcoraabo\b",
    r"\bindrhi\b",
    # =========================================================================
    # SALUD
    # =========================================================================
    r"\bcedimat\b",
    r"\bplaza\s?de\s?la\s?salud\b",
    r"\bhgps\b",
    r"\bcl[ií]nica\s?abreu\b",
    r"\bcentro\s?m[eé]dico\s?corominas\b",
    r"\bcorominas\b",
    r"\bhoms\b",
    r"\bhospital\s?metropolitano\s?de\s?santiago\b",
    r"\bcl[ií]nica\s?uni[oó]n\s?m[eé]dica\b",
    r"\buni[oó]n\s?m[eé]dica\b",
    r"\bhospiten\b",
    r"\bcentro\s?m[eé]dico\s?real\b",
    r"\bcabral\s?y\s?b[aá]ez\b",
    r"\bcentro\s?m[eé]dico\s?punta\s?cana\b",
    r"\bidss\b",
    r"\bidoppril\b",
    r"\blaboratorio\s?referencia\b",
    r"\bamadita\b",
    r"\bpatria\s?rivas\b",
    r"\bsns\b",
    r"\bunap\b",
    r"\bcpn\b",
    r"\bcentro\s?de\s?primer\s?nivel\b",
    r"\bcentro\s?de\s?salud\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\bdispensario\b",
    r"\blaboratorio\b",
    r"\bmispas\b",
    r"\bsespas\b",
    # =========================================================================
    # CORREO Y COURIER
    # =========================================================================
    r"\binposdom\b",
    r"\bcorreos\s?dominicanos\b",
    r"\beps\b",
    r"\baerocargo\b",
    r"\bdhl\b",
    r"\bfedex\b",
    r"\bups\b",
    # =========================================================================
    # HOTELERÍA — CADENAS Y MARCAS (todo incluido)
    # =========================================================================
    r"\bbarcel[oó]\b",
    r"\boccidental\b",
    r"\broyal\s?hideaway\b",
    r"\ballegro\b",
    r"\biberostar\b",
    r"\biberostar\s?waves\b",
    r"\biberostar\s?selection\b",
    r"\bjoia\b",
    r"\bbah[ií]a\s?principe\b",
    r"\bgrupo\s?pi[nñ]ero\b",
    r"\briu\b",
    r"\bmeli[aá]\b",
    r"\bparadisus\b",
    r"\bzel\b",
    r"\bpalladium\b",
    r"\bgrand\s?palladium\b",
    r"\btrs\b",
    r"\bfiesta\s?hotel\b",
    r"\bcatalonia\b",
    r"\blopesan\b",
    r"\bamresorts\b",
    r"\bam\s?resorts\b",
    r"\bhyatt\s?inclusive\b",
    r"\bsecrets\b",
    r"\bdreams\b",
    r"\bbreathless\b",
    r"\bzo[eë]try\b",
    r"\bsunscape\b",
    r"\bhyatt\s?ziva\b",
    r"\bhyatt\s?zilara\b",
    r"\bhyatt\s?vivid\b",
    r"\bnow\s?(?:onyx|larimar|garden)\b",
    r"\bbe\s?live\b",
    r"\bmajestic\b",
    r"\bocean\s?by\s?h10\b",
    r"\bh10\b",
    r"\bocean\s?(?:blue|sand|el\s?faro)\b",
    r"\bviva\s?wyndham\b",
    r"\bviva\s?by\s?wyndham\b",
    r"\bwyndham\b",
    r"\bexcellence\b",
    r"\bfinest\b",
    r"\bkarisma\b",
    r"\bnickelodeon\b",
    r"\bmargaritaville\b",
    r"\bserenade\b",
    r"\blive\s?aqua\b",
    r"\bimpressive\b",
    r"\bwhala\b",
    r"\bprincess\b",
    r"\bhodelpa\b",
    r"\bemotions\b",
    r"\bgrupo\s?puntacana\b",
    r"\bpuntacana\s?resort\b",
    r"\bplaya\s?hotels\b",
    r"\blifestyle\s?holidays\b",
    r"\bcasa\s?de\s?campo\b",
    r"\btortuga\s?bay\b",
    r"\bwestin\b",
    r"\bfour\s?points\b",
    r"\bcoral\s?costa\s?caribe\b",
    r"\bclub\s?med\b",
    r"\bstarwood\b",
    r"\bhard\s?rock\s?hotel\b",
    r"\bgrand\s?sirenis\b",
    r"\bvista\s?sol\b",
    r"\bplayabachata\b",
    r"\bsenator\b",
    r"\beden\s?roc\b",
    r"\bamanera\b",
    r"\bfour\s?seasons\b",
    r"\bsanctuary\s?cap\s?cana\b",
    r"\balsol\b",
    r"\bcasa\s?colonial\b",
    r"\bsublime\s?samana\b",
    r"\bcayo\s?levantado\b",
    # =========================================================================
    # HOTELES URBANOS
    # =========================================================================
    r"\bmarriott\b",
    r"\bjw\s?marriott\b",
    r"\bsheraton\b",
    r"\brenaissance\b",
    r"\bjaragua\b",
    r"\baloft\b",
    r"\bhilton\b",
    r"\bembassy\s?suites\b",
    r"\bhomewood\s?suites\b",
    r"\bhampton\b",
    r"\bcrowne\s?plaza\b",
    r"\bintercontinental\b",
    r"\breal\s?intercontinental\b",
    r"\bel\s?embajador\b",
    r"\bdominican\s?fiesta\b",
    r"\bnicol[aá]s\s?de\s?ovando\b",
    r"\bcaribe\s?colonial\b",
    r"\bnovus\s?plaza\b",
    r"\bgran\s?almirante\b",
    r"\bgarden\s?court\b",
    r"\bcurio\s?collection\b",
    r"\bhyatt\s?centric\b",
    r"\bhyatt\s?place\b",
    r"\bholiday\s?inn(?:\s?express)?\b",
    r"\bcourtyard\b",
    r"\bradisson\b",
    r"\bbest\s?western\b",
    r"\bbillini\b",
    r"\bhotel\s?franc[eé]s\b",
    r"\bhotel\s?riazor\b",
    r"\bvilla\s?colonial\b",
    r"\bmosquito\s?boutique\b",
    r"\bluca\s?hotel\b",
    r"\bairbnb\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\baparthotel\b",
    r"\bvilla\b",
    # =========================================================================
    # CASINOS, LOTERÍAS Y BANCAS DE APUESTAS
    # =========================================================================
    r"\bleidsa\b",
    r"\bloter[ií]a\s?nacional\b",
    r"\bloteka\b",
    r"\bla\s?primera\b",
    r"\bloto\s?real\b",
    r"\bquiniela\s?pale\b",
    r"\bquiniela\b",
    r"\bpale\b",
    r"\bganam[aá]s\b",
    r"\bbanca\s?loto\b",
    r"\blotedom\b",
    r"\bsuperm[aá]s\b",
    r"\bla\s?suerte\b",
    r"\bbanca\s?de\s?loter[ií]a\b",
    r"\bbanca\s?de\s?apuestas\b",
    r"\bcasa\s?de\s?apuestas\b",
    r"\bcasino\b",
    r"\bsala\s?de\s?juegos\b",
    # =========================================================================
    # CINES, MALLS Y ENTRETENCIÓN
    # =========================================================================
    r"\bcaribbean\s?cinemas\b",
    r"\bpalacio\s?del\s?cine\b",
    r"\bfine\s?arts\b",
    r"\bmegaplex\b",
    r"\bbowlerama\b",
    r"\b[aá]gora\s?mall\b",
    r"\bblue\s?mall\b",
    r"\bsambil\b",
    r"\bdowntown\s?center\b",
    r"\bgaler[ií]a\s?360\b",
    r"\bacr[oó]polis\b",
    r"\bmegacentro\b",
    r"\bnovocentro\b",
    r"\bbella\s?terra\b",
    r"\bplaza\s?central\b",
    r"\bsilver\s?sun\b",
    r"\bsans\s?souci\b",
    r"\bocean\s?world\b",
    r"\bmanat[ií]\s?park\b",
    r"\bscape\s?park\b",
    r"\bjet\s?set\b",
    r"\boz\b",
    r"\bclub\s?malecon\b",
    r"\birish\s?pub\b",
    r"\bo'?\s?reilly'?s\b",
    r"\bpraia\b",
    r"\bvertigo\b",
    # =========================================================================
    # GIMNASIOS
    # =========================================================================
    r"\bgympro\b",
    r"\bgym\s?pro\b",
    r"\bbody\s?shop\s?athletic\b",
    r"\bbody\s?shop\b",
    r"\bworld\s?fitness\b",
    r"\bsmart\s?fit\b",
    r"\bsmartfit\b",
    r"\bgold'?s?\s?gym\b",
    r"\banytime\s?fitness\b",
    r"\bcrossfit\b",
    r"\bcross\s?fit\b",
    r"\borangetheory\b",
    r"\bgimnasio\b",
    # =========================================================================
    # TRANSPORTE Y MOVILIDAD
    # =========================================================================
    r"\barajet\b",
    r"\bsky\s?high\b",
    r"\bair\s?century\b",
    r"\bcopa\s?airlines\b",
    r"\bjetblue\b",
    r"\baerodom\b",
    r"\blas\s?am[eé]ricas\b",
    r"\bcaribe\s?tours\b",
    r"\bmetro\s?tours\b",
    r"\bexpreso\s?b[aá]varo\b",
    r"\baetra\b",
    r"\bsichoem\b",
    r"\bomsa\b",
    r"\bopret\b",
    r"\bintrant\b",
    r"\bmetro\s?de\s?santo\s?domingo\b",
    r"\btelef[eé]rico\b",
    r"\bpeaje\b",
    r"\bhertz\b",
    r"\bavis\b",
    r"\bbudget\b",
    r"\beuropcar\b",
    r"\bsixt\b",
    r"\bnelly\s?rent\b",
    r"\buber\b",
    r"\bindrive\b",
    r"\bcabify\b",
    # =========================================================================
    # EDUCACIÓN
    # =========================================================================
    r"\buasd\b",
    r"\bpucmm\b",
    r"\bintec\b",
    r"\bunibe\b",
    r"\bunapec\b",
    r"\butesa\b",
    r"\bo&m\b",
    r"\buniversidad\s?o\s?(?:y|&)\s?m\b",
    r"\buce\b",
    r"\bunphu\b",
    r"\bucsd\b",
    r"\bitla\b",
    r"\bbarna\b",
    r"\bunicaribe\b",
    r"\buapa\b",
    r"\bufhec\b",
    r"\binfotep\b",
    r"\buniversidad\b",
    r"\bpolit[eé]cnico\b",
    r"\bliceo\b",
    r"\bescuela\s?b[aá]sica\b",
    r"\bescuela\b",
    r"\bcolegio\b",
    # =========================================================================
    # INSTITUCIONES PÚBLICAS Y COMUNITARIAS
    # =========================================================================
    r"\bayuntamiento\b",
    r"\bjunta\s?municipal\b",
    r"\bdistrito\s?municipal\b",
    r"\bjunta\s?de\s?vecinos\b",
    r"\bcasa\s?comunal\b",
    r"\bcasa\s?de\s?cultura\b",
    r"\bclub\s?deportivo\b",
    r"\bdestacamento\b",
    r"\bpolic[ií]a\s?nacional\b",
    r"\bcuerpo\s?de\s?bomberos\b",
    r"\bbomberos\b",
    r"\bdefensa\s?civil\b",
    r"\bjce\b",
    r"\bjunta\s?central\s?electoral\b",
    r"\boficial[ií]a\b",
    r"\bprogresando\s?con\s?solidaridad\b",
    r"\bsupérate\b",
    r"\bsuperate\b",
    r"\bcomedores\s?econ[oó]micos\b",
    r"\binabie\b",
    r"\binaipi\b",
    r"\bestancia\s?infantil\b",
    r"\bparroquia\b",
    r"\biglesia\b",
    r"\bgobernaci[oó]n\b",
    r"\bministerio\b",
    r"\bsenasa\s?oficina\b",
    # =========================================================================
    # COMODINES SECTORIALES (baja precisión: última pasada)
    # =========================================================================
    r"\bagro",
    r"\bvet",
    r"\bforraj",
    r"\bvivero\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\balmac[eé]n\b",
    r"\bdep[oó]sito\b",
    r"\bcarnicer[ií]a\b",
    r"\bpescader[ií]a\b",
    r"\bpanader[ií]a\b",
    r"\brepostería\b",
    r"\bel[eé]ctric",
    r"\belectronic",
    r"\balbergue\b",
    r"\bcafeter[ií]a\b",
    r"\bcomedor\b",
    r"\bbanca\b",
]


# =============================================================================
# Patrones de ALTO riesgo de falso positivo. Están incluidos arriba; esta lista
# permite excluirlos en una primera pasada limpia:
#     SAFE_CHAIN_REGEX = [p for p in CHAIN_REGEX if p not in AMBIGUOUS_PATTERNS]
# =============================================================================
AMBIGUOUS_PATTERNS = {
    r"\bazul\b",
    r"\bria\b",
    r"\bcarol\b",
    r"\bbarra\b",
    r"\bjade\b",
    r"\byao\b",
    r"\boz\b",
    r"\bviva\b",
    r"\bsky\b",
    r"\baster\b",
    r"\bclaro\b",
    r"\borange\b",
    r"\bwind\b",
    r"\bsura\b",
    r"\bhumano\b",
    r"\bpep[ií]n\b",
    r"\bpalic\b",
    r"\bdreams\b",
    r"\bsecrets\b",
    r"\bprincess\b",
    r"\bmajestic\b",
    r"\bzel\b",
    r"\bjoia\b",
    r"\btrs\b",
    r"\bh10\b",
    r"\bfinest\b",
    r"\bexcellence\b",
    r"\bimpressive\b",
    r"\bwhala\b",
    r"\bemotions\b",
    r"\ballegro\b",
    r"\boccidental\b",
    r"\briu\b",
    r"\bd1\b",
    r"\bego\b",
    r"\bbakers\b",
    r"\bdelta\s?comercial\b",
    r"\bedom\b",
    r"\bgbc\b",
    r"\beps\b",
    r"\bups\b",
    r"\bsns\b",
    r"\bcpn\b",
    r"\bunap\b",
    r"\bars\b",
    r"\bafp\b",
    r"\bsie\b",
    r"\bcde\b",
    r"\bpale\b",
    r"\bquiniela\b",
    r"\bcasino\b",
    r"\bbanca\b",
    r"\bla\s?primera\b",
    r"\bla\s?suerte\b",
    r"\bla\s?nacional\b",
    r"\bla\s?isla\b",
    r"\bla\s?bomba\b",
    r"\bel\s?canal\b",
    r"\bla\s?bodega\b",
    r"\bla\s?cadena\b",
    r"\bla\s?colonial\b",
    r"\bfresh\s?market\b",
    r"\bpica\s?pollo\b",
    r"\bcolmado\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\balmac[eé]n\b",
    r"\bdep[oó]sito\b",
    r"\bcomedor\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\bvilla\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    r"\bcl[ií]nica\b",
    r"\bhospital\b",
    r"\blaboratorio\b",
    r"\bdispensario\b",
    r"\bescuela\b",
    r"\bcolegio\b",
    r"\buniversidad\b",
    r"\bliceo\b",
    r"\bgimnasio\b",
    r"\bferreter[ií]a\b",
    r"\bpanader[ií]a\b",
    r"\bcafeter[ií]a\b",
    r"\biglesia\b",
    r"\bparroquia\b",
    r"\bministerio\b",
    r"\bpeaje\b",
    r"\bbudget\b",
    r"\bcopa\s?airlines\b",
    r"\bepa\b",
}
