# config/patterns.py  —  CHILE  (v2, investigación profunda)
# =============================================================================
# Módulo 2: Cadenas (adaptación a Chile del listado original de RD)
# Fuente estructural: 1_Limpieza_Duplicados_Cadenas.ipynb
#
# Cobertura: ~700 marcas verificadas con fuente (CMF, SUSESO, SISS, SEC/CNE,
# SUBTEL, MINSAL/DEIS, ASACH, SERNAC, prensa económica chilena), vigentes y
# discontinuadas de los últimos ~15 años. Las discontinuadas se incluyen a
# propósito: siguen apareciendo en data histórica.
#
# Notas de uso:
#  - Todos los patrones asumen texto normalizado a minúsculas.
#  - Se mantienen variantes con y sin tilde ([eé], [ií], [oó], [aá], [uú])
#    para tolerar datos sin acentuación.
#  - Los patrones marcados "# ambiguo" pueden generar falsos positivos
#    (palabras del español común, apellidos, topónimos). Revisar antes de
#    activarlos sobre texto libre; ver AMBIGUOUS_PATTERNS al final.
#  - Los patrones marcados "# rebrand" corresponden a marcas cuyo nombre
#    cambió: útil para colapsar histórico a la entidad actual.
# =============================================================================

CHAIN_REGEX = [
    # =========================================================================
    # SUPERMERCADOS — CADENAS NACIONALES Y FORMATOS
    # =========================================================================
    r"\bl[ií]der\b",
    r"\bhiper\s?l[ií]der\b",
    r"\bhiperl[ií]der\b",
    r"\bexpress\s?de\s?l[ií]der\b",
    r"\bl[ií]der\s?express\b",
    r"\blider\s?exp\b",
    r"\bsuper\s?bodega\s?a\s?cuenta\b",
    r"\bsuperbodega\s?acuenta\b",
    r"\bsb\s?a\s?cuenta\b",
    r"\bacuenta\b",
    r"\ba\s?cuenta\b",
    r"\bcentral\s?mayorista\b",
    r"\bekono\b",
    r"\balmac\b",
    r"\balmacs\b",
    r"\bwalmart\b",
    r"\bwal[\s\-]?mart\b",
    r"\bd\s?(?:y|&)\s?s\b",  # rebrand D&S -> Walmart
    r"\bdistribuci[oó]n\s?y\s?servicio\b",
    r"\bjumbo\b",
    r"\bhiper\s?jumbo\b",
    r"\bsanta\s?isabel\b",
    r"\bsta\.?\s?isabel\b",
    r"\bcencosud\b",
    r"\bspid\b",
    r"\bspid\s?35\b",
    r"\bspid35\b",
    r"\btops\b",
    r"\blas\s?brisas\b",
    r"\bmontecarlo\b",
    r"\bmonte\s?carlo\b",
    r"\beconomax\b",
    r"\bmultimarket\b",
    r"\bmarmentini\b",
    r"\bagas\b",
    r"\bunimarc\b",
    r"\buni\s?marc\b",
    r"\brendic\b",
    r"\brendic\s?hnos\b",
    r"\balvi\b",
    r"\bclub\s?alvi\b",
    r"\bsuper\s?10\b",
    r"\bsuper10\b",
    r"\bmayorista\s?10\b",
    r"\bmayorista10\b",
    r"\bsmu\b",
    r"\bhipermarc\b",
    r"\bmultiahorro\b",
    r"\bmulti\s?ahorro\b",
    r"\bok\s?market\b",
    r"\bokmarket\b",
    r"\btelemercados\b",
    r"\bdipac\b",
    r"\bdeca\b",
    r"\bbryc\b",
    r"\bkorlaet\b",
    r"\bcofrima\b",
    r"\babu\s?gosch\b",
    r"\babugosch\b",
    r"\bsupermercados?\s?del\s?sur\b",
    r"\bbigger\b",
    r"\bkeymarket\b",
    r"\bkey\s?market\b",
    r"\bmu[nñ]oz\s?hermanos\b",
    r"\bpuerto\s?cristo\b",
    r"\bdiproc\b",
    r"\btottus\b",
    r"\bhiper\s?tottus\b",
    r"\bprecio\s?uno\b",
    # =========================================================================
    # SUPERMERCADOS REGIONALES (verificados; socios ASACH y locales)
    # =========================================================================
    r"\bcugat\b",
    r"\b[uú]nico\b",  # ambiguo ("único")
    r"\bhiper\s?patag[oó]nico\b",
    r"\bhiperpatag[oó]nico\b",
    r"\biguaz[uú]\b",
    r"\bla\s?colchag[uü]ina\b",
    r"\bla\s?fama\b",
    r"\bcrossmarket\b",
    r"\bcross\s?market\b",
    r"\bpuritan\b",
    r"\brofil\b",
    r"\bromanini\b",
    r"\beltit\b",
    r"\bprovimarket\b",
    r"\bsupermercados?\s?el\s?9\b",
    r"\bsuper\s?9\b",
    r"\bsuper9\b",
    r"\bsuper\s?el\s?tr[eé]bol\b",
    r"\bsupermercados?\s?o'?higgins\b",
    r"\berbi\b",
    r"\bsanta\s?beatriz\b",
    r"\blubba\b",
    r"\bahorrem[aá]s\b",
    r"\bopen\s?group\b",
    r"\bmontserrat\b",
    r"\bmonserrat\b",
    r"\bel\s?carnicero\b",
    r"\bla\s?caserita\b",
    r"\bdicomex\b",
    r"\bfruna\b",
    # =========================================================================
    # MAYORISTAS Y DISTRIBUIDORES
    # =========================================================================
    r"\badelco\b",
    r"\brabi[eé]\b",
    r"\basf\s?log[ií]stica\b",
    r"\bla\s?oferta\b",
    r"\buno\s?market\b",
    r"\bgonzalito\b",
    r"\bmersan\b",
    r"\bvega\s?central\b",
    r"\blo\s?valledor\b",
    r"\bmercado\s?mayorista\b",
    r"\bferia\s?libre\b",
    r"\bmakro\b",
    # =========================================================================
    # TIENDAS DE CONVENIENCIA
    # =========================================================================
    r"\bpronto\s?copec\b",
    r"\bpunto\s?copec\b",
    r"\barcoprime\b",
    r"\bpronto\b",  # ambiguo
    r"\bupa!?\b",
    r"\bupita!?\b",
    r"\bastop\b",
    r"\baramco\s?stop\b",
    r"\ba[\s\-]?stop\b",
    r"\bspacio\s?1\b",
    r"\bspacio1\b",
    r"\bspacio\s?uno\b",
    r"\boxxo\b",
    r"\bbig\s?john\b",
    r"\bbigjohn\b",
    r"\bminimarket\b",
    r"\bmini\s?market\b",
    r"\bminimercado\b",
    r"\bseven\s?eleven\b",
    r"\b7[\s\-]?eleven\b",
    # =========================================================================
    # COMBUSTIBLE, ELECTROMOVILIDAD Y GAS
    # =========================================================================
    r"\bcopec\b",
    r"\bempresas\s?copec\b",
    r"\bshell\b",
    r"\benex\b",
    r"\baramco\b",
    r"\besmax\b",
    r"\bpetrobras\b",  # rebrand -> Aramco
    r"\bterpel\b",
    r"\bypf\b",
    r"\brepsol\b",
    r"\bpetroprix\b",
    r"\bjlc\b",
    r"\bhugo\s?n[aá]jle\b",
    r"\bempresas\s?hn\b",
    r"\bestaci[oó]n\s?de\s?servicio\b",
    r"\bservicentro\b",
    r"\bbencinera\b",
    r"\benap\b",
    r"\bempresa\s?nacional\s?del\s?petr[oó]leo\b",
    r"\bcopec\s?voltex\b",
    r"\bvoltex\b",
    r"\benel\s?x(?:\s?way)?\b",
    r"\bmetrogas\b",
    r"\bgasvalpo\b",
    r"\benergas\b",
    r"\bgas\s?sur\b",
    r"\bgassur\b",
    r"\bintergas\b",
    r"\bgasco\b",
    r"\bsolgas\b",
    r"\binnergy\b",
    r"\blipigas\b",
    r"\babastible\b",
    r"\bgas\s?hn\b",
    r"\bgas\s?maule\b",
    r"\bautogasco\b",
    r"\bgas\s?licuado\b",
    r"\bbal[oó]n\s?de\s?gas\b",
    # =========================================================================
    # DELIVERY, QUICK COMMERCE Y MARKETPLACES
    # =========================================================================
    r"\bpedidosya\b",
    r"\bpedidos\s?ya\b",
    r"\bpeya\b",
    r"\brappi\b",
    r"\buber\s?eats\b",
    r"\bubereats\b",
    r"\bcornershop\b",
    r"\bget\s?justo\b",
    r"\bgetjusto\b",
    r"\bfazil\b",
    r"\bjokr\b",
    r"\bdidi\s?food\b",
    r"\btottus\s?app\b",
    r"\bmercado\s?libre\b",
    r"\bmercadolibre\b",
    r"\bmeli\b",
    r"\bfalabella\.com\b",
    r"\bparis\.cl\b",
    r"\bripley\.com\b",
    r"\baliexpress\b",
    r"\bali\s?express\b",
    r"\btemu\b",
    r"\bshein\b",
    r"\bdafiti\b",
    r"\blinio\b",
    # =========================================================================
    # COMIDA RÁPIDA INTERNACIONAL
    # =========================================================================
    r"\bmc\s?donald'?s?\b",
    r"\bmcdonald'?s?\b",
    r"\bmac\s?donalds\b",
    r"\bburger\s?king\b",
    r"\bburguer\s?king\b",
    r"\bsubway\b",
    r"\bkfc\b",
    r"\bkentucky\s?fried\s?chicken\b",
    r"\bwendy'?s\b",
    r"\btaco\s?bell\b",
    r"\bpopeye'?s?\b",
    r"\bjohnny\s?rockets\b",
    r"\b100\s?montaditos\b",
    r"\bcien\s?montaditos\b",
    r"\bp\.?f\.?\s?chang'?s\b",
    r"\bchili'?s\b",
    r"\btgi\s?fridays?\b",
    r"\bapplebee'?s\b",
    r"\bruby\s?tuesday\b",
    r"\bhooters\b",
    r"\boutback\b",
    r"\bchina\s?wok\b",
    r"\bboost\s?juice\b",
    r"\bbarra\s?chalaca\b",
    # =========================================================================
    # COMIDA RÁPIDA CHILENA / FUENTES DE SODA / SÁNGUCHES
    # =========================================================================
    r"\bdoggis\b",
    r"\bdoggi'?s\b",
    r"\bjuan\s?maestro\b",
    r"\btommy\s?beans\b",
    r"\bmamut\b",
    r"\bgn\s?brands\b",
    r"\bdegasa\b",
    r"\bbarrio\s?chick'?en\b",
    r"\bbarrio\s?chicken\b",
    r"\bschopdog\b",
    r"\bschop\s?dog\b",
    r"\bdomin[oó]\b",  # ambiguo (Dominó vs Domino's)
    r"\blomit[oó]n\b",
    r"\bbar\s?nacional\b",
    r"\bfuente\s?alemana\b",
    r"\bfuente\s?chilena\b",
    r"\belkika\b",
    r"\bel\s?kika\b",
    r"\bcharly\s?dog\b",
    r"\bmr\.?\s?lucas\b",
    r"\bbloke\s?burger\b",
    r"\bamerican\s?burger\b",
    r"\bbex\s?burger\b",
    r"\bgrds\b",
    r"\bwing\s?it\b",
    r"\bpedro\s?,?\s?juan\s?(?:y|&)\s?diego\b",
    r"\bbuffet\s?express\b",
    r"\bwild\s?foods\b",
    r"\bwevo\b",
    r"\byouserv\b",
    r"\bdel\s?cultivo\b",
    r"\btomate\s?algo\b",
    r"\bachoclonados\b",
    r"\bemporio\s?zunino\b",
    r"\bempanadas?\s?zunino\b",
    r"\bzunino\b",
    r"\bberlin\s?d[oö]ner\b",
    r"\bkebab\b",
    r"\bbadra'?s\b",
    # =========================================================================
    # PIZZERÍAS
    # =========================================================================
    r"\bpapa\s?john'?s?\b",
    r"\bpapa\s?johns\b",
    r"\bdomino'?s\s?pizza\b",
    r"\bdominos\s?pizza\b",
    r"\bpizza\s?hut\b",
    r"\btelepizza\b",
    r"\blittle\s?caesars\b",
    r"\blittle\s?ceasars\b",
    r"\bpizza\s?pizza\b",
    r"\bmelt\s?pizza\b",
    r"\bmelt\b",  # ambiguo
    r"\bunder\s?pizza\b",
    r"\boh\s?my\s?pizza\b",
    r"\bagostina\b",
    r"\blovdo\b",
    r"\barlecchino\b",
    r"\bvittore\b",
    r"\bpizzer[ií]a\b",
    # =========================================================================
    # SUSHI Y COMIDA ASIÁTICA DE CADENA
    # =========================================================================
    r"\bniu\s?sushi\b",
    r"\bsushi\s?blues\b",
    r"\bsakura\s?express\b",
    r"\baqua\s?sushi\b",
    r"\basoko\s?sushi\b",
    r"\bbaku\s?sushi\b",
    r"\bbendito\s?sushi\b",
    r"\bboka\s?sushi\b",
    r"\budon\b",
    r"\bichiban\b",
    r"\bkintaro\b",
    r"\bramen\s?kintaro\b",
    r"\bosaka\b",
    r"\bsushi\b",  # ambiguo (genérico)
    # =========================================================================
    # CAFETERÍAS Y CAFÉS CON PIERNAS
    # =========================================================================
    r"\bstarbucks\b",
    r"\bdunkin(?:'?s)?(?:\s?donuts)?\b",
    r"\bjuan\s?valdez\b",
    r"\bcaf[eé]\s?hait[ií]\b",
    r"\bhait[ií]\b",  # ambiguo (país)
    r"\bcaf[eé]\s?caribe\b",
    r"\bcaf[eé]\s?y\s?t[eé]\s?italia\b",
    r"\bastoria\b",
    r"\bcaf[eé]\s?cory\b",
    r"\bel\s?caf[eé]\s?rosa\b",
    r"\bl'?espresso\b",
    r"\bblackdrop\b",
    r"\bblack\s?drop\b",
    r"\bbiancolatte\b",
    r"\baffogato\b",
    r"\bnespresso\b",
    r"\bsegafredo\b",
    r"\badagio\s?teas?\b",
    r"\bbig\s?boba\b",
    r"\bcafeter[ií]a\b",
    # =========================================================================
    # HELADERÍAS, PASTELERÍAS, PANADERÍAS, CHOCOLATERÍAS
    # =========================================================================
    r"\bemporio\s?la\s?rosa\b",
    r"\btavelli\b",
    r"\bcoppelia\b",
    r"\bcopelia\b",
    r"\bbravissimo\b",
    r"\bbrav[ií]ssimo\b",
    r"\bgrido\b",
    r"\byogen\s?fr[üu]z\b",
    r"\bhappy\s?gelato\b",
    r"\byogurtlife\b",
    r"\bh[aä]agen[\s\-]?dazs\b",
    r"\bbaskin\s?robbins\b",
    r"\bbarquiller[ií]a\b",
    r"\bcasta[nñ]o\b",
    r"\bsan\s?camilo\b",
    r"\bnucha\b",
    r"\bc'?est\s?si\s?bon\b",
    r"\bsesibon\b",
    r"\bvarsovienne\b",
    r"\bvolka\b",
    r"\bbrownie\s?republic\b",
    r"\bhappy\s?days\s?waffles\b",
    r"\bpiadina\s?leggera\b",
    r"\btempo\s?d'?italia\b",
    r"\bkrispy\s?kreme\b",
    r"\bcinnabon\b",
    r"\bpanader[ií]a\b",
    r"\bpasteler[ií]a\b",
    r"\bconfiter[ií]a\b",
    r"\bhelader[ií]a\b",
    r"\brotiser[ií]a\b",
    # =========================================================================
    # BOTILLERÍAS, VINOS Y LICORES
    # =========================================================================
    r"\bl[ií]quidos\.cl\b",
    r"\bl[ií]quidos\b",
    r"\bel\s?mundo\s?del\s?vino\b",
    r"\bla\s?vinoteca\b",
    r"\bbbvinos\b",
    r"\bbb\s?vinos\b",
    r"\bcomercial\s?baco\b",
    r"\blicores\s?san\s?joaqu[ií]n\b",
    r"\bmitjans\b",
    r"\bbotiller[ií]a\b",
    r"\bvinoteca\b",
    # =========================================================================
    # FARMACIAS
    # =========================================================================
    r"\bcruz\s?verde\b",
    r"\bcruzverde\b",
    r"\bsocofar\b",
    r"\bfemsa\s?salud\b",
    r"\bsalcobrand\b",
    r"\bsalco\s?brand\b",
    r"\bempresas\s?sb\b",
    r"\bfarmacias?\s?ahumada\b",
    r"\bahumada\b",  # ambiguo (calle Ahumada)
    r"\bfasa\b",
    r"\bdr\.?\s?simi\b",
    r"\bdoctor\s?simi\b",
    r"\bfarmacias?\s?similares\b",
    r"\bfarmacias?\s?knop\b",
    r"\bknop\b",
    r"\bredfarma\b",
    r"\bred\s?farma\b",
    r"\becofarmacias?\b",
    r"\bnovasalud\b",
    r"\bnova\s?salud\b",
    r"\bfarmacias?\s?gal[eé]nica\b",
    r"\bla\s?botika\b",
    r"\bfarmacias?\s?bel[eé]n\b",
    r"\bfarmacias?\s?manr[ií]quez\b",
    r"\bdr\.?\s?ahorro\b",
    r"\bdoctor\s?ahorro\b",
    r"\bmakelawen\b",
    r"\bfarmacia\s?mapuche\b",
    r"\bfarmacias?\s?karmel\b",
    r"\bfarmal[ií]der\b",
    r"\bsalco\b",
    r"\bfarmacia\s?brand\b",
    r"\bfarmacia\s?popular\b",
    r"\bfarmacia\s?comunal\b",
    r"\bfarmacia\s?municipal\b",
    r"\bfarmacia\s?comunitaria\b",
    r"\bachifarp\b",
    r"\bvitabotica\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    r"\bdroguer[ií]a\b",
    r"\bcenabast\b",
    # =========================================================================
    # PERFUMERÍA Y BELLEZA
    # =========================================================================
    r"\bpreunic\b",
    r"\bpre\s?unic\b",
    r"\bmaicao\b",
    r"\bdbs\b",
    r"\bdbs\s?beauty\b",
    r"\bprismology\b",
    r"\bkiko\s?milano\b",
    r"\bsally\s?beauty\b",
    r"\bpichara\b",
    r"\bbeauty\s?plus\b",
    r"\bmycocos\b",
    r"\bthe\s?body\s?shop\b",
    r"\bl'?occitane\b",
    r"\bnatura\b",
    r"\bavon\b",
    r"\bsephora\b",
    r"\bparfois\b",
    r"\bperfumer[ií]a\b",
    # =========================================================================
    # ÓPTICAS Y AUDIOLOGÍA
    # =========================================================================
    r"\brotter\s?(?:y|&)\s?krauss\b",
    r"\brotter\b",
    r"\bryk\b",
    r"\b[oó]pticas?\s?gmo\b",
    r"\bgmo\b",
    r"\becon[oó]pticas?\b",
    r"\bsun\s?planet\b",
    r"\bplace\s?vend[oô]me\b",
    r"\bschilling\b",
    r"\bsunglass\s?hut\b",
    r"\bben\s?(?:and|&)\s?frank\b",
    r"\bmas\s?visi[oó]n\b",
    r"\b\+visi[oó]n\b",
    r"\bgaes\b",
    r"\bamplifon\b",
    r"\b[oó]ptica\s?alemana\b",
    r"\bhammersley\b",
    r"\b[oó]pticas?\s?basic\b",
    r"\bmac[\s\-]?hale\b",
    r"\bfederico\s?henzi\b",
    r"\bitaloptica\b",
    r"\bzeiss\s?vision\b",
    r"\b[oó]ptica\b",
    # =========================================================================
    # REDES DE SALUD, CLÍNICAS Y LABORATORIOS
    # =========================================================================
    r"\bredsalud\b",
    r"\bred\s?salud\b",
    r"\bmegasalud\b",
    r"\bmega\s?salud\b",
    r"\bbanm[eé]dica\b",
    r"\bbupa\b",
    r"\bintegram[eé]dica\b",
    r"\bvidaintegra\b",
    r"\bvida\s?integra\b",
    r"\bandes\s?salud\b",
    r"\buc\s?christus\b",
    r"\bachs\b",
    r"\bmutual\s?de\s?seguridad\b",
    r"\bist\b",
    r"\bhospital\s?del\s?trabajador\b",
    r"\bcl[ií]nica\s?alemana\b",
    r"\bcl[ií]nica\s?las\s?condes\b",
    r"\bclc\b",
    r"\bcl[ií]nica\s?santa\s?mar[ií]a\b",
    r"\bcl[ií]nica\s?d[aá]vila\b",
    r"\bcl[ií]nica\s?indisa\b",
    r"\bindisa\b",
    r"\bcl[ií]nica\s?universidad\s?de\s?los\s?andes\b",
    r"\bcl[ií]nica\s?tabancura\b",
    r"\bavansalud\b",
    r"\bcl[ií]nica\s?bicentenario\b",
    r"\bcl[ií]nica\s?meds\b",
    r"\bmeds\b",
    r"\bcl[ií]nica\s?cordillera\b",
    r"\bcl[ií]nica\s?colonial\b",
    r"\bhospital\s?del\s?profesor\b",
    r"\blos\s?coihues\b",
    r"\bfalp\b",
    r"\barturo\s?l[oó]pez\s?p[eé]rez\b",
    r"\biram\b",
    r"\bhcuch\b",
    r"\bhospital\s?cl[ií]nico\b",
    r"\bcl[ií]nica\s?fleming\b",
    r"\bcl[ií]nica\s?tarapac[aá]\b",
    r"\bcl[ií]nica\s?la\s?portada\b",
    r"\bcl[ií]nica\s?el\s?loa\b",
    r"\bcl[ií]nica\s?atacama\b",
    r"\bcl[ií]nica\s?elqui\b",
    r"\bciudad\s?del\s?mar\b",
    r"\bcl[ií]nica\s?re[nñ]aca\b",
    r"\bcl[ií]nica\s?los\s?carrera\b",
    r"\bcl[ií]nica\s?r[ií]o\s?blanco\b",
    r"\bcl[ií]nica\s?maitenes\b",
    r"\bfusat\b",
    r"\bcl[ií]nica\s?del\s?maule\b",
    r"\bcl[ií]nica\s?lircay\b",
    r"\bcl[ií]nica\s?b[ií]o\s?b[ií]o\b",
    r"\bsanatorio\s?alem[aá]n\b",
    r"\bhospital\s?cl[ií]nico\s?del\s?sur\b",
    r"\bcl[ií]nica\s?mayor\b",
    r"\bcl[ií]nica\s?puerto\s?varas\b",
    r"\bcl[ií]nica\s?magallanes\b",
    r"\bcl[ií]nica\s?puerto\s?montt\b",
    r"\bpasteur\b",
    r"\bpuerta\s?del\s?sol\b",
    r"\bfola\b",
    r"\bbionet\b",
    r"\bredlab\b",
    r"\blaboratorio\s?blanco\b",
    r"\bbupa\s?lab\b",
    r"\belsa\b",
    r"\bbiosoluciones\b",
    r"\blivio\s?barnafi\b",
    r"\bhelp\b",  # ambiguo (Help Rescate)
    r"\bhome\s?medical\b",
    r"\bcl[ií]nica\b",
    r"\bsanatorio\b",
    r"\blaboratorio\b",
    r"\bcentro\s?m[eé]dico\b",
    r"\bcentro\s?dental\b",
    # =========================================================================
    # ISAPRES, SEGUROS DE SALUD Y RED PÚBLICA (siglas oficiales MINSAL/DEIS)
    # =========================================================================
    r"\bfonasa\b",
    r"\bisapre\b",
    r"\bcolmena\b",
    r"\bconsalud\b",
    r"\bcruz\s?blanca\b",
    r"\bcruzblanca\b",
    r"\bnueva\s?masvida\b",
    r"\bmasvida\b",
    r"\bm[aá]s\s?vida\b",
    r"\bvida\s?tres\b",
    r"\bvida\s?3\b",
    r"\bisapre\s?esencial\b",
    r"\bisalud\b",
    r"\bcruz\s?del\s?norte\b",
    r"\bing\s?salud\b",
    r"\bnorm[eé]dica\b",
    r"\bpromepart\b",
    r"\bferrosalud\b",
    r"\bsuperintendencia\s?de\s?salud\b",
    r"\bminsal\b",
    r"\bisp\b",
    r"\bcesfam\b",
    r"\bcecosf\b",
    r"\bcecof\b",
    r"\bcosam\b",
    r"\bsapu\b",
    r"\bsar\b",  # ambiguo (SAG/SAR)
    r"\bsur\b",  # ambiguo (Servicio de Urgencia Rural vs "sur")
    r"\bsamu\b",
    r"\bcrs\b",
    r"\bcdt\b",
    r"\bccr\b",
    r"\bconsultorio\b",
    r"\bposta\b",
    r"\bposta\s?de\s?salud\s?rural\b",
    r"\bestaci[oó]n\s?m[eé]dico\s?rural\b",
    r"\bcentro\s?de\s?salud\s?familiar\b",
    r"\bcentro\s?de\s?salud\b",
    r"\bhospital\b",
    r"\bservicio\s?de\s?salud\b",
    r"\bseremi\b",
    r"\bm[oó]dulo\s?odontol[oó]gico\b",
    # =========================================================================
    # GIMNASIOS Y CLUBES DEPORTIVOS
    # =========================================================================
    r"\bpacific\s?fitness\b",
    r"\bsmart\s?fit\b",
    r"\bsmartfit\b",
    r"\bsportlife\b",
    r"\bsport\s?life\b",
    r"\benergy\s?club\b",
    r"\benergy\s?fitness\b",
    r"\bspeed\s?works\b",
    r"\byoutopia\b",
    r"\bko\s?urban\b",
    r"\bbalthus\b",
    r"\belite\s?fitness\b",
    r"\bmotion\s?center\b",
    r"\bo2\s?fit\b",
    r"\bo2fit\b",
    r"\bgimnasios?\s?chile\b",
    r"\bclub\s?recrear\b",
    r"\bcardiopilates\b",
    r"\bcrossfit\b",
    r"\bcross\s?fit\b",
    r"\bgimnasio\b",
    r"\bnatatorio\b",
    # =========================================================================
    # DENTAL, VETERINARIA Y MASCOTAS
    # =========================================================================
    r"\buno\s?salud\s?dental\b",
    r"\buno\s?salud\b",
    r"\bsonrident\b",
    r"\blatamvet\b",
    r"\blatam\s?vet\b",
    r"\bdr\.?\s?pet\b",
    r"\bpet\s?happy\b",
    r"\bsuperzoo\b",
    r"\bsuper\s?zoo\b",
    r"\bpetco\b",
    r"\bpet\s?city\b",
    r"\bmaskota\b",
    r"\bmaskota\s?center\b",
    r"\brazas\s?pet\b",
    r"\bbe\s?foods\b",
    r"\bpetvet\b",
    r"\bpet\s?home\b",
    r"\bbpets\b",
    r"\bamigales\b",
    r"\bclub\s?de\s?perros\s?y\s?gatos\b",
    r"\bmundo\s?petshop\b",
    r"\bcopeval\b",
    r"\bcoagra\b",
    r"\bveterinaria\b",
    # =========================================================================
    # GRANDES TIENDAS / MULTITIENDAS
    # =========================================================================
    r"\bfalabella\b",
    r"\bsaci\s?falabella\b",
    r"\bripley\b",
    r"\beccsa\b",
    r"\bpar[ií]s\b",  # ambiguo (ciudad)
    r"\balmacenes\s?par[ií]s\b",
    r"\bparis\s?express\b",
    r"\bla\s?polar\b",
    r"\blapolar\b",
    r"\babcdin\b",
    r"\babc\s?din\b",
    r"\bab[cd]\s?retail\b",
    r"\bad\s?retail\b",
    r"\bdin\b",  # ambiguo
    r"\bhites\b",
    r"\btricot\b",
    r"\bcorona\b",  # ambiguo
    r"\bjohnson'?s?\b",
    r"\bdijon\b",
    r"\bfashion'?s?\s?park\b",
    r"\bfashion\s?park\b",
    r"\bcalzados?\s?beba\b",
    # =========================================================================
    # MEJORAMIENTO DEL HOGAR, FERRETERÍA Y CONSTRUCCIÓN
    # =========================================================================
    r"\bsodimac\b",
    r"\bhomecenter\b",
    r"\bhome\s?center\b",
    r"\bsodimac\s?constructor\b",
    r"\beasy\b",
    r"\bconstrumart\b",
    r"\bimperial\b",
    r"\bchilemat\b",
    r"\bmts\b",
    r"\bferrexperto\b",
    r"\bel\s?martillo\b",
    r"\bmadesur\b",
    r"\bferreter[ií]a\s?prat\b",
    r"\bferreter[ií]a\s?okey\b",
    r"\bcasa\s?franco\b",
    r"\bcasa\s?garc[ií]a\b",
    r"\bsocodima\b",
    r"\bebema\b",
    r"\bprodalam\b",
    r"\bweitzler\b",
    r"\bferreter[ií]a\b",
    r"\bcorral[oó]n\b",
    r"\bbarraca\b",
    # =========================================================================
    # MUEBLES, DECORACIÓN Y COLCHONES
    # =========================================================================
    r"\bhomy\b",
    r"\bikea\b",
    r"\bcasaideas\b",
    r"\bcasa\s?(?:e|&|y)\s?ideas\b",
    r"\brosen\b",
    r"\bcic\b",
    r"\bcelta\b",
    r"\bflex\b",
    r"\bproterra\b",
    r"\bmica\b",
    r"\bcasa\s?f[oó]a\b",
    # =========================================================================
    # TECNOLOGÍA, ELECTRO Y VIDEOJUEGOS
    # =========================================================================
    r"\bpc\s?factory\b",
    r"\bpcfactory\b",
    r"\bcasa\s?royal\b",
    r"\bcasaroyal\b",
    r"\bwinpy\b",
    r"\bwei\b",
    r"\bsp\s?digital\b",
    r"\bspdigital\b",
    r"\bzmart\b",
    r"\bmicroplay\b",
    r"\bmicro\s?play\b",
    r"\bweplay\b",
    r"\btodojuegos\b",
    r"\bgeekz\b",
    r"\bmegaplay\b",
    r"\bmac\s?online\b",
    r"\bmaconline\b",
    r"\bishop\b",
    r"\bsamsung\s?store\b",
    # =========================================================================
    # MODA INTERNACIONAL
    # =========================================================================
    r"\bzara\b",
    r"\bzara\s?home\b",
    r"\bmassimo\s?dutti\b",
    r"\bbershka\b",
    r"\bpull\s?(?:and|&)?\s?bear\b",
    r"\bstradivarius\b",
    r"\boysho\b",
    r"\bh&m\b",
    r"\bh\s?(?:y|and)\s?m\b",
    r"\bgap\b",
    r"\bbanana\s?republic\b",
    r"\bold\s?navy\b",
    r"\besprit\b",
    r"\bdiesel\b",
    r"\bbenetton\b",
    r"\bcalzedonia\b",
    r"\bforever\s?21\b",
    r"\broxy\b",
    r"\bquiksilver\b",
    r"\bdc\s?shoes\b",
    r"\bthe\s?north\s?face\b",
    r"\bkipling\b",
    r"\bbrooks\s?brothers\b",
    r"\bugg\b",
    r"\bteva\b",
    r"\bralph\s?lauren\b",
    r"\btommy\s?hilfiger\b",
    r"\bcalvin\s?klein\b",
    r"\bguess\b",
    r"\blacoste\b",
    r"\bmango\b",
    r"\bcrocs\b",
    r"\baldo\b",
    r"\bclarks\b",
    r"\bgeox\b",
    r"\btimberland\b",
    r"\bsteve\s?madden\b",
    r"\bflorsheim\b",
    r"\bnine\s?west\b",
    r"\bbata\b",
    r"\babercrombie\b",
    r"\bcarter'?s\b",
    r"\bvans\b",
    # =========================================================================
    # MODA Y CALZADO CHILENO (Forus, Komax y otros)
    # =========================================================================
    r"\bhush\s?puppies\b",
    r"\brockford\b",
    r"\bdhouse\b",
    r"\bd[\s\-]?house\b",
    r"\bshoe\s?express\b",
    r"\bcalpany\b",
    r"\btns\b",
    r"\bwe\s?love\s?shoes\b",
    r"\bazaleia\b",
    r"\b7\s?veinte\b",
    r"\bb[\s\-]?soul\b",
    r"\bbillabong\b",
    r"\bcat\s?footwear\b",
    r"\bsuprice\b",
    r"\bkliper\b",
    r"\bgacel\b",
    r"\bguante\b",
    r"\bkayser\b",
    r"\bcaffarena\b",
    r"\bpalmers\b",
    r"\bintime\b",
    r"\bcolloky\b",
    r"\bopaline\b",
    r"\bbaby\s?infanti\b",
    r"\binfanti\b",
    r"\bmundo\s?petit\b",
    r"\bpill[ií]n\b",
    r"\b4\s?kids\b",
    r"\bsybilla\b",
    r"\bbasement\b",
    r"\buniversity\s?club\b",
    r"\bnewport\b",
    r"\bamericanino\b",
    r"\bbearcliff\b",
    r"\bmountain\s?gear\b",
    r"\byamp\b",
    r"\bdoo\s?australia\b",
    r"\bellus\b",
    r"\bbarbados\b",
    r"\brobert\s?lewis\b",
    r"\bamano\b",
    # =========================================================================
    # DEPORTE Y OUTDOOR
    # =========================================================================
    r"\bnike\b",
    r"\badidas\b",
    r"\bpuma\b",
    r"\bunder\s?armour\b",
    r"\bcolumbia\b",
    r"\bmerrell\b",
    r"\bpatagonia\b",  # ambiguo (región)
    r"\beverlast\b",
    r"\bdecathlon\b",
    r"\bsparta\b",
    r"\bmarathon\b",
    r"\bandesgear\b",
    r"\bandes\s?gear\b",
    r"\bdoite\b",
    r"\blippi\b",
    r"\btatoo\b",
    r"\bla\s?cumbre\b",
    r"\bnorthland\b",
    r"\b100%?\s?f[uú]tbol\b",
    r"\bcien\s?por\s?ciento\s?futbol\b",
    # =========================================================================
    # VARIEDADES, LIBRERÍAS, JUGUETERÍAS Y PAPELERÍA
    # =========================================================================
    r"\bminiso\b",
    r"\bmumuso\b",
    r"\bilahui\b",
    r"\bdimeiggs\b",
    r"\bdimerc\b",
    r"\bl[aá]piz\s?l[oó]pez\b",
    r"\blibrer[ií]a\s?nacional\b",
    r"\bantartica\b",
    r"\bant[aá]rtica\b",
    r"\bferia\s?chilena\s?del\s?libro\b",
    r"\bcontrapunto\b",
    r"\bbooks\s?(?:and|&)\s?bits\b",
    r"\btruman\b",
    r"\bjerplaz\b",
    r"\bmundilibros\b",
    r"\bqu[eé]\s?leo\b",
    r"\btoyscenter\b",
    r"\btoys\s?center\b",
    r"\blittle\s?toys\b",
    r"\blibrer[ií]a\b",
    r"\bpapeler[ií]a\b",
    r"\bjugueter[ií]a\b",
    # =========================================================================
    # JOYERÍA
    # =========================================================================
    r"\bpandora\b",
    r"\baurus\b",
    r"\bjoyer[ií]a\b",
    r"\brelojer[ií]a\b",
    # =========================================================================
    # AUTOMOTRIZ, REPUESTOS Y NEUMÁTICOS
    # =========================================================================
    r"\bautoplanet\b",
    r"\bauto\s?planet\b",
    r"\bautostock\b",
    r"\brosselot\b",
    r"\bderco\b",
    r"\bderco\s?center\b",
    r"\bsalfa\b",
    r"\bsalfasur\b",
    r"\bsalfa\s?rent\b",
    r"\bkaufmann\b",
    r"\bbruno\s?fritsch\b",
    r"\bguillermo\s?morales\b",
    r"\bamericar\b",
    r"\bcoseche\b",
    r"\bcerflex\b",
    r"\bvulco\b",
    r"\bfirestone\b",
    r"\bbridgestone\b",
    r"\bneumax\b",
    r"\bneum[aá]ticosk\b",
    r"\bchileneum[aá]ticos\b",
    r"\bneumachile\b",
    r"\bautomotora\b",
    r"\bvulcanizaci[oó]n\b",
    r"\blubricentro\b",
    # =========================================================================
    # BANCOS
    # =========================================================================
    r"\bbanco\s?de\s?chile\b",
    r"\bbancochile\b",
    r"\bedwards\b",
    r"\bbancoestado\b",
    r"\bbanco\s?estado\b",
    r"\bbanco\s?del\s?estado\b",
    r"\bbech\b",
    r"\bserviestado\b",
    r"\bbci\b",
    r"\bbanco\s?de\s?cr[eé]dito\s?e\s?inversiones\b",
    r"\bsantander\b",
    r"\bbanefe\b",
    r"\bscotiabank\b",
    r"\bscotia\b",
    r"\bita[uú]\b",
    r"\bcorpbanca\b",
    r"\bcorp\s?banca\b",
    r"\bbice\b",
    r"\bbicecorp\b",
    r"\bbanco\s?internacional\b",
    r"\bbanco\s?consorcio\b",
    r"\bbanco\s?falabella\b",
    r"\bbanco\s?ripley\b",
    r"\bbtg\s?pactual\b",
    r"\bhsbc\b",
    r"\btanner\b",
    r"\btenpo\s?bank\b",
    r"\bjp\s?morgan\b",
    r"\bjpmorgan\b",
    r"\bchina\s?construction\s?bank\b",
    r"\bbank\s?of\s?china\b",
    r"\bbanco\s?security\b",
    r"\bbbva\b",
    r"\bbanco\s?del\s?desarrollo\b",
    r"\bbandesarrollo\b",
    r"\bbanco\s?penta\b",
    r"\bbanco\s?paris\b",
    r"\bbanco\s?monex\b",
    r"\bbankboston\b",
    r"\bcitibank\b",
    r"\bdeutsche\s?bank\b",
    r"\bbanco\s?do\s?brasil\b",
    r"\bbanco\s?central\b",
    r"\bcmf\b",
    # =========================================================================
    # COOPERATIVAS Y CAJAS DE COMPENSACIÓN
    # =========================================================================
    r"\bcoopeuch\b",
    r"\boriencoop\b",
    r"\bcapual\b",
    r"\bdetacoop\b",
    r"\bahorrocoop\b",
    r"\bcoocretal\b",
    r"\bcoonfia\b",
    r"\bdale\b",  # ambiguo
    r"\bcaja\s?los\s?andes\b",
    r"\bccaf\b",
    r"\blos\s?h[eé]roes\b",
    r"\bla\s?araucana\b",
    r"\bcaja\s?18\s?de\s?septiembre\b",
    r"\bgabriela\s?mistral\b",
    r"\btapp\b",
    r"\bcaja\s?de\s?compensaci[oó]n\b",
    # =========================================================================
    # FINTECH, BILLETERAS Y PREPAGO
    # =========================================================================
    r"\btenpo\b",
    r"\bmercado\s?pago\b",
    r"\bmercadopago\b",
    r"\bmach\b",
    r"\bmachbank\b",
    r"\bchek\b",
    r"\bfpay\b",
    r"\bsuperdigital\b",
    r"\bglobal66\b",
    r"\bglobal\s?66\b",
    r"\bprex\b",
    r"\bcopec\s?pay\b",
    r"\bfintual\b",
    r"\bbuda\b",
    r"\bcryptomarket\b",
    r"\bcryptomkt\b",
    r"\bxepelin\b",
    r"\bkoywe\b",
    r"\bfintoc\b",
    r"\bhaulmer\b",
    r"\btuu\b",
    r"\bkushki\b",
    r"\bkhipu\b",
    r"\bpomelo\b",
    r"\bdest[aá]came\b",
    r"\bgalgo\b",
    r"\bchipax\b",
    r"\bcomunidad\s?feliz\b",
    r"\bencuadrado\b",
    r"\bconomy\b",
    r"\bneat\b",
    r"\bvita\s?wallet\b",
    # =========================================================================
    # ADQUIRENCIA, REDES Y MEDIOS DE PAGO
    # =========================================================================
    r"\btransbank\b",
    r"\btbk\b",
    r"\bredcompra\b",
    r"\bred\s?compra\b",
    r"\bwebpay\b",
    r"\bweb\s?pay\b",
    r"\bonepay\b",
    r"\bgetnet\b",
    r"\bklap\b",
    r"\bmulticaja\b",
    r"\bpincenter\b",
    r"\biswitch\b",
    r"\bbci\s?pagos\b",
    r"\bcompraqu[ií]\b",
    r"\bbanchile\s?pagos\b",
    r"\bmercado\s?pago\s?point\b",
    r"\bredelcom\b",
    r"\bsumup\b",
    r"\bbaaskit\b",
    r"\bred\s?global\b",
    r"\bpagos\s?y\s?servicios\b",
    r"\bredbanc\b",
    r"\bcombanc\b",
    r"\bnexus\b",
    r"\bservipag\b",
    r"\bcaja\s?vecina\b",
    r"\bcajavecina\b",
    r"\bsencillito\b",
    r"\bunired\b",
    r"\bdcv\b",
    r"\baft\b",
    r"\bpluxee\b",
    r"\bsodexo\b",
    r"\bedenred\b",
    r"\bamipass\b",
    # =========================================================================
    # CASAS COMERCIALES Y TARJETAS DE RETAIL
    # =========================================================================
    r"\bcmr\b",
    r"\bcmr\s?falabella\b",
    r"\btarjeta\s?cencosud\b",
    r"\btarjeta\s?m[aá]s\b",
    r"\bcat\s?administradora\b",
    r"\btarjeta\s?ripley\b",
    r"\bcar\s?s\.?a\.?\b",
    r"\bl[ií]der\s?bci\b",
    r"\bpresto\b",
    r"\btricard\b",
    r"\bsantander\s?consumer\b",
    r"\bautofin\b",
    # =========================================================================
    # SEGUROS Y AFP
    # =========================================================================
    r"\bzurich\b",
    r"\bmapfre\b",
    r"\bhdi\b",
    r"\bbci\s?seguros\b",
    r"\bconsorcio\b",
    r"\bsura\b",
    r"\bsuramericana\b",
    r"\bchubb\b",
    r"\bmetlife\b",
    r"\bconfuturo\b",
    r"\bpenta\s?vida\b",
    r"\bprincipal\b",
    r"\bbice\s?vida\b",
    r"\beuroamerica\b",
    r"\bvida\s?c[aá]mara\b",
    r"\balemana\s?seguros\b",
    r"\bcardif\b",
    r"\bassurant\b",
    r"\bsouthbridge\b",
    r"\breale\b",
    r"\bliberty\b",
    r"\brenta\s?nacional\b",
    r"\bcoface\b",
    r"\bsolunion\b",
    r"\borsan\b",
    r"\bstarr\b",
    r"\bcn\s?life\b",
    r"\bmutual\s?de\s?seguros\b",
    r"\bmutualidad\s?del\s?ej[eé]rcito\b",
    r"\bafp\b",
    r"\bcapital\b",  # ambiguo
    r"\bcuprum\b",
    r"\bhabitat\b",
    r"\bh[aá]bitat\b",
    r"\bplanvital\b",
    r"\bplan\s?vital\b",
    r"\bprovida\b",
    r"\bafp\s?modelo\b",
    r"\bafp\s?uno\b",
    r"\bbansander\b",
    r"\bmagister\b",
    r"\bsanta\s?mar[ií]a\b",  # ambiguo
    # =========================================================================
    # TELECOMUNICACIONES
    # =========================================================================
    r"\bentel\b",
    r"\bmovistar\b",
    r"\btelef[oó]nica\b",
    r"\bctc\b",
    r"\bclaro\b",  # ambiguo ("claro" adverbio)
    r"\bclarovtr\b",
    r"\bclaro\s?vtr\b",
    r"\bvtr\b",
    r"\bwom\b",
    r"\bnextel\b",
    r"\bsmartcom\b",
    r"\bchilesat\b",
    r"\btelmex\b",
    r"\bbellsouth\b",
    r"\bstartel\b",
    r"\bgtd\b",
    r"\bgtd\s?manquehue\b",
    r"\btelsur\b",
    r"\btelef[oó]nica\s?del\s?sur\b",
    r"\bmundo\s?pac[ií]fico\b",
    r"\bmundo\b",  # ambiguo
    r"\bvirgin\s?mobile\b",
    r"\bnetline\b",
    r"\btelestar\b",
    r"\bsuma\s?m[oó]vil\b",
    r"\bsimple\b",  # ambiguo
    r"\bfalabella\s?m[oó]vil\b",
    r"\bdirectv\b",
    r"\btuves\b",
    r"\bzapping\b",
    r"\btv\s?red\b",
    r"\bquintavisi[oó]n\b",
    r"\bmetr[oó]polis\s?intercom\b",
    r"\bcablexpress\b",
    r"\bstarlink\b",
    r"\bsubtel\b",
    # =========================================================================
    # ELECTRICIDAD (distribuidoras y cooperativas)
    # =========================================================================
    r"\benel\b",
    r"\benel\s?distribuci[oó]n\b",
    r"\bchilectra\b",
    r"\benel\s?colina\b",
    r"\bcge\b",
    r"\bcompa[nñ][ií]a\s?general\s?de\s?electricidad\b",
    r"\bconafe\b",
    r"\bemel\b",
    r"\bemelat\b",
    r"\bemelectric\b",
    r"\bemetal\b",
    r"\bemelari\b",
    r"\beliqsa\b",
    r"\belecda\b",
    r"\br[ií]o\s?maipo\b",
    r"\bchilquinta\b",
    r"\bel[eé]ctrica\s?del\s?litoral\b",
    r"\bedecsa\b",
    r"\bemelca\b",
    r"\beepa\b",
    r"\bluz\s?andes\b",
    r"\bluzandes\b",
    r"\bluzparral\b",
    r"\bluzlinares\b",
    r"\bmataquito\b",
    r"\bcodiner\b",
    r"\bsaesa\b",
    r"\bfrontel\b",
    r"\bluz\s?osorno\b",
    r"\bedelays[eé]n\b",
    r"\bedelmag\b",
    r"\bcoelcha\b",
    r"\bcoopelan\b",
    r"\bcopelec\b",
    r"\bsocoepa\b",
    r"\bcrell\b",
    r"\bcooprel\b",
    r"\bcoopersol\b",
    r"\bcooperativa\s?el[eé]ctrica\b",
    # =========================================================================
    # SANITARIAS (agua potable y alcantarillado)
    # =========================================================================
    r"\baguas\s?andinas\b",
    r"\bemos\b",
    r"\baguas\s?cordillera\b",
    r"\baguas\s?manquehue\b",
    r"\bsmapa\b",
    r"\besval\b",
    r"\baguas\s?del\s?valle\b",
    r"\baguas\s?del\s?altiplano\b",
    r"\baguas\s?antofagasta\b",
    r"\bnueva\s?atacama\b",
    r"\baguas\s?cha[nñ]ar\b",
    r"\bessbio\b",
    r"\bnuevosur\b",
    r"\bnuevo\s?sur\b",
    r"\baguas\s?araucan[ií]a\b",
    r"\bsuralis\b",
    r"\bessal\b",
    r"\baguas\s?d[eé]cima\b",
    r"\baguas\s?patagonia\b",
    r"\baguas\s?magallanes\b",
    r"\baguas\s?san\s?pedro\b",
    r"\baguas\s?san\s?isidro\b",
    r"\bsacyr\s?agua\b",
    r"\bmelipilla\s?norte\b",
    r"\blarapinta\b",
    r"\bcoopagua\b",
    r"\bsasipa\b",
    r"\btratacal\b",
    r"\bsiss\b",
    # =========================================================================
    # CORREO Y LOGÍSTICA
    # =========================================================================
    r"\bcorreos\s?de\s?chile\b",
    r"\bcorreoschile\b",
    r"\bchilexpress\b",
    r"\bstarken\b",
    r"\bblue\s?express\b",
    r"\bbluexpress\b",
    r"\bbluex\b",
    r"\bshipit\b",
    r"\benv[ií]ame\b",
    r"\b99minutos\b",
    r"\bivoy\b",
    r"\bchile\s?post\b",
    r"\bfedex\b",
    r"\bdhl\b",
    r"\bups\b",
    # =========================================================================
    # HOTELERÍA
    # =========================================================================
    r"\bmarriott\b",
    r"\bjw\s?marriott\b",
    r"\bcourtyard\b",
    r"\bsheraton\b",
    r"\bfour\s?points\b",
    r"\bw\s?santiago\b",
    r"\bhyatt\b",
    r"\bgrand\s?hyatt\b",
    r"\bhyatt\s?centric\b",
    r"\bhilton\b",
    r"\bhilton\s?garden\s?inn\b",
    r"\bdoubletree\b",
    r"\bhampton\s?(?:by\s?hilton|inn)\b",
    r"\bintercontinental\b",
    r"\bcrowne\s?plaza\b",
    r"\bholiday\s?inn(?:\s?express)?\b",
    r"\bnh\s?(?:hotel|collection)\b",
    r"\bibis\b",
    r"\bnovotel\b",
    r"\bmercure\b",
    r"\bpullman\s?hotel\b",
    r"\bsofitel\b",
    r"\bmeli[aá]\b",
    r"\bradisson\b",
    r"\bpark\s?inn\b",
    r"\bbest\s?western\b",
    r"\bwyndham\b",
    r"\bramada\b",
    r"\bfour\s?seasons\b",
    r"\bthe\s?ritz[\s\-]?carlton\b",
    r"\bmandarin\s?oriental\b",
    r"\bsingular\b",
    r"\bdiego\s?de\s?almagro\b",
    r"\bpanamericana\s?hotel\b",
    r"\bterrado\b",
    r"\bnoi\s?hotel\b",
    r"\bcumbres\b",
    r"\batton\b",
    r"\bexplora\b",
    r"\bawasi\b",
    r"\btierra\s?hotels?\b",
    r"\benjoy\s?hotel\b",
    r"\bdreams\s?hotel\b",
    r"\bgeohotel\b",
    r"\bhotel\s?presidente\b",
    r"\bairbnb\b",
    r"\bbooking\.com\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\bhoster[ií]a\b",
    r"\bcaba[nñ]as\b",
    r"\bapart\s?hotel\b",
    r"\bmotel\b",
    # =========================================================================
    # CASINOS, CINES Y ENTRETENCIÓN
    # =========================================================================
    r"\benjoy\b",
    r"\bdreams\b",
    r"\bmundo\s?dreams\b",
    r"\bmonticello\b",
    r"\bsun\s?monticello\b",
    r"\bmarina\s?del\s?sol\b",
    r"\bcasino\s?de\s?vi[nñ]a\b",
    r"\blatin\s?gaming\b",
    r"\bcasino\s?antay\b",
    r"\bcasino\s?ovalle\b",
    r"\bcasino\b",
    r"\bbingo\b",
    r"\bcinemark\b",
    r"\bcineplanet\b",
    r"\bcine\s?hoyts\b",
    r"\bcinehoyts\b",
    r"\bhoyts\b",
    r"\bcinepolis\b",
    r"\bcin[eé]polis\b",
    r"\bcine\s?star\b",
    r"\bmuvix\b",
    r"\bmovieland\b",
    r"\bfantasilandia\b",
    r"\bhappyland\b",
    r"\bhappy\s?land\b",
    r"\bmundo\s?m[aá]gico\b",
    r"\bkidzania\b",
    r"\bchuck\s?e\s?cheese\b",
    r"\bsacoa\b",
    r"\bmovistar\s?arena\b",
    r"\bteatro\s?caupolic[aá]n\b",
    # =========================================================================
    # TRANSPORTE, PEAJES Y MOVILIDAD
    # =========================================================================
    r"\bturbus\b",
    r"\btur\s?bus\b",
    r"\bpullman\s?bus\b",
    r"\bcondor\s?bus\b",
    r"\bc[oó]ndor\s?bus\b",
    r"\bcruz\s?del\s?sur\b",
    r"\bjac\b",
    r"\beme\s?bus\b",
    r"\bnilahue\b",
    r"\bbuses\s?fierro\b",
    r"\bqueilen\s?bus\b",
    r"\bbus\s?sur\b",
    r"\bandesmar\b",
    r"\bterminal\s?de\s?buses\b",
    r"\bmetro\s?de\s?santiago\b",
    r"\bred\s?movilidad\b",
    r"\btransantiago\b",
    r"\bbiotr[eé]n\b",
    r"\bmerval\b",
    r"\befe\b",
    r"\btrenes\b",
    r"\btarjeta\s?bip\b",
    r"\bbip!\b",
    r"\btag\b",  # ambiguo
    r"\bautopista\s?central\b",
    r"\bcostanera\s?norte\b",
    r"\bvespucio\s?norte\b",
    r"\bvespucio\s?sur\b",
    r"\bam[eé]rico\s?vespucio\b",
    r"\bruta\s?del\s?maipo\b",
    r"\brutas\s?del\s?pac[ií]fico\b",
    r"\blos\s?libertadores\b",
    r"\bpeaje\b",
    r"\blatam\b",
    r"\blatam\s?airlines\b",
    r"\bsky\s?airline\b",
    r"\bjetsmart\b",
    r"\baerol[ií]nea\b",
    r"\baeropuerto\b",
    r"\bhertz\b",
    r"\bavis\b",
    r"\beuropcar\b",
    r"\beconorent\b",
    r"\bchilean\s?rent\s?a\s?car\b",
    r"\brent\s?a\s?car\b",
    r"\buber\b",
    r"\bcabify\b",
    r"\bdidi\b",
    r"\bbeat\b",
    # =========================================================================
    # EDUCACIÓN DE CADENA
    # =========================================================================
    r"\bduoc\b",
    r"\bduoc\s?uc\b",
    r"\binacap\b",
    r"\baiep\b",
    r"\bsanto\s?tom[aá]s\b",
    r"\bip\s?chile\b",
    r"\bcft\b",
    r"\bipp\b",
    r"\bpreuniversitario\b",
    r"\bpedro\s?de\s?valdivia\b",
    r"\bcpech\b",
    r"\buniversidad\b",
    r"\binstituto\s?profesional\b",
    r"\bliceo\b",
    r"\bescuela\b",
    r"\bcolegio\b",
    r"\bjard[ií]n\s?infantil\b",
    r"\bsala\s?cuna\b",
    # =========================================================================
    # INSTITUCIONES PÚBLICAS Y COMUNITARIAS
    # =========================================================================
    r"\bmunicipalidad\b",
    r"\bilustre\s?municipalidad\b",
    r"\bdelegaci[oó]n\s?municipal\b",
    r"\bdelegaci[oó]n\s?presidencial\b",
    r"\bgobernaci[oó]n\b",
    r"\bgobierno\s?regional\b",
    r"\bjunta\s?de\s?vecinos\b",
    r"\bsede\s?social\b",
    r"\bsede\s?comunitaria\b",
    r"\bcentro\s?comunitario\b",
    r"\bclub\s?deportivo\b",
    r"\bcentro\s?de\s?madres\b",
    r"\bcomit[eé]\s?de\s?agua\s?potable\b",
    r"\bapr\b",
    r"\bcuerpo\s?de\s?bomberos\b",
    r"\bbomberos\b",
    r"\bcarabineros\b",
    r"\bret[eé]n\b",
    r"\btenencia\b",
    r"\bsubcomisar[ií]a\b",
    r"\bcomisar[ií]a\b",
    r"\bpdi\b",
    r"\bpolic[ií]a\s?de\s?investigaciones\b",
    r"\bgendarmer[ií]a\b",
    r"\bregistro\s?civil\b",
    r"\bchileatiende\b",
    r"\bips\b",
    r"\bjunji\b",
    r"\bfundaci[oó]n\s?integra\b",
    r"\bjunaeb\b",
    r"\bsence\b",
    r"\bbiblioteca\s?p[uú]blica\b",
    r"\bindap\b",
    r"\bsag\b",
    r"\bconaf\b",
    r"\bserviu\b",
    r"\bminvu\b",
    r"\bsernapesca\b",
    r"\bdga\b",
    r"\bsii\b",
    r"\btesorer[ií]a\b",
    r"\bcompin\b",
    r"\bsenda\b",
    r"\bsernameg\b",
    # =========================================================================
    # COMODINES SECTORIALES (baja precisión: usar como última pasada)
    # =========================================================================
    r"\bagro",
    r"\bvet",
    r"\bforraj",
    r"\bvivero\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\bsociedad\s?comercial\b",
    r"\bcarnicer[ií]a\b",
    r"\bverduler[ií]a\b",
    r"\bfiambrer[ií]a\b",
    r"\bpescader[ií]a\b",
    r"\bamasander[ií]a\b",
    r"\bel[eé]ctric",
    r"\belectronic",
    r"\bcooperativa\b",
    r"\bsindicato\b",
    r"\bfundaci[oó]n\b",
    r"\bcorporaci[oó]n\b",
]


# =============================================================================
# Patrones de ALTO riesgo de falso positivo.
# Están incluidos arriba en CHAIN_REGEX; esta lista existe para poder
# excluirlos fácilmente cuando se corre sobre texto libre:
#     SAFE_CHAIN_REGEX = [p for p in CHAIN_REGEX if p not in AMBIGUOUS_PATTERNS]
# =============================================================================
AMBIGUOUS_PATTERNS = {
    r"\b[uú]nico\b",
    r"\bpronto\b",
    r"\bmelt\b",
    r"\bsushi\b",
    r"\bhait[ií]\b",
    r"\bahumada\b",
    r"\bpar[ií]s\b",
    r"\bdin\b",
    r"\bcorona\b",
    r"\bdomin[oó]\b",
    r"\bclaro\b",
    r"\bmundo\b",
    r"\bsimple\b",
    r"\bcapital\b",
    r"\bdale\b",
    r"\bsanta\s?mar[ií]a\b",
    r"\bpatagonia\b",
    r"\bhelp\b",
    r"\bsar\b",
    r"\bsur\b",
    r"\btag\b",
    r"\bcelta\b",
    r"\bflex\b",
    r"\bmica\b",
    r"\bwei\b",
    r"\bcic\b",
    r"\bmts\b",
    r"\bgap\b",
    r"\bups\b",
    r"\bsag\b",
    r"\bips\b",
    r"\bisp\b",
    r"\bjac\b",
    r"\bbeat\b",
    r"\btuu\b",
    r"\bneat\b",
    r"\bmach\b",
    r"\bimperial\b",
    r"\beasy\b",
    r"\bconsorcio\b",
    r"\bsura\b",
    r"\bprincipal\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\bfundaci[oó]n\b",
    r"\bcorporaci[oó]n\b",
    r"\bcooperativa\b",
    r"\bescuela\b",
    r"\bcolegio\b",
    r"\buniversidad\b",
    r"\bhotel\b",
    r"\bfarmacia\b",
    r"\bcl[ií]nica\b",
    r"\bhospital\b",
    r"\bconsultorio\b",
    r"\bposta\b",
    r"\blaboratorio\b",
    r"\bcasino\b",
    r"\bgimnasio\b",
    r"\bpanader[ií]a\b",
    r"\bpasteler[ií]a\b",
    r"\bcarnicer[ií]a\b",
    r"\bferreter[ií]a\b",
    r"\blibrer[ií]a\b",
    r"\b[oó]ptica\b",
    r"\bveterinaria\b",
    r"\bjoyer[ií]a\b",
    r"\bbotiller[ií]a\b",
    r"\bpizzer[ií]a\b",
    r"\bcafeter[ií]a\b",
    r"\bhelader[ií]a\b",
    r"\brotiser[ií]a\b",
    r"\bminimarket\b",
}
