# config/patterns.py  —  PERÚ
# =============================================================================
# Módulo 2: Cadenas (adaptación a Perú del listado original de RD)
# Fuente estructural: 1_Limpieza_Duplicados_Cadenas.ipynb
#
#
#  - Texto normalizado a minúsculas.
#  - Variantes con y sin tilde.
#  - "# ambiguo" = alto riesgo de falso positivo (ver AMBIGUOUS_PATTERNS).
#  - "# rebrand" = cambió de nombre; útil para colapsar histórico.
# =============================================================================

CHAIN_REGEX = [
    # =========================================================================
    # SUPERMERCADOS — LOS TRES GRANDES GRUPOS Y SUS FORMATOS
    # =========================================================================
    # Intercorp / Supermercados Peruanos
    r"\bplaza\s?vea\b",
    r"\bplazavea\b",
    r"\bvivanda\b",
    r"\bmass\b",  # ambiguo
    r"\btiendas?\s?mass\b",
    r"\beconomax\b",
    r"\bsupermercados?\s?peruanos\b",
    r"\bspsa\b",
    r"\bintercorp\b",
    r"\binretail\b",
    # Cencosud Perú
    r"\bwong\b",
    r"\be\.?\s?wong\b",
    r"\bmetro\b",  # ambiguo (tren)
    r"\bmi\s?market\b",
    r"\bmimarket\b",
    r"\bcencosud\b",
    # Falabella Perú
    r"\btottus\b",
    r"\bhiperbodega\s?precio\s?uno\b",
    r"\bprecio\s?uno\b",
    # Mayoristas y otros
    r"\bmakro\b",
    r"\bmayorsa\b",
    r"\bsupermercados?\s?la\s?canasta\b",
    r"\bsupermercados?\s?franco\b",
    r"\bel\s?super\b",
    r"\bplaza\s?del\s?sol\b",
    r"\bsupermercados?\s?orion\b",  # verificar
    r"\bmercado\s?mayorista\b",
    r"\bsanta\s?anita\b",
    r"\bunicachi\b",
    r"\bcaquet[aá]\b",
    r"\bmercado\s?central\b",
    r"\bmercado\s?de\s?frutas\b",
    # =========================================================================
    # BODEGAS, CONVENIENCIA Y TIENDAS DE ESTACIÓN
    # =========================================================================
    r"\btambo\+?\b",
    r"\btambo\s?mas\b",
    r"\boxxo\b",
    r"\blisto!?\b",
    r"\brepshop\b",
    r"\bviva\s?repsol\b",
    r"\bjet\s?market\b",
    r"\bbodega\b",  # ambiguo (categoría dominante en Perú)
    r"\bminimarket\b",
    r"\bmini\s?market\b",
    r"\bbodeguita\b",
    # =========================================================================
    # COMBUSTIBLE Y GLP
    # =========================================================================
    r"\bprimax\b",
    r"\brepsol\b",
    r"\bpetroper[uú]\b",
    r"\bpecsa\b",
    r"\bpeco\b",  # verificar
    r"\bterpel\b",
    r"\bshell\b",
    r"\bcoesti\b",
    r"\bgrifo\b",
    r"\bgrifos\b",
    r"\bestaci[oó]n\s?de\s?servicio\b",
    r"\bservicentro\b",
    r"\bsolgas\b",
    r"\blima\s?gas\b",
    r"\bzeta\s?gas\b",
    r"\bllama\s?gas\b",
    r"\bcaserito\s?gas\b",
    r"\bfl[aá]magas\b",
    r"\bcalidda\b",
    r"\bc[aá]lidda\b",
    r"\bcontugas\b",
    r"\bgas\s?natural\s?vehicular\b",
    r"\bgnv\b",
    r"\bglp\b",
    # =========================================================================
    # DELIVERY, QUICK COMMERCE Y MARKETPLACES
    # =========================================================================
    r"\brappi\b",
    r"\bpedidosya\b",
    r"\bpedidos\s?ya\b",
    r"\bdidi\s?food\b",
    r"\bcornershop\b",
    r"\bfazil\b",
    r"\bglovo\b",
    r"\buber\s?eats\b",
    r"\bfavo\b",
    r"\bchazki\b",
    r"\bmercado\s?libre\b",
    r"\bmercadolibre\b",
    r"\bmeli\b",
    r"\bfalabella\.com\b",
    r"\blinio\b",
    r"\bjuntoz\b",
    r"\bshein\b",
    r"\btemu\b",
    r"\baliexpress\b",
    r"\bplatanitos\.com\b",
    # =========================================================================
    # FARMACIAS Y BOTICAS
    # =========================================================================
    r"\binkafarma\b",
    r"\binka\s?farma\b",
    r"\bmifarma\b",
    r"\bmi\s?farma\b",
    r"\bfarmacias\s?peruanas\b",
    r"\bboticas\s?(?:y|&)\s?salud\b",
    r"\bboticas\s?per[uú]\b",
    r"\bbtl\b",
    r"\bfasa\b",
    r"\bfarmacias\s?ahumada\b",
    r"\bboticas\s?arc[aá]ngel\b",
    r"\barc[aá]ngel\b",
    r"\bboticas\s?hogar\s?(?:y|&)\s?salud\b",
    r"\bqu[ií]mica\s?suiza\b",
    r"\bquicorp\b",
    r"\bfarmacia\s?universal\b",
    r"\bboticas\s?felicidad\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    r"\bdroguer[ií]a\b",
    # =========================================================================
    # GRANDES TIENDAS Y RETAIL POR DEPARTAMENTO
    # =========================================================================
    r"\bsaga\s?falabella\b",
    r"\bfalabella\b",
    r"\bripley\b",
    r"\boechsle\b",
    r"\bparis\b",  # ambiguo — Paris salió de Perú
    r"\bestilos\b",
    r"\btopitop\b",
    r"\btopi\s?top\b",
    r"\btiendas?\s?efe\b",
    r"\befe\b",  # ambiguo
    r"\bla\s?curacao\b",
    r"\bcarsa\b",
    r"\bhiraoka\b",
    r"\bcoolbox\b",
    r"\bmarcimex\b",
    r"\belektra\b",
    # =========================================================================
    # MEJORAMIENTO DEL HOGAR Y CONSTRUCCIÓN
    # =========================================================================
    r"\bsodimac\b",
    r"\bhomecenter\b",
    r"\bhome\s?center\b",
    r"\bpromart\b",
    r"\bmaestro\b",  # ambiguo
    r"\bcassinelli\b",
    r"\bdecor\s?center\b",
    r"\bcorporaci[oó]n\s?aceros\s?arequipa\b",
    r"\bprogresol\b",
    r"\bconstruredes\b",
    r"\bferreter[ií]a\b",
    r"\bpacasmayo\b",
    r"\bcementos\s?pacasmayo\b",
    r"\bcementos\s?lima\b",
    r"\bunicon\b",
    r"\bfirth\b",
    # =========================================================================
    # MODA, CALZADO Y DEPORTE
    # =========================================================================
    r"\bzara\b",
    r"\bh&m\b",
    r"\bforever\s?21\b",
    r"\bbershka\b",
    r"\bpull\s?(?:and|&)?\s?bear\b",
    r"\bstradivarius\b",
    r"\bmassimo\s?dutti\b",
    r"\bplatanitos\b",
    r"\bbata\b",
    r"\bpassarela\b",
    r"\bmarquis\b",
    r"\brenzo\s?costa\b",
    r"\bpieers\b",
    r"\bmichelle\s?belau\b",
    r"\bnorton\b",
    r"\bdo\s?it\b",
    r"\bbasement\b",
    r"\bindex\b",
    r"\bsybilla\b",
    r"\bmarathon\s?sports\b",
    r"\bmarathon\b",
    r"\bnike\b",
    r"\badidas\b",
    r"\bpuma\b",
    r"\bnew\s?balance\b",
    r"\btriathlon\b",
    r"\bcasa\s?rosselli\b",
    # =========================================================================
    # VARIEDADES, LIBRERÍAS Y PAPELERÍAS
    # =========================================================================
    r"\bminiso\b",
    r"\bmumuso\b",
    r"\bilahui\b",
    r"\btai\s?loy\b",
    r"\bcontinental\b",  # ambiguo (librería Continental)
    r"\bcrisol\b",
    r"\bzeta\s?bookstore\b",
    r"\bibero\s?librer[ií]as\b",
    r"\butilex\b",
    r"\bstandford\b",
    r"\blibrer[ií]a\b",
    r"\bpapeler[ií]a\b",
    r"\bbazar\b",
    # =========================================================================
    # COMIDA RÁPIDA INTERNACIONAL
    # =========================================================================
    r"\bmc\s?donald'?s?\b",
    r"\bmcdonald'?s?\b",
    r"\barcos\s?dorados\b",
    r"\bkfc\b",
    r"\bkentucky\s?fried\s?chicken\b",
    r"\bburger\s?king\b",
    r"\bpopeye'?s?\b",
    r"\bsubway\b",
    r"\bdomino'?s?\s?pizza\b",
    r"\bdominos?\b",
    r"\bpizza\s?hut\b",
    r"\bpapa\s?john'?s?\b",
    r"\bchili'?s\b",
    r"\bstarbucks\b",
    r"\bdunkin(?:'?s)?(?:\s?donuts)?\b",
    r"\bjuan\s?valdez\b",
    r"\btaco\s?bell\b",
    r"\bwendy'?s\b",
    r"\bfriday'?s\b",
    r"\bhooters\b",
    r"\bjohnny\s?rockets\b",
    r"\bkrispy\s?kreme\b",
    r"\bcinnabon\b",
    r"\bchina\s?wok\b",
    r"\bchinawok\b",
    # operadores / franquiciados (aparecen como razón social en glosas)
    r"\bdelosi\b",
    r"\bng\s?restaurants\b",
    r"\bsigdelo\b",  # verificar
    r"\bfranquicias\s?peruanas\b",  # verificar
    # =========================================================================
    # CADENAS PERUANAS DE COMIDA
    # =========================================================================
    r"\bbembos\b",
    r"\bnorky'?s\b",
    r"\brocky'?s\b",
    r"\broky'?s\b",
    r"\bpardos\s?chicken\b",
    r"\bpardos\b",
    r"\bla\s?le[nñ]a\b",
    r"\bvilla\s?chicken\b",
    r"\bdon\s?belisario\b",
    r"\bel\s?rancho\b",
    r"\bprimos\s?chicken\b",
    r"\botto\s?grill\b",
    r"\bpollo\s?a\s?la\s?brasa\b",
    r"\bpoller[ií]a\b",
    r"\bchifa\b",
    r"\bcevicher[ií]a\b",
    r"\banticucher[ií]a\b",
    r"\bla\s?lucha\b",
    r"\bla\s?lucha\s?sanguicher[ií]a\b",
    r"\bpasquale\s?hermanos\b",
    r"\bsegundo\s?muelle\b",
    r"\btanta\b",
    r"\bpanchita\b",
    r"\bmadam\s?tusan\b",
    r"\bla\s?mar\b",
    r"\bosaka\b",
    r"\bmaido\b",
    r"\bcentral\b",  # ambiguo
    r"\bastrid\s?(?:y|&)\s?gast[oó]n\b",
    r"\brafael\b",
    r"\bmayta\b",
    r"\bkjolle\b",
    r"\bmalabar\b",
    r"\bfiesta\b",  # ambiguo
    r"\bembarcadero\s?41\b",
    r"\bpunto\s?azul\b",
    r"\bcanta\s?rana\b",
    r"\brustica\b",
    r"\br[uú]stica\b",
    r"\bmangos\b",
    r"\bla\s?bistecca\b",
    r"\bel\s?tiziano\b",
    r"\btzuru\b",
    r"\bedo\s?sushi\b",
    r"\bmakoto\b",
    r"\bkoi\b",
    r"\bnikkei\b",
    r"\bsanguicher[ií]a\b",
    # =========================================================================
    # CAFÉ, PANADERÍA, PASTELERÍA Y HELADOS
    # =========================================================================
    r"\baltomayo\b",
    r"\bcaf[eé]\s?britt\b",
    r"\bbisetti\b",
    r"\barabica\b",
    r"\btostaduria\b",
    r"\bpuku\s?puku\b",
    r"\bneira\s?caf[eé]\b",
    r"\bsan\s?antonio\b",
    r"\bdon\s?mamino\b",
    r"\bla\s?baguette\b",
    r"\bpasteler[ií]a\s?san\s?antonio\b",
    r"\bbimbo\b",
    r"\bpan\s?pons\b",
    r"\bcaf[eé]\s?verde\b",
    r"\bmotitas\b",  # verificar
    r"\bd'?onofrio\b",
    r"\bdonofrio\b",
    r"\blaritza\s?d'?\b",
    r"\b4d\b",
    r"\bblu\b",  # ambiguo
    r"\bh[aä]agen[\s\-]?dazs\b",
    r"\bcrepes\s?(?:y|&)\s?waffles\b",
    r"\bmanolo\b",
    r"\bcafeter[ií]a\b",
    r"\bpanader[ií]a\b",
    r"\bpasteler[ií]a\b",
    # =========================================================================
    # BANCA
    # =========================================================================
    r"\bbcp\b",
    r"\bbanco\s?de\s?cr[eé]dito\b",
    r"\bcredicorp\b",
    r"\bbbva\b",
    r"\bbbva\s?continental\b",
    r"\bbanco\s?continental\b",
    r"\binterbank\b",
    r"\bscotiabank\b",
    r"\bbanco\s?wiese\b",
    r"\bbanco\s?de\s?la\s?naci[oó]n\b",
    r"\bbanco\s?naci[oó]n\b",
    r"\bbn\b",
    r"\bbanbif\b",
    r"\bbanco\s?interamericano\s?de\s?finanzas\b",
    r"\bmibanco\b",
    r"\bmi\s?banco\b",
    r"\bbanco\s?pichincha\b",
    r"\bbanco\s?financiero\b",
    r"\bbanco\s?gnb\b",
    r"\bcitibank\b",
    r"\bbanco\s?falabella\b",
    r"\bbanco\s?ripley\b",
    r"\bbanco\s?azteca\b",
    r"\balfin\s?banco\b",
    r"\bbanco\s?santander\b",
    r"\bicbc\b",
    r"\bcrediscotia\b",
    r"\bcompartamos\b",
    r"\bfinanciera\s?oh!?\b",
    r"\bfinanciera\s?confianza\b",
    r"\bfinanciera\s?efectiva\b",
    r"\bfinanciera\s?qapaq\b",
    r"\bfinanciera\s?proempresa\b",
    r"\bcaja\s?arequipa\b",
    r"\bcaja\s?huancayo\b",
    r"\bcaja\s?piura\b",
    r"\bcaja\s?cusco\b",
    r"\bcaja\s?trujillo\b",
    r"\bcaja\s?sullana\b",
    r"\bcaja\s?ica\b",
    r"\bcaja\s?tacna\b",
    r"\bcaja\s?maynas\b",
    r"\bcaja\s?del\s?santa\b",
    r"\bcaja\s?paita\b",
    r"\bcaja\s?metropolitana\b",
    r"\bcaja\s?los\s?andes\b",
    r"\bcaja\s?raiz\b",
    r"\bcaja\s?ra[ií]z\b",
    r"\bcaja\s?municipal\b",
    r"\bcooperativa\s?pac[ií]fico\b",
    r"\babaco\b",
    r"\bbanco\s?central\s?de\s?reserva\b",
    r"\bbcrp\b",
    r"\bsbs\b",
    r"\bcofide\b",
    r"\bagrobanco\b",
    r"\bfondo\s?mivivienda\b",
    # =========================================================================
    # MEDIOS DE PAGO, BILLETERAS Y AGENTES
    # =========================================================================
    r"\byape\b",
    r"\bplin\b",
    r"\btunki\b",
    r"\bligo\b",
    r"\bbim\b",
    r"\bniubiz\b",
    r"\bvisanet\b",
    r"\bizipay\b",
    r"\bculqi\b",
    r"\bvendem[aá]s\b",
    r"\bpagoefectivo\b",
    r"\bpago\s?efectivo\b",
    r"\bsafetypay\b",
    r"\bkasnet\b",
    r"\bagente\s?bcp\b",
    r"\bagente\s?multired\b",
    r"\bmultired\b",
    r"\bagente\s?interbank\b",
    r"\bwestern\s?union\b",
    r"\bmoney\s?gram\b",
    r"\bmoneygram\b",
    r"\bglobokas\b",
    r"\bfullcarga\b",
    r"\brappipay\b",
    r"\bmercado\s?pago\b",
    # =========================================================================
    # SEGUROS, AFP Y SALUD
    # =========================================================================
    r"\brimac\b",
    r"\bpac[ií]fico\s?seguros\b",
    r"\bla\s?positiva\b",
    r"\bmapfre\b",
    r"\binterseguro\b",
    r"\bprotecta\b",
    r"\bcrecer\s?seguros\b",
    r"\bsanitas\b",
    r"\bavla\b",
    r"\bchubb\b",
    r"\bqualitas\b",
    r"\bafp\s?integra\b",
    r"\bprima\s?afp\b",
    r"\bprofuturo\b",
    r"\bafp\s?habitat\b",
    r"\bafp\s?horizonte\b",
    r"\bafp\b",
    r"\bessalud\b",
    r"\bes\s?salud\b",
    r"\bsis\b",
    r"\bminsa\b",
    r"\bcl[ií]nica\s?internacional\b",
    r"\bcl[ií]nica\s?san\s?pablo\b",
    r"\bcl[ií]nica\s?ricardo\s?palma\b",
    r"\bcl[ií]nica\s?anglo\s?americana\b",
    r"\bcl[ií]nica\s?delgado\b",
    r"\bcl[ií]nica\s?javier\s?prado\b",
    r"\bcl[ií]nica\s?good\s?hope\b",
    r"\bcl[ií]nica\s?montesur\b",
    r"\bcl[ií]nica\s?san\s?felipe\b",
    r"\bcl[ií]nica\s?stella\s?maris\b",
    r"\bauna\b",
    r"\boncosalud\b",
    r"\bsanna\b",
    r"\bcl[ií]nica\s?vallesur\b",
    r"\bsuiza\s?lab\b",
    r"\bsuizalab\b",
    r"\bblufstein\b",
    r"\broe\b",
    r"\banglolab\b",
    r"\bprecisa\b",
    r"\bunilabs\b",
    r"\bcentro\s?de\s?salud\b",
    r"\bpuesto\s?de\s?salud\b",
    r"\bposta\s?m[eé]dica\b",
    r"\bhospital\s?regional\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\bdiresa\b",
    r"\bgeresa\b",
    r"\bclas\b",
    r"\blaboratorio\b",
    # =========================================================================
    # TELECOMUNICACIONES
    # =========================================================================
    r"\bmovistar\b",
    r"\btelef[oó]nica\b",
    r"\btelef[oó]nica\s?del\s?per[uú]\b",
    r"\bclaro\b",
    r"\bam[eé]rica\s?m[oó]vil\b",
    r"\bentel\b",
    r"\bnextel\b",
    r"\bbitel\b",
    r"\bviettel\b",
    r"\bwin\b",  # ambiguo
    r"\bwow\b",
    r"\bdirectv\b",
    r"\bfiberlux\b",
    r"\bstar\s?global\b",
    r"\boptical\s?networks\b",
    r"\bosiptel\b",
    r"\bstarlink\b",
    # =========================================================================
    # ENERGÍA, AGUA Y SANEAMIENTO
    # =========================================================================
    r"\bluz\s?del\s?sur\b",
    r"\benel\b",
    r"\benel\s?distribuci[oó]n\b",
    r"\bedelnor\b",
    r"\bdistriluz\b",
    r"\bhidrandina\b",
    r"\belectrocentro\b",
    r"\belectronorte\b",
    r"\benosa\b",
    r"\bseal\b",
    r"\belectro\s?sur\s?este\b",
    r"\belectro\s?puno\b",
    r"\belectro\s?oriente\b",
    r"\belectro\s?ucayali\b",
    r"\belectro\s?dunas\b",
    r"\bcoelvisac\b",
    r"\bosinergmin\b",
    r"\bsedapal\b",
    r"\bsedapar\b",
    r"\bsedalib\b",
    r"\bepsel\b",
    r"\bseda\s?hu[aá]nuco\b",
    r"\bsedacusco\b",
    r"\bemapa\b",
    r"\bsunass\b",
    # =========================================================================
    # LOGÍSTICA Y COURIER
    # =========================================================================
    r"\bserpost\b",
    r"\bolva\s?courier\b",
    r"\bolva\b",
    r"\bshalom\b",
    r"\bmarvisur\b",
    r"\bcruz\s?del\s?sur\s?cargo\b",
    r"\brappi\s?cargo\b",
    r"\bdhl\b",
    r"\bfedex\b",
    r"\bups\b",
    r"\burbano\b",
    # =========================================================================
    # HOTELERÍA
    # =========================================================================
    r"\bmarriott\b",
    r"\bjw\s?marriott\b",
    r"\bwestin\b",
    r"\bcourtyard\b",
    r"\baloft\b",
    r"\bhilton\b",
    r"\bhampton\b",
    r"\bdoubletree\b",
    r"\bhyatt\b",
    r"\bhyatt\s?centric\b",
    r"\bbelmond\b",
    r"\bmiraflores\s?park\b",
    r"\bcountry\s?club\s?lima\b",
    r"\blos\s?delfines\b",
    r"\bswissotel\b",
    r"\bsheraton\b",
    r"\bwyndham\b",
    r"\bibis\b",
    r"\bnovotel\b",
    r"\bmercure\b",
    r"\bholiday\s?inn(?:\s?express)?\b",
    r"\bradisson\b",
    r"\bbest\s?western\b",
    r"\bcasa\s?andina\b",
    r"\bcosta\s?del\s?sol\b",
    r"\blibertador\b",
    r"\baranwa\b",
    r"\binkaterra\b",
    r"\btierra\s?viva\b",
    r"\bsonesta\b",
    r"\bdecameron\b",
    r"\bel\s?pueblo\b",
    r"\bairbnb\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\bhospedaje\b",
    r"\balbergue\b",
    # =========================================================================
    # ENTRETENCIÓN, CINES, MALLS Y JUEGO
    # =========================================================================
    r"\bcineplanet\b",
    r"\bcinemark\b",
    r"\bcin[eé]polis\b",
    r"\buvk\b",
    r"\bcine\s?star\b",
    r"\bmovie\s?time\b",
    r"\bjockey\s?plaza\b",
    r"\breal\s?plaza\b",
    r"\bmall\s?aventura\b",
    r"\bplaza\s?norte\b",
    r"\bmegaplaza\b",
    r"\blarcomar\b",
    r"\bopen\s?plaza\b",
    r"\bminka\b",
    r"\bmall\s?del\s?sur\b",
    r"\bplaza\s?lima\s?sur\b",
    r"\bparque\s?arauco\b",
    r"\bcamino\s?real\b",
    r"\bconey\s?park\b",
    r"\bhappyland\b",
    r"\bdivercity\b",
    r"\bla\s?tinka\b",
    r"\btinka\b",
    r"\bte\s?apuesto\b",
    r"\bapuesta\s?total\b",
    r"\binkabet\b",
    r"\bdoradobet\b",
    r"\bbetsson\b",
    r"\bmeridianbet\b",
    r"\batlantic\s?city\b",
    r"\bgolden\s?palace\b",
    r"\bfiesta\s?casino\b",
    r"\bmajestic\b",
    r"\bla\s?hacienda\b",
    r"\bcasino\b",
    r"\btragamonedas\b",
    r"\bsala\s?de\s?juegos\b",
    # =========================================================================
    # GIMNASIOS
    # =========================================================================
    r"\bsmart\s?fit\b",
    r"\bsmartfit\b",
    r"\bbodytech\b",
    r"\bgold'?s?\s?gym\b",
    r"\bsportlife\b",
    r"\bvidasana\b",
    r"\benergym\b",
    r"\bcrossfit\b",
    r"\bgimnasio\b",
    # =========================================================================
    # TRANSPORTE Y MOVILIDAD
    # =========================================================================
    r"\blatam\b",
    r"\bsky\s?airline\b",
    r"\bjetsmart\b",
    r"\bstar\s?per[uú]\b",
    r"\blc\s?per[uú]\b",
    r"\bperuvian\b",
    r"\bviva\s?air\b",
    r"\blan\s?per[uú]\b",
    r"\bcruz\s?del\s?sur\b",
    r"\boltursa\b",
    r"\bm[oó]vil\s?tours\b",
    r"\bciva\b",
    r"\bexcluciva\b",
    r"\btepsa\b",
    r"\bwari\b",
    r"\bl[ií]nea\b",  # ambiguo
    r"\bterminal\s?terrestre\b",
    r"\bmetropolitano\b",
    r"\bmetro\s?de\s?lima\b",
    r"\bl[ií]nea\s?1\b",
    r"\batu\b",
    r"\bcorredor\s?azul\b",
    r"\bpeaje\b",
    r"\brutas\s?de\s?lima\b",
    r"\blamsac\b",
    r"\bl[aá]mac\b",
    r"\buber\b",
    r"\bcabify\b",
    r"\bindriver\b",
    r"\bin\s?driver\b",
    r"\bdidi\b",
    r"\bbeat\b",
    r"\bhertz\b",
    r"\bavis\b",
    r"\bbudget\b",
    r"\blocaliza\b",
    # =========================================================================
    # AUTOMOTRIZ
    # =========================================================================
    r"\btoyota\s?del\s?per[uú]\b",
    r"\bmitsui\b",
    r"\bderco\b",
    r"\bindumotora\b",
    r"\bautomotores\s?gildemeister\b",
    r"\beuromotors\b",
    r"\binchcape\b",
    r"\bcrosland\b",
    r"\bhonda\s?del\s?per[uú]\b",
    r"\bnissan\s?maquinarias\b",
    r"\bkia\s?import\b",
    r"\bmotocorp\b",
    r"\brepuestos\b",
    r"\bllanter[ií]a\b",
    r"\blubricentro\b",
    # =========================================================================
    # EDUCACIÓN
    # =========================================================================
    r"\bunmsm\b",
    r"\bpucp\b",
    r"\bupc\b",
    r"\busil\b",
    r"\butp\b",
    r"\bucv\b",
    r"\buniversidad\s?c[eé]sar\s?vallejo\b",
    r"\buniversidad\s?continental\b",
    r"\bupn\b",
    r"\buniversidad\s?de\s?lima\b",
    r"\buniversidad\s?del\s?pac[ií]fico\b",
    r"\besan\b",
    r"\buni\b",  # ambiguo
    r"\bcibertec\b",
    r"\bsenati\b",
    r"\btecsup\b",
    r"\bidat\b",
    r"\bzegel\b",
    r"\bipae\b",
    r"\btoulouse\s?lautrec\b",
    r"\bsise\b",
    r"\buniversidad\b",
    r"\binstituto\b",
    r"\bcolegio\b",
    r"\binstituci[oó]n\s?educativa\b",
    r"\bi\.?e\.?\b",
    r"\bcuna\s?jard[ií]n\b",
    # =========================================================================
    # INSTITUCIONES PÚBLICAS Y COMUNITARIAS
    # =========================================================================
    r"\bmunicipalidad\b",
    r"\bmunicipalidad\s?distrital\b",
    r"\bmunicipalidad\s?provincial\b",
    r"\bgobierno\s?regional\b",
    r"\bcomisar[ií]a\b",
    r"\bpnp\b",
    r"\bpolic[ií]a\s?nacional\b",
    r"\bcompa[nñ][ií]a\s?de\s?bomberos\b",
    r"\bbomberos\b",
    r"\bserenazgo\b",
    r"\breniec\b",
    r"\bsunat\b",
    r"\bonp\b",
    r"\bindeci\b",
    r"\bvaso\s?de\s?leche\b",
    r"\bcomedor\s?popular\b",
    r"\bolla\s?com[uú]n\b",
    r"\bqali\s?warma\b",
    r"\bcuna\s?m[aá]s\b",
    r"\bjuntos\b",
    r"\bpensi[oó]n\s?65\b",
    r"\bfoncodes\b",
    r"\bagrorural\b",
    r"\bagencia\s?agraria\b",
    r"\bpronied\b",
    r"\bmidis\b",
    r"\bmimp\b",
    r"\bmunicipio\b",
    r"\blocal\s?comunal\b",
    r"\bjunta\s?vecinal\b",
    r"\bparroquia\b",
    r"\biglesia\b",
    r"\bcomunidad\s?campesina\b",
    r"\bcentro\s?poblado\b",
    # =========================================================================
    # COMODINES SECTORIALES
    # =========================================================================
    r"\bagro",
    r"\bvet",
    r"\bforraj",
    r"\bvivero\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\bferia\b",
    r"\bmercado\b",
    r"\bcarnicer[ií]a\b",
    r"\bavicola\b",
    r"\bav[ií]cola\b",
    r"\bfrigor[ií]fico\b",
    r"\bel[eé]ctric",
    r"\belectronic",
    r"\bcooperativa\b",
    r"\basociaci[oó]n\b",
]


# =============================================================================
# Patrones de ALTO riesgo de falso positivo (incluidos arriba).
#     SAFE_CHAIN_REGEX = [p for p in CHAIN_REGEX if p not in AMBIGUOUS_PATTERNS]
# =============================================================================
AMBIGUOUS_PATTERNS = {
    r"\bmass\b",
    r"\bmetro\b",
    r"\bbodega\b",
    r"\bparis\b",
    r"\befe\b",
    r"\bmaestro\b",
    r"\bcontinental\b",
    r"\bcentral\b",
    r"\bfiesta\b",
    r"\bblu\b",
    r"\b4d\b",
    r"\bwin\b",
    r"\bwow\b",
    r"\broe\b",
    r"\bbim\b",
    r"\bligo\b",
    r"\bsis\b",
    r"\bclas\b",
    r"\bseal\b",
    r"\bbn\b",
    r"\buni\b",
    r"\bipae\b",
    r"\bidat\b",
    r"\batu\b",
    r"\bciva\b",
    r"\bl[ií]nea\b",
    r"\bbeat\b",
    r"\bbudget\b",
    r"\bjuntos\b",
    r"\bmajestic\b",
    r"\bcasino\b",
    r"\btinka\b",
    r"\bminka\b",
    r"\bkoi\b",
    r"\bmangos\b",
    r"\bnorton\b",
    r"\bindex\b",
    r"\bdo\s?it\b",
    r"\bmarathon\b",
    r"\bprecisa\b",
    r"\bauna\b",
    r"\babaco\b",
    r"\bwong\b",
    r"\bpardos\b",
    r"\bla\s?mar\b",
    r"\bmayta\b",
    r"\brafael\b",
    r"\bgrifo\b",
    r"\bgrifos\b",
    r"\bpeco\b",
    r"\bglp\b",
    r"\bgnv\b",
    r"\bmercado\b",
    r"\bferia\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\bcooperativa\b",
    r"\basociaci[oó]n\b",
    r"\bvivero\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\bhospedaje\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    r"\bdroguer[ií]a\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\blaboratorio\b",
    r"\bferreter[ií]a\b",
    r"\blibrer[ií]a\b",
    r"\bpapeler[ií]a\b",
    r"\bbazar\b",
    r"\bpanader[ií]a\b",
    r"\bpasteler[ií]a\b",
    r"\bcafeter[ií]a\b",
    r"\bpoller[ií]a\b",
    r"\bchifa\b",
    r"\bcevicher[ií]a\b",
    r"\bcolegio\b",
    r"\buniversidad\b",
    r"\binstituto\b",
    r"\bi\.?e\.?\b",
    r"\bgimnasio\b",
    r"\bmunicipio\b",
    r"\bparroquia\b",
    r"\biglesia\b",
    r"\bpeaje\b",
    r"\bminimarket\b",
}
