# config/patterns.py

# =============================================================================
# Módulo 2: Cadenas (Source: 1_Limpieza_Duplicados_Cadenas.ipynb)
# =============================================================================
CHAIN_REGEX = [
    r"\bsupermercados?\s?nacional\b", r"\bsuper\s?nacional\b", r"\bcentro\s?cuesta\s?nacional\b",
    r"\bccn\b", r"\bjumbo\b", r"\bjumbo\s?express\b", r"\bmercajumbo\b", r"\bmerca\s?jumbo\b",
    r"\bla\s?sirena\b", r"\bsirena\s?market\b", r"\bmulticentro\s?la\s?sirena\b", r"\bmulticentro\s?sirena\b",
    r"\bgrupo\s?ramos\b", r"\bsuper\s?pola\b", r"\bsuperpola\b", r"\baprezio\b", r"\bmultiplaza\b",
    r"\bsupermercados?\s?bravo\b", r"\bsuper\s?bravo\b", r"\bhipermercados?\s?ol[eé]\b",
    r"\bsupermercados?\s?ol[eé]\b", r"\bpricesmart\b", r"\bprice\s?smart\b", r"\bhipermercados?\s?iberia\b",
    r"\biberia\s?supermercado\b", r"\bsupermercados?\s?jose\s?luis\b", r"\bsuper\s?fresh\s?market\b",
    r"\bsupermercados?\s?soberano\b", r"\bsuper\s?mercado\s?soberano\b", r"\bhipermercados?\s?la\s?fuente\b",
    r"\bsupermercados?\s?la\s?fuente\b", r"\bla\s?fuente\s?fun\b", r"\bel\s?drag[oó]n\s?de\s?oro\b",
    r"\blas\s?canas\s?market\s?place\b", r"\bsmart\s?shop\b", r"\bsmartshop\b", r"\bsmart\s?wash\b",
    r"\bsuper\s?express\b", r"\bsuperexpress\b", r"\bquick\s?market\b", r"\bfood\s?mart\b",
    r"\bfoodmart\b", r"\boxxo\b", r"\bseven\s?eleven\b", r"\b7[\s\-]?eleven\b", r"\bcity\s?market\b",
    r"\bgo\s?market\b", r"\btotalenergies\b", r"\btotal\s?energies\b", r"\bestaci[oó]n\s?total\b",
    r"\bgasolineras?\s?total\b", r"\bsunix\b", r"\bsunix\s?petroleum\b", r"\besso\b", r"\bestaci[oó]n\s?next\b",
    r"\bgasolineras?\s?next\b", r"\bsigma\b", r"\bsigma\s?petroleum\b", r"\bpetrom[oó]vil\b", r"\bpetromovil\b",
    r"\btexaco\b", r"\bgulfstream\b", r"\bshell\b", r"\beco\s?petr[oó]leo\b", r"\bunited\s?petroleum\b",
    r"\brilix\b", r"\bisla\s?petroleum\b", r"\bchevron\b", r"\bmobil\b", r"\bbp\b", r"\bm[eé]trogas\b",
    r"\btropigas\b", r"\bpropa[\s\-]?gas\b", r"\b[oó]ptimo\s?gas\b", r"\bcoastal\b", r"\bpollos?\s?victorina\b",
    r"\bvictorina\b", r"\bpollos?\s?rey\b", r"\bpala\s?pizza\b", r"\bpizzarelli\b", r"\bpizza\s?house\b",
    r"\bthe\s?pizza\s?house\b", r"\bpizza\s?man[ií]a\b", r"\bpizzamania\b", r"\bdomino'?s?\s?pizza\b",
    r"\bdominos?\b", r"\bpizza\s?hut\b", r"\bpapa\s?john'?s\b", r"\blittle\s?caesars\b", r"\btelepizza\b",
    r"\bmc\s?donald'?s?\b", r"\bmcdonald'?s?\b", r"\bburger\s?king\b", r"\bwendy'?s\b", r"\bkfc\b",
    r"\bkentucky\s?fried\s?chicken\b", r"\bsubway\b", r"\btaco\s?bell\b", r"\bcarl'?s\s?jr\b", r"\bquiznos\b",
    r"\bhooters\b", r"\bbuffalo\s?wild\s?wings\b", r"\bwingstop\b", r"\bwing\s?stop\b", r"\bchili'?s\b",
    r"\btony\s?roma'?s\b", r"\btgi\s?fridays?\b", r"\bfridays?\b", r"\bchef\s?pepper\b", r"\bpork\s?(?:and|&)\s?beer\b",
    r"\brico\s?hot\s?dog\b", r"\bemparedado\b", r"\bpizza\s?deli\s?bely\b", r"\bdunkin(?:'?s)?(?:\s?donuts)?\b",
    r"\bkrispy\s?kreme\b", r"\bcinnabon\b", r"\bpopeye'?s?\b", r"\bdenny'?s\b", r"\bapplebee'?s\b", r"\bihop\b",
    r"\bbaker\b", r"\bfroots\b", r"\badri[aá]n\s?tropical\b", r"\bel\s?mes[oó]n\s?de\s?la\s?cava\b",
    r"\bvesuvio\b", r"\bpat'?e\s?palo\b", r"\bmesa\s?suprema\b", r"\bel\s?conuco\b", r"\bel\s?lina\b",
    r"\bsushi\s?ya\b", r"\bmitre\b", r"\bbottega\b", r"\bil\s?capo\b", r"\bpapagayo\b", r"\bpositano\b",
    r"\bsegafredo\b", r"\bsegafredo\s?zanetti\b", r"\bcafeto\b", r"\bforno\s?bianco\b", r"\bnespresso\b",
    r"\bjuan\s?valdez\b", r"\bthe\s?coffee\s?bean\b", r"\bil\s?caff[eè]\b", r"\bla\s?cafetera\b",
    r"\bbon\s?caf[eé]\b", r"\bpan\s?(?:y|&)\s?m[aá]s\b", r"\bla\s?europea\b", r"\bpanader[ií]a\s?cocoroco\b",
    r"\bcocoroco\b", r"\bdulcer[ií]a\s?dominicana\b", r"\bbany'?s\b", r"\bcandy\s?express\b", r"\bbimbo\b",
    r"\bbim\s?bo\b", r"\bhelados?\s?bon\b", r"\bbon\b", r"\bbaskin\s?robbins\b", r"\bdairy\s?queen\b",
    r"\byogen\s?fr[üu]z\b", r"\bcold\s?stone\b", r"\bh[aä]agen[\s\-]?dazs\b", r"\bhelados?\s?dippin\b",
    r"\bfarmacias?\s?carol\b", r"\bfarmacia\s?carol\b", r"\bfarmacias?\s?los\s?hidalgos\b",
    r"\blos\s?hidalgos\b", r"\bmedicar\s?gbc\b", r"\bfarmacias?\s?gbc\b", r"\bgbc\b", r"\bfarmax\b",
    r"\bfarmaxtra\b", r"\bfarma\s?xtra\b", r"\bfarmaplan\b", r"\bfarmacia\s?del\s?ahorro\b", r"\bgnc\b",
    r"\bsally\s?beauty\b", r"\bsephora\b", r"\bbarcel[oó]\b", r"\biberostar\b", r"\bbah[ií]a\s?principe\b",
    r"\briu\b", r"\bmeli[aá]\b", r"\bcatalonia\b", r"\blopesan\b", r"\bhard\s?rock\s?hotel\b",
    r"\bhard\s?rock\s?caf[eé]\b", r"\bhilton\b", r"\bembassy\s?suites\b", r"\bhampton\s?inn\b",
    r"\bdoubletree\b", r"\bdouble\s?tree\b", r"\bmarriott\b", r"\bjw\s?marriott\b",
    r"\bcourtyard(?:\s?by\s?marriott)?\b", r"\bsheraton\b", r"\bintercontinental\b", r"\bcrowne\s?plaza\b",
    r"\bholiday\s?inn(?:\s?express)?\b", r"\bhyatt\b", r"\bhyatt\s?place\b", r"\bcasa\s?de\s?campo\b",
    r"\bdreams\b", r"\bsecrets\b", r"\bbreathless\b", r"\bnow\s?(?:onyx|larimar)\b", r"\bgrand\s?palladium\b",
    r"\bpalladium\b", r"\bbe\s?live\b", r"\boccidental\b", r"\bmajestic\b", r"\bocean\s?(?:blue|sand|el\s?faro)\b",
    r"\bviva\s?wyndham\b", r"\bwyndham(?:\s?garden)?\b", r"\bsunscape\b", r"\bbest\s?western\b",
    r"\bla\s?quinta(?:\s?inns?\s?(?:and|&)\s?suites)?\b", r"\bcomfort\s?inn\b", r"\bquality\s?(?:inn|hotel)\b",
    r"\bramada\b", r"\bairbnb\b", r"\bgympro\b", r"\bgym\s?pro\b", r"\bbody\s?shop\s?athletic\b",
    r"\bbody\s?shop\b", r"\bworld\s?fitness\b", r"\bsmart\s?fit\b", r"\bsmartfit\b", r"\bgold'?s?\s?gym\b",
    r"\banytime\s?fitness\b", r"\bcrossfit\b", r"\bcross\s?fit\b", r"\borangetheory\b", r"\bcrunch\s?fitness\b",
    r"\bsport\s?city\b", r"\bcaribbean\s?cinemas\b", r"\bpalacio\s?del\s?cine\b", r"\bfine\s?arts\b",
    r"\bmegaplex\b", r"\bbowlerama\b", r"\bjet\s?set\b", r"\boz\b", r"\bclub\s?malecon\b", r"\birish\s?pub\b",
    r"\bo'?\s?reilly'?s\b", r"\bplaza\s?lama\b", r"\balmacenes?\s?el\s?canal\b", r"\bel\s?canal\b",
    r"\bla\s?isla\b", r"\btiendas?\s?garrido\b", r"\bhipertiendas?\s?zaglul\b", r"\bzaglul\b",
    r"\balmacenes?\s?unidos?\b", r"\bla\s?baratosa\b", r"\bcasa\s?nader\b", r"\bla\s?bomba\b",
    r"\bcasa\s?cuesta\b", r"\bferreter[ií]a\s?cuesta\b", r"\blibrer[ií]a\s?cuesta\b", r"\bjuguet[oó]n\b",
    r"\bferreter[ií]a\s?americana\b", r"\bferreter[ií]a\s?ochoa\b", r"\bcorripio\b", r"\bmax\s?comercial\b",
    r"\bradiocentro\b", r"\bikea\b", r"\bcarrefour\b", r"\bgallo\s?m[aá]s\s?gallo\b", r"\bla\s?curacao\b",
    r"\belektra\b", r"\bminiso\b", r"\bmumuso\b", r"\bilahui\b", r"\boffice\s?(?:depot|max)\b",
    r"\bautozone\b", r"\bthe\s?home\s?depot\b", r"\bhome\s?depot\b", r"\bepa\b", r"\bzara\b", r"\bh&m\b",
    r"\bbershka\b", r"\bforever\s?21\b", r"\bnike\b", r"\badidas\b", r"\bskechers\b", r"\bpayless\b",
    r"\bclaro\b", r"\bclaro\s?dominicana\b", r"\baltice\b", r"\bviva\b", r"\bwind\s?telecom\b", r"\bwind\b",
    r"\bbanreservas\b", r"\bbanco\s?de\s?reservas\b", r"\bbanco\s?popular\b", r"\bpopular\s?dominicano\b",
    r"\bbhd\b", r"\bbhd\s?le[oó]n\b", r"\bbanco\s?bhd\b", r"\bscotiabank\b", r"\bbanco\s?del\s?progreso\b",
    r"\bdominicano\s?del\s?progreso\b", r"\bbanco\s?santa\s?cruz\b", r"\bbanco\s?caribe\b", r"\bbanco\s?vimenca\b",
    r"\bvimenca\b", r"\bbanco\s?ademi\b", r"\bademi\b", r"\bbanesco\b", r"\bbanco\s?promerica\b",
    r"\bpromerica\b", r"\bbanco\s?l[oó]pez\s?de\s?haro\b", r"\bbanco\s?bdi\b", r"\bqik\b", r"\bapap\b",
    r"\basociaci[oó]n\s?popular\b", r"\basociaci[oó]n\s?cibao\b", r"\basociaci[oó]n\s?la\s?nacional\b",
    r"\balnap\b", r"\bbanco\s?central\b", r"\bcitibank\b", r"\bpepsi\b", r"\bpepsi[\s\-]?cola\b",
    r"\blaboratorio\b", r"\balbergue\b", r"\belectronic\b", r"\bcasa\s?comunal\b", r"\bcasa\s?de\s?cultura\b",
    r"\bcentro\s?de\s?salud\b", r"\bcl[ií]nica\b", r"\bcuerpo\s?de\s?bomberos\b", r"\bagro", r"\bvet"
]
