# config/patterns.py  —  BRASIL
# =============================================================================
# Módulo 2: Cadenas (adaptación a Brasil del listado original de RD)
# Fuente estructural: 1_Limpieza_Duplicados_Cadenas.ipynb
#
# ALCANCE: cobertura de las cadenas MÁS IMPORTANTES de Brasil (nacionales y las
# regionales grandes). No es exhaustivo como los archivos de Chile / RD: no
# incluye la cola larga de redes locales por estado. Construido con conocimiento
# del mercado — el presupuesto de búsqueda web de la sesión estaba agotado, así
# que conviene validar fechas de cierre/rebranding antes de producción.
#
# NOTA DE NORMALIZACIÓN (crítico en portugués):
#  - Texto en minúsculas.
#  - Los patrones toleran texto SIN acentos (muy común en data sucia brasileña):
#    ç→[cç], ã→[aã], õ→[oõ], é→[eé], á→[aá], ê→[eê], ô→[oô], ú→[uú], í→[ií].
#  - "# ambíguo" = alto riesgo de falso positivo (ver AMBIGUOUS_PATTERNS).
#  - "# rebrand" = la marca cambió de nombre.
# =============================================================================

CHAIN_REGEX = [
    # =========================================================================
    # VAREJO ALIMENTAR — GRANDES GRUPOS NACIONALES
    # =========================================================================
    # Grupo Carrefour Brasil (incorporou Grupo BIG / Walmart Brasil em 2022)
    r"\bcarrefour\b",
    r"\bcarrefour\s?bairro\b",
    r"\bcarrefour\s?express\b",
    r"\batacad[aã]o\b",
    r"\bsam'?s\s?club\b",
    r"\bnacional\b",  # ambíguo
    r"\bbompre[cç]o\b",
    r"\bbig\s?bompre[cç]o\b",
    r"\bgrupo\s?big\b",
    r"\bwalmart\b",
    r"\bmaxxi\s?atacado\b",
    r"\btodo\s?dia\b",
    r"\bmercadorama\b",
    r"\bhiper\s?bompre[cç]o\b",
    # GPA / Pão de Açúcar
    r"\bp[aã]o\s?de\s?a[cç][uú]car\b",
    r"\bgpa\b",
    r"\bextra\b",  # ambíguo
    r"\bextra\s?mercado\b",
    r"\bminimercado\s?extra\b",
    r"\bmini\s?extra\b",
    r"\bcompre\s?bem\b",
    r"\bass[aá][ií]\b",
    r"\bassai\s?atacadista\b",
    r"\bsendas\b",
    # Cencosud Brasil
    r"\bgbarbosa\b",
    r"\bg\s?barbosa\b",
    r"\bbretas\b",
    r"\bperini\b",
    r"\bprezunic\b",
    r"\bmercantil\s?rodrigues\b",
    r"\bcencosud\b",
    # Otros grandes nacionales / regionais
    r"\bgrupo\s?mateus\b",
    r"\bmateus\s?supermercados?\b",
    r"\bmix\s?mateus\b",
    r"\bsuper\s?muffato\b",
    r"\bmuffato\b",
    r"\bmax\s?atacadista\b",
    r"\btenda\s?atacado\b",
    r"\brold[aã]o\b",
    r"\bfort\s?atacadista\b",
    r"\bgrupo\s?pereira\b",
    r"\bcomper\b",
    r"\bnovo\s?atacarejo\b",
    r"\batacadista\b",
    r"\batacarejo\b",
    r"\bsonda\s?supermercados?\b",
    r"\bsonda\b",
    r"\bsavegnago\b",
    r"\bcoop\b",
    r"\bangeloni\b",
    r"\bzaffari\b",
    r"\bbourbon\b",
    r"\bcondor\b",
    r"\bsupermercados?\s?bh\b",
    r"\bverdemar\b",
    r"\bepa\b",
    r"\bmineir[aã]o\b",
    r"\bdma\b",
    r"\bsuper\s?nosso\b",
    r"\bbahamas\b",
    r"\bzona\s?sul\b",
    r"\bmundial\b",
    r"\bguanabara\b",
    r"\bprincesa\b",
    r"\bgiassi\b",
    r"\bkoch\b",
    r"\bbistek\b",
    r"\bimperatriz\b",
    r"\bnordest[aã]o\b",
    r"\bbarbosa\s?supermercados?\b",
    r"\bsemar\b",
    r"\benxuto\b",
    r"\btauste\b",
    r"\bconfian[cç]a\b",
    r"\bamig[aã]o\b",
    r"\bcidade\s?can[cç][aã]o\b",
    r"\bfestval\b",
    r"\brede\s?smart\b",
    r"\brede\s?econ\b",
    r"\bhortifruti\b",
    r"\bnatural\s?da\s?terra\b",
    r"\bdia\b",  # ambíguo — Dia% saiu do Brasil
    r"\bmakro\b",
    r"\bspani\b",
    r"\bvillarreal\b",
    r"\bstok\s?center\b",
    r"\bsupermercado\b",
    r"\bmercadinho\b",
    r"\bmercearia\b",
    r"\bhipermercado\b",
    # =========================================================================
    # CONVENIÊNCIA E POSTOS DE COMBUSTÍVEL
    # =========================================================================
    r"\bpetrobras\b",
    r"\bbr\s?distribuidora\b",
    r"\bvibra\b",
    r"\bvibra\s?energia\b",
    r"\bposto\s?br\b",
    r"\bipiranga\b",
    r"\bshell\b",
    r"\bra[ií]zen\b",
    r"\bale\b",  # ambíguo
    r"\balesat\b",
    r"\btexaco\b",
    r"\brede\s?sim\b",
    r"\brodoil\b",
    r"\bciapetro\b",
    r"\bcharrua\b",
    r"\bpetrox\b",
    r"\bposto\b",
    r"\bam\s?pm\b",
    r"\bampm\b",
    r"\bbr\s?mania\b",
    r"\bshell\s?select\b",
    r"\bselect\b",  # ambíguo
    r"\boxxo\b",
    r"\blojas?\s?de\s?conveni[eê]ncia\b",
    r"\bultragaz\b",
    r"\bliquigas\b",
    r"\bliquig[aá]s\b",
    r"\bcopagaz\b",
    r"\bsupergasbras\b",
    r"\bnacional\s?g[aá]s\b",
    r"\bconsigaz\b",
    # =========================================================================
    # DELIVERY, QUICK COMMERCE E MARKETPLACES
    # =========================================================================
    r"\bifood\b",
    r"\bi\s?food\b",
    r"\brappi\b",
    r"\buber\s?eats\b",
    r"\b99\s?food\b",
    r"\bjames\s?delivery\b",
    r"\bz[eé]\s?delivery\b",
    r"\bdaki\b",
    r"\bshopper\b",
    r"\bcornershop\b",
    r"\baiqfome\b",
    r"\bmercado\s?livre\b",
    r"\bmercadolivre\b",
    r"\bmeli\b",
    r"\bamazon\b",
    r"\bshopee\b",
    r"\bshein\b",
    r"\baliexpress\b",
    r"\btemu\b",
    r"\bmagalu\b",
    r"\bmagazine\s?luiza\b",
    r"\bamericanas\b",
    r"\bsubmarino\b",
    r"\bshoptime\b",
    r"\bnetshoes\b",
    r"\bdafiti\b",
    r"\benjoei\b",
    r"\bolx\b",
    r"\bkabum\b",
    r"\bmadeiramadeira\b",
    r"\bmobly\b",
    # =========================================================================
    # FARMÁCIAS E DROGARIAS
    # =========================================================================
    r"\braia\s?drogasil\b",
    r"\bdroga\s?raia\b",
    r"\bdrogaraia\b",
    r"\bdrogasil\b",
    r"\bpague\s?menos\b",
    r"\bextrafarma\b",
    r"\bpanvel\b",
    r"\bdrogaria\s?s[aã]o\s?paulo\b",
    r"\bdrogaria\s?pacheco\b",
    r"\bdpsp\b",
    r"\bnissei\b",
    r"\bfarm[aá]cias?\s?nissei\b",
    r"\bdrogal\b",
    r"\bultrafarma\b",
    r"\bdrogaria\s?araujo\b",
    r"\bara[uú]jo\b",
    r"\bvenancio\b",
    r"\bven[aâ]ncio\b",
    r"\bfarmais\b",
    r"\bbig\s?ben\b",
    r"\bpharmapele\b",
    r"\bfarm[aá]cia\s?popular\b",
    r"\bindiana\b",
    r"\bnossa\s?farma\b",
    r"\bfarm[aá]cia\b",
    r"\bdrogaria\b",
    # =========================================================================
    # FAST FOOD E RESTAURANTES DE REDE
    # =========================================================================
    r"\bmc\s?donald'?s?\b",
    r"\bmcdonald'?s?\b",
    r"\barcos\s?dorados\b",
    r"\bmc\s?caf[eé]\b",
    r"\bburger\s?king\b",
    r"\bzamp\b",
    r"\bpopeyes\b",
    r"\bsubway\b",
    r"\bbob'?s\b",
    r"\bbffc\b",
    r"\bkfc\b",
    r"\bpizza\s?hut\b",
    r"\bdomino'?s?\s?pizza\b",
    r"\bdominos?\b",
    r"\bhabib'?s\b",
    r"\bragazzo\b",
    r"\bchina\s?in\s?box\b",
    r"\bgendai\b",
    r"\bgiraffas\b",
    r"\bspoleto\b",
    r"\bvivenda\s?do\s?camar[aã]o\b",
    r"\bmontana\s?grill\b",
    r"\boutback\b",
    r"\bmadero\b",
    r"\bcoco\s?bambu\b",
    r"\bdivino\s?fog[aã]o\b",
    r"\bgriletto\b",
    r"\bjin\s?jin\b",
    r"\bpatroni\b",
    r"\bsukiya\b",
    r"\bbaked\s?potato\b",
    r"\bmr\.?\s?cheney\b",
    r"\bapplebee'?s\b",
    r"\bparis\s?6\b",
    r"\bfogo\s?de\s?ch[aã]o\b",
    r"\bbarbacoa\b",
    r"\brodizio\b",
    r"\brod[ií]zio\b",
    r"\bchurrascaria\b",
    r"\bpastelaria\b",
    r"\blanchonete\b",
    r"\bpizzaria\b",
    # =========================================================================
    # CAFÉ, PADARIA, DOCES E SORVETES
    # =========================================================================
    r"\bstarbucks\b",
    r"\bthe\s?coffee\b",
    r"\bfran'?s\s?caf[eé]\b",
    r"\brei\s?do\s?mate\b",
    r"\bcasa\s?do\s?p[aã]o\s?de\s?queijo\b",
    r"\bcaf[eé]\s?cultura\b",
    r"\boct[aá]vio\s?caf[eé]\b",
    r"\bsuplicy\b",
    r"\bbauducco\b",
    r"\bcasa\s?bauducco\b",
    r"\bpadaria\b",
    r"\bconfeitaria\b",
    r"\bcacau\s?show\b",
    r"\bkopenhagen\b",
    r"\bbrasil\s?cacau\b",
    r"\bchocolates?\s?brasil\b",
    r"\blindt\b",
    r"\bsodi[eê]\s?doces\b",
    r"\bbacio\s?di\s?latte\b",
    r"\bchiquinho\s?sorvetes\b",
    r"\boakberry\b",
    r"\ba[cç]a[ií]\s?concept\b",
    r"\bfrooty\b",
    r"\byogoberry\b",
    r"\bkibon\b",
    r"\bh[aä]agen[\s\-]?dazs\b",
    r"\bsorveteria\b",
    r"\bcasa\s?de\s?bolos\b",
    r"\bmr\.?\s?mix\b",
    # =========================================================================
    # VAREJO — LOJAS DE DEPARTAMENTO, MODA E ELETRO
    # =========================================================================
    r"\bcasas\s?bahia\b",
    r"\bponto\s?frio\b",
    r"\bponto\b",  # ambíguo
    r"\bvia\s?varejo\b",
    r"\bgrupo\s?casas\s?bahia\b",
    r"\blojas\s?americanas\b",
    r"\bhavan\b",
    r"\blojas\s?renner\b",
    r"\brenner\b",
    r"\bc&a\b",
    r"\bc\s?(?:e|&)\s?a\b",
    r"\briachuelo\b",
    r"\bmarisa\b",
    r"\bpernambucanas\b",
    r"\bhering\b",
    r"\byoucom\b",
    r"\bashua\b",
    r"\bzara\b",
    r"\bh&m\b",
    r"\bforever\s?21\b",
    r"\bcentauro\b",
    r"\bdecathlon\b",
    r"\bnike\b",
    r"\badidas\b",
    r"\btrack\s?(?:e|&)\s?field\b",
    r"\barezzo\b",
    r"\bschutz\b",
    r"\banacapri\b",
    r"\bmelissa\b",
    r"\bhavaianas\b",
    r"\bipanema\b",
    r"\bgrendene\b",
    r"\bpaquet[aá]\b",
    r"\bconstance\b",
    r"\bdemocrata\b",
    r"\bchilli\s?beans\b",
    r"\b[oó]ticas\s?carol\b",
    r"\b[oó]ticas\s?diniz\b",
    r"\bvivara\b",
    r"\bpandora\b",
    r"\bmorana\b",
    r"\bimaginarium\b",
    r"\bpuket\b",
    r"\bo\s?botic[aá]rio\b",
    r"\bboticario\b",
    r"\bnatura\b",
    r"\bavon\b",
    r"\beudora\b",
    r"\bquem\s?disse\s?berenice\b",
    r"\bbeleza\s?na\s?web\b",
    r"\bsephora\b",
    r"\bfast\s?shop\b",
    r"\biplace\b",
    r"\bterabyte\b",
    r"\bmultilaser\b",
    # =========================================================================
    # CASA, CONSTRUÇÃO E MÓVEIS
    # =========================================================================
    r"\bleroy\s?merlin\b",
    r"\btelhanorte\b",
    r"\bc&c\b",
    r"\bobramax\b",
    r"\bsodimac\b",
    r"\bbalaroti\b",
    r"\btumelero\b",
    r"\bquero[\s\-]?quero\b",
    r"\bcassol\b",
    r"\bchatuba\b",
    r"\bcenter\s?castilho\b",
    r"\bdicico\b",
    r"\btodimo\b",
    r"\bcasa\s?show\b",
    r"\btok\s?(?:e|&)\s?stok\b",
    r"\betna\b",
    r"\bcamicado\b",
    r"\bmateriais?\s?de\s?constru[cç][aã]o\b",
    r"\bdep[oó]sito\b",  # ambíguo
    # =========================================================================
    # BANCOS E INSTITUIÇÕES FINANCEIRAS
    # =========================================================================
    r"\bbanco\s?do\s?brasil\b",
    r"\bbb\b",
    r"\bcaixa\s?econ[oô]mica\b",
    r"\bcaixa\b",  # ambíguo
    r"\bita[uú]\b",
    r"\bita[uú]\s?unibanco\b",
    r"\bunibanco\b",
    r"\bbradesco\b",
    r"\bsantander\b",
    r"\bbtg\s?pactual\b",
    r"\bsafra\b",
    r"\bbanrisul\b",
    r"\bbanco\s?do\s?nordeste\b",
    r"\bbnb\b",
    r"\bbanco\s?da\s?amaz[oô]nia\b",
    r"\bbasa\b",
    r"\bbndes\b",
    r"\bsicredi\b",
    r"\bsicoob\b",
    r"\bbancoob\b",
    r"\bcresol\b",
    r"\bbanco\s?inter\b",
    r"\bnubank\b",
    r"\bnu\s?pagamentos\b",
    r"\bc6\s?bank\b",
    r"\bbanco\s?original\b",
    r"\bpagbank\b",
    r"\bpagseguro\b",
    r"\bneon\b",
    r"\bnext\b",
    r"\bbanco\s?pan\b",
    r"\bbanco\s?bv\b",
    r"\bvotorantim\b",
    r"\bdaycoval\b",
    r"\bmodal\b",
    r"\bwill\s?bank\b",
    r"\bagibank\b",
    r"\bbanco\s?master\b",
    r"\bbmg\b",
    r"\bdigio\b",
    r"\bbanco\s?genial\b",
    r"\bbanco\s?central\b",
    r"\bbacen\b",
    r"\bxp\s?investimentos\b",
    r"\brico\b",  # ambíguo
    r"\bclear\b",
    r"\btoro\s?investimentos\b",
    r"\b[oó]rama\b",
    r"\bwarren\b",
    # =========================================================================
    # MEIOS DE PAGAMENTO E ADQUIRÊNCIA
    # =========================================================================
    r"\bcielo\b",
    r"\brede\b",  # ambíguo
    r"\bgetnet\b",
    r"\bstone\b",
    r"\bton\b",  # ambíguo
    r"\binfinitepay\b",
    r"\bsumup\b",
    r"\bmercado\s?pago\b",
    r"\bpicpay\b",
    r"\bame\s?digital\b",
    r"\brecargapay\b",
    r"\bpix\b",
    r"\bboleto\b",
    r"\bmaquininha\b",
    r"\bvero\b",
    r"\bsafrapay\b",
    r"\bpagarme\b",
    r"\bpagar\.me\b",
    r"\bebanx\b",
    r"\bwestern\s?union\b",
    r"\balelo\b",
    r"\bsodexo\b",
    r"\bpluxee\b",
    r"\bticket\b",  # ambíguo
    r"\bvr\s?benef[ií]cios\b",
    r"\bcaju\b",
    r"\bflash\s?benef[ií]cios\b",
    # =========================================================================
    # SEGUROS, SAÚDE SUPLEMENTAR E BENEFÍCIOS
    # =========================================================================
    r"\bbradesco\s?seguros\b",
    r"\bporto\s?seguro\b",
    r"\bsulam[eé]rica\b",
    r"\bamil\b",
    r"\bhapvida\b",
    r"\bnotredame\s?interm[eé]dica\b",
    r"\bgndi\b",
    r"\bunimed\b",
    r"\bprevent\s?senior\b",
    r"\bgolden\s?cross\b",
    r"\ballianz\b",
    r"\btokio\s?marine\b",
    r"\bmapfre\b",
    r"\bliberty\b",
    r"\bhdi\b",
    r"\bazul\s?seguros\b",
    r"\bicatu\b",
    r"\bzurich\b",
    r"\bmetlife\b",
    r"\bassurant\b",
    r"\bcaixa\s?seguradora\b",
    r"\bods\b",
    r"\bans\b",
    r"\bplano\s?de\s?sa[uú]de\b",
    # =========================================================================
    # HOSPITAIS, LABORATÓRIOS E REDE PÚBLICA DE SAÚDE
    # =========================================================================
    r"\brede\s?d'?or\b",
    r"\bd'?or\b",
    r"\balbert\s?einstein\b",
    r"\bs[ií]rio[\s\-]?liban[eê]s\b",
    r"\boswaldo\s?cruz\b",
    r"\bnove\s?de\s?julho\b",
    r"\b9\s?de\s?julho\b",
    r"\bbenefic[eê]ncia\s?portuguesa\b",
    r"\bsanta\s?casa\b",
    r"\bdasa\b",
    r"\bfleury\b",
    r"\bhermes\s?pardini\b",
    r"\bsabin\b",
    r"\bdelboni\b",
    r"\blavoisier\b",
    r"\balta\s?diagn[oó]sticos\b",
    r"\bamor\s?sa[uú]de\b",
    r"\bdr\.?\s?consulta\b",
    r"\bcl[ií]nica\s?sim\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\blaborat[oó]rio\b",
    r"\bubs\b",
    r"\bupa\b",
    r"\bposto\s?de\s?sa[uú]de\b",
    r"\bpsf\b",
    r"\besf\b",
    r"\bcaps\b",
    r"\bsamu\b",
    r"\bsus\b",
    r"\bcentro\s?de\s?sa[uú]de\b",
    r"\bpronto\s?socorro\b",
    r"\bunidade\s?b[aá]sica\b",
    # =========================================================================
    # TELECOMUNICAÇÕES
    # =========================================================================
    r"\bvivo\b",
    r"\btelef[oô]nica\b",
    r"\bclaro\b",
    r"\bnet\b",  # ambíguo
    r"\bembratel\b",
    r"\btim\b",
    r"\boi\b",  # ambíguo
    r"\bnextel\b",
    r"\balgar\b",
    r"\bsercomtel\b",
    r"\bsky\b",
    r"\bvero\s?internet\b",
    r"\bdesktop\b",
    r"\bbrisanet\b",
    r"\bunifique\b",
    r"\bsumicity\b",
    r"\bligga\b",
    r"\bstarlink\b",
    r"\banatel\b",
    # =========================================================================
    # ENERGIA, GÁS, ÁGUA E SANEAMENTO
    # =========================================================================
    r"\benel\b",
    r"\blight\b",
    r"\bcemig\b",
    r"\bcopel\b",
    r"\bcpfl\b",
    r"\bneoenergia\b",
    r"\bcoelba\b",
    r"\bcelpe\b",
    r"\bcosern\b",
    r"\belektro\b",
    r"\bequatorial\b",
    r"\bcemar\b",
    r"\bcelpa\b",
    r"\bcepisa\b",
    r"\bceee\b",
    r"\benergisa\b",
    r"\bedp\b",
    r"\beletrobras\b",
    r"\bfurnas\b",
    r"\bchesf\b",
    r"\baneel\b",
    r"\bcomg[aá]s\b",
    r"\bnaturgy\b",
    r"\bsabesp\b",
    r"\bcopasa\b",
    r"\bcedae\b",
    r"\bsanepar\b",
    r"\bcagece\b",
    r"\bcaesb\b",
    r"\bcorsan\b",
    r"\bembasa\b",
    r"\bcasan\b",
    r"\bcompesa\b",
    r"\baegea\b",
    r"\bbrk\s?ambiental\b",
    r"\bigu[aá]\b",
    # =========================================================================
    # CORREIOS, LOGÍSTICA E TRANSPORTE
    # =========================================================================
    r"\bcorreios\b",
    r"\bjadlog\b",
    r"\bloggi\b",
    r"\btotal\s?express\b",
    r"\bbraspress\b",
    r"\bsequoia\b",
    r"\bmercado\s?envios\b",
    r"\bshopee\s?xpress\b",
    r"\bazul\s?cargo\b",
    r"\bdhl\b",
    r"\bfedex\b",
    r"\bups\b",
    r"\blatam\b",
    r"\bgol\b",  # ambíguo
    r"\bazul\b",  # ambíguo
    r"\bvoepass\b",
    r"\bcometa\b",
    r"\bgontijo\b",
    r"\b[uú]til\b",
    r"\bviacao\s?1001\b",
    r"\bkaissara\b",
    r"\bitapemirim\b",
    r"\bbuser\b",
    r"\bclickbus\b",
    r"\brodovi[aá]ria\b",
    r"\bmetr[oô]\b",
    r"\bcptm\b",
    r"\bsupervia\b",
    r"\bbrt\b",
    r"\bbilhete\s?[uú]nico\b",
    r"\bped[aá]gio\b",
    r"\bsem\s?parar\b",
    r"\bconectcar\b",
    r"\bveloe\b",
    r"\buber\b",
    r"\b99\b",
    r"\b99\s?pop\b",
    r"\bindrive\b",
    r"\bcabify\b",
    r"\blocaliza\b",
    r"\bmovida\b",
    r"\bunidas\b",
    # =========================================================================
    # EDUCAÇÃO
    # =========================================================================
    r"\busp\b",
    r"\bunicamp\b",
    r"\bufrj\b",
    r"\bunesp\b",
    r"\bufmg\b",
    r"\bunip\b",
    r"\best[aá]cio\b",
    r"\byduqs\b",
    r"\banhanguera\b",
    r"\bkroton\b",
    r"\bcogna\b",
    r"\bunopar\b",
    r"\buninter\b",
    r"\bunicesumar\b",
    r"\bcruzeiro\s?do\s?sul\b",
    r"\bfmu\b",
    r"\bmackenzie\b",
    r"\bpuc\b",
    r"\bsenai\b",
    r"\bsenac\b",
    r"\bsesi\b",
    r"\bsesc\b",
    r"\bfisk\b",
    r"\bwizard\b",
    r"\bccaa\b",
    r"\bcultura\s?inglesa\b",
    r"\bkumon\b",
    r"\bmicrolins\b",
    r"\bprepara\b",
    r"\buniversidade\b",
    r"\bfaculdade\b",
    r"\bcol[eé]gio\b",
    r"\bescola\b",
    r"\bemei\b",
    r"\bemef\b",
    r"\bcmei\b",
    r"\bcreche\b",
    # =========================================================================
    # LAZER, CINEMA, ACADEMIAS E APOSTAS
    # =========================================================================
    r"\bcinemark\b",
    r"\bcin[eé]polis\b",
    r"\bkinoplex\b",
    r"\buci\b",
    r"\bmoviecom\b",
    r"\bcine\s?ara[uú]jo\b",
    r"\bplayarte\b",
    r"\bbeto\s?carrero\b",
    r"\bhopi\s?hari\b",
    r"\bhot\s?park\b",
    r"\bsmart\s?fit\b",
    r"\bsmartfit\b",
    r"\bbio\s?ritmo\b",
    r"\bselfit\b",
    r"\bbluefit\b",
    r"\bpanobianco\b",
    r"\bjust\s?fit\b",
    r"\bbodytech\b",
    r"\bacademia\b",
    r"\bcrossfit\b",
    r"\bbetano\b",
    r"\bbet365\b",
    r"\bblaze\b",
    r"\besportes\s?da\s?sorte\b",
    r"\bsportingbet\b",
    r"\bsuperbet\b",
    r"\bkto\b",
    r"\bpixbet\b",
    r"\bbetnacional\b",
    r"\bloterias?\s?caixa\b",
    r"\blot[eé]rica\b",
    r"\bmega[\s\-]?sena\b",
    # =========================================================================
    # HOTELARIA
    # =========================================================================
    r"\baccor\b",
    r"\bibis\b",
    r"\bnovotel\b",
    r"\bmercure\b",
    r"\bpullman\b",
    r"\bsofitel\b",
    r"\badagio\b",
    r"\batlantica\b",
    r"\bcomfort\b",
    r"\bquality\b",
    r"\bradisson\b",
    r"\bsleep\s?inn\b",
    r"\bgo\s?inn\b",
    r"\bbourbon\s?hot[eé]is\b",
    r"\bblue\s?tree\b",
    r"\btransam[eé]rica\b",
    r"\bnobile\b",
    r"\bwyndham\b",
    r"\bmarriott\b",
    r"\bhilton\b",
    r"\bintercity\b",
    r"\bslaviero\b",
    r"\bvila\s?gal[eé]\b",
    r"\biberostar\b",
    r"\brio\s?quente\b",
    r"\bcost[aã]o\s?do\s?santinho\b",
    r"\bhyatt\b",
    r"\bairbnb\b",
    r"\bhot[eé]l?\b",
    r"\bpousada\b",
    r"\bmotel\b",
    # =========================================================================
    # ÓRGÃOS PÚBLICOS E EQUIPAMENTOS COMUNITÁRIOS
    # =========================================================================
    r"\bprefeitura\b",
    r"\bc[aâ]mara\s?municipal\b",
    r"\bsubprefeitura\b",
    r"\bgoverno\s?do\s?estado\b",
    r"\bcras\b",
    r"\bcreas\b",
    r"\bdetran\b",
    r"\bpoupatempo\b",
    r"\binss\b",
    r"\breceita\s?federal\b",
    r"\bcart[oó]rio\b",
    r"\bf[oó]rum\b",
    r"\bdelegacia\b",
    r"\bpol[ií]cia\s?militar\b",
    r"\bpol[ií]cia\s?civil\b",
    r"\bcorpo\s?de\s?bombeiros\b",
    r"\bdefesa\s?civil\b",
    r"\bguarda\s?municipal\b",
    r"\bassocia[cç][aã]o\s?de\s?moradores\b",
    r"\bsindicato\b",
    r"\bigreja\b",
    r"\bpar[oó]quia\b",
    r"\bfeira\s?livre\b",
    r"\bmercado\s?municipal\b",
    r"\bceasa\b",
    r"\bsebrae\b",
    # =========================================================================
    # CORINGAS SETORIAIS (baixa precisão: usar na última passada)
    # =========================================================================
    r"\bagro",
    r"\bvet",
    r"\bpet\s?shop\b",
    r"\bpetz\b",
    r"\bcobasi\b",
    r"\bagropecu[aá]ria\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\ba[cç]ougue\b",
    r"\bhortifr[uú]ti\b",
    r"\bel[eé]tric",
    r"\beletr[oô]nic",
    r"\bcooperativa\b",
    r"\bltda\b",
    r"\bme\b",
    r"\bepp\b",
    r"\beireli\b",
]


# =============================================================================
# Patrones de ALTO riesgo de falso positivo (incluidos arriba).
# En Brasil el problema es peor que en español: muchas marcas son palabras
# comunes del portugués (extra, rede, ponto, oi, net, caixa, dia, gol, azul).
#     SAFE_CHAIN_REGEX = [p for p in CHAIN_REGEX if p not in AMBIGUOUS_PATTERNS]
# =============================================================================
AMBIGUOUS_PATTERNS = {
    r"\bextra\b",
    r"\bnacional\b",
    r"\bdia\b",
    r"\brede\b",
    r"\bponto\b",
    r"\boi\b",
    r"\bnet\b",
    r"\bcaixa\b",
    r"\bgol\b",
    r"\bazul\b",
    r"\bale\b",
    r"\bselect\b",
    r"\bton\b",
    r"\bticket\b",
    r"\brico\b",
    r"\bnext\b",
    r"\bclear\b",
    r"\bvero\b",
    r"\bmundial\b",
    r"\bprincesa\b",
    r"\bcoop\b",
    r"\bepa\b",
    r"\bdma\b",
    r"\bsonda\b",
    r"\bcondor\b",
    r"\bconfian[cç]a\b",
    r"\bbourbon\b",
    r"\bbahamas\b",
    r"\bzona\s?sul\b",
    r"\bguanabara\b",
    r"\bimperatriz\b",
    r"\bkoch\b",
    r"\bindiana\b",
    r"\bara[uú]jo\b",
    r"\bcometa\b",
    r"\b[uú]til\b",
    r"\b99\b",
    r"\bbb\b",
    r"\bmetr[oô]\b",
    r"\bbrt\b",
    r"\buci\b",
    r"\bupa\b",
    r"\bubs\b",
    r"\bsus\b",
    r"\bpuc\b",
    r"\bans\b",
    r"\bods\b",
    r"\bhdi\b",
    r"\bpix\b",
    r"\bboleto\b",
    r"\bstone\b",
    r"\bshopper\b",
    r"\bdep[oó]sito\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\bcooperativa\b",
    r"\bltda\b",
    r"\bme\b",
    r"\bepp\b",
    r"\beireli\b",
    r"\bposto\b",
    r"\bsupermercado\b",
    r"\bmercadinho\b",
    r"\bmercearia\b",
    r"\bhipermercado\b",
    r"\batacadista\b",
    r"\batacarejo\b",
    r"\bfarm[aá]cia\b",
    r"\bdrogaria\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\blaborat[oó]rio\b",
    r"\bpadaria\b",
    r"\bconfeitaria\b",
    r"\blanchonete\b",
    r"\bpizzaria\b",
    r"\bpastelaria\b",
    r"\bchurrascaria\b",
    r"\bsorveteria\b",
    r"\bacademia\b",
    r"\bescola\b",
    r"\bcol[eé]gio\b",
    r"\buniversidade\b",
    r"\bfaculdade\b",
    r"\bcreche\b",
    r"\bigreja\b",
    r"\bpar[oó]quia\b",
    r"\bhot[eé]l?\b",
    r"\bpousada\b",
    r"\bmotel\b",
    r"\bped[aá]gio\b",
    r"\brodovi[aá]ria\b",
    r"\bf[oó]rum\b",
    r"\bcart[oó]rio\b",
    r"\bdelegacia\b",
    r"\bsindicato\b",
    r"\bfeira\s?livre\b",
    r"\ba[cç]ougue\b",
    r"\bhortifr[uú]ti\b",
    r"\bagropecu[aá]ria\b",
}
