# config/patterns.py  —  PANAMÁ
# =============================================================================
# Módulo 2: Cadenas (adaptación a Panamá del listado original de RD)
# Fuente estructural: 1_Limpieza_Duplicados_Cadenas.ipynb
#

# =============================================================================

CHAIN_REGEX = [
    # =========================================================================
    # SUPERMERCADOS
    # =========================================================================
    r"\bsuper\s?99\b",
    r"\bsuper99\b",
    r"\b99\b",  # ambiguo
    r"\bsupermercados?\s?rey\b",
    r"\brey\b",  # ambiguo
    r"\bgrupo\s?rey\b",
    r"\bromero\b",
    r"\bmr\.?\s?precio\b",
    r"\bcorporaci[oó]n\s?favorita\b",
    r"\bel\s?machetazo\b",
    r"\bmachetazo\b",
    r"\briba\s?smith\b",
    r"\bribasmith\b",
    r"\bsupermercados?\s?xtra\b",
    r"\bxtra\b",
    r"\bgrupo\s?xtra\b",
    r"\bsuper\s?kosher\b",
    r"\bdeli\s?gourmet\b",
    r"\bsuper\s?carnes\b",
    r"\bsuper\s?bar[uú]\b",
    r"\bpricesmart\b",
    r"\bprice\s?smart\b",
    r"\bmegadepot\b",
    r"\bmega\s?depot\b",
    r"\bfelipe\s?motta\b",
    r"\bsupermercado\b",
    r"\bminisuper\b",
    r"\bmini\s?super\b",
    r"\babarroter[ií]a\b",
    r"\bbodeg[oó]n\b",
    r"\bzona\s?libre\b",  # PA: Colón
    # =========================================================================
    # COMBUSTIBLE Y CONVENIENCIA
    # =========================================================================
    r"\bdelta\b",
    r"\bpetr[oó]leos\s?delta\b",
    r"\bterpel\b",
    r"\bpuma\s?energy\b",
    r"\bpuma\b",
    r"\btexaco\b",
    r"\bchevron\b",
    r"\baccel\b",
    r"\besso\b",
    r"\bshell\b",
    r"\bva\s?(?:y|&)\s?ven\b",
    r"\bva&ven\b",
    r"\bvayven\b",
    r"\bdelta\s?xpress\b",
    r"\bsuper\s?7\b",  # verificar
    r"\bestaci[oó]n\s?de\s?servicio\b",
    r"\bbomba\b",  # ambiguo
    r"\bgas\s?licuado\b",
    r"\btropigas\b",
    r"\bpanagas\b",  # verificar
    # =========================================================================
    # DELIVERY Y MARKETPLACES
    # =========================================================================
    r"\bappetito\s?24\b",
    r"\bappetito24\b",  # rebrand -> PedidosYa
    r"\bpedidosya\b",
    r"\bpedidos\s?ya\b",
    r"\buber\s?eats\b",
    r"\bubereats\b",
    r"\bglovo\b",
    r"\bdidi\s?food\b",
    r"\bmercado\s?libre\b",
    r"\bamazon\b",
    r"\bshein\b",
    r"\btemu\b",
    r"\baliexpress\b",
    r"\bcasillero\b",  # PA: clave en compras online
    # =========================================================================
    # FARMACIAS
    # =========================================================================
    r"\bfarmacias?\s?arrocha\b",
    r"\barrocha\b",
    r"\bfarmacias?\s?metro\b",
    r"\bmetro\b",  # ambiguo (Metro de Panamá)
    r"\bel\s?javillo\b",
    r"\bfarmacias?\s?rey\b",
    r"\bfarmacia\s?regia\b",
    r"\bfarmacias?\s?revilla\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    r"\bdroguer[ií]a\b",
    # =========================================================================
    # COMIDA RÁPIDA Y RESTAURANTES DE CADENA
    # =========================================================================
    r"\bmc\s?donald'?s?\b",
    r"\bmcdonald'?s?\b",
    r"\bburger\s?king\b",
    r"\bkfc\b",
    r"\bkentucky\s?fried\s?chicken\b",
    r"\bwendy'?s\b",
    r"\bsubway\b",
    r"\bpopeye'?s?\b",
    r"\btaco\s?bell\b",
    r"\bdomino'?s?\s?pizza\b",
    r"\bdominos?\b",
    r"\bpizza\s?hut\b",
    r"\bpapa\s?john'?s?\b",
    r"\blittle\s?caesars\b",
    r"\bstarbucks\b",
    r"\bdunkin(?:'?s)?(?:\s?donuts)?\b",
    r"\bkrispy\s?kreme\b",
    r"\bchili'?s\b",
    r"\btgi\s?fridays?\b",
    r"\btony\s?roma'?s\b",
    r"\bhard\s?rock\s?caf[eé]\b",
    r"\bhooters\b",
    r"\bbenihana\b",
    r"\bsushi\s?itto\b",
    r"\bwingstop\b",
    r"\bcinnabon\b",
    r"\bh[aä]agen[\s\-]?dazs\b",
    r"\bcold\s?stone\b",
    # cadenas panameñas
    r"\bniko'?\s?s?\s?caf[eé]\b",
    r"\bnikos\b",
    r"\bpio\s?pio\b",
    r"\bgrupo\s?melo\b",
    r"\bmelo\b",  # ambiguo
    r"\bel\s?trapiche\b",
    r"\btinajas\b",
    r"\brinc[oó]n\s?table[nñ]o\b",
    r"\bathanasiou\b",
    r"\bcaf[eé]\s?unido\b",
    r"\bbajareque\b",
    r"\bcaf[eé]\s?duran\b",
    r"\bdur[aá]n\b",  # ambiguo (apellido)
    r"\bmanolo\s?caracol\b",
    r"\bla\s?rana\s?dorada\b",
    r"\bmahalo\b",
    r"\bcafeter[ií]a\b",
    r"\bpanader[ií]a\b",
    r"\bpasteler[ií]a\b",
    r"\bheladeria\b",
    r"\bhelader[ií]a\b",
    r"\bpizzer[ií]a\b",
    r"\bmarisquer[ií]a\b",
    # =========================================================================
    # RETAIL — TIENDAS, ELECTRO Y FERRETERÍA
    # =========================================================================
    r"\bfelix\s?b\.?\s?maduro\b",
    r"\bf[eé]lix\s?maduro\b",
    r"\bfelix\b",
    r"\bstevens\b",
    r"\bdorian'?s\b",
    r"\bcollins\b",
    r"\bbibi\b",
    r"\bpanafoto\b",
    r"\bmultimax\b",
    r"\baudiofoto\b",
    r"\brodelag\b",
    r"\bel\s?costo\b",
    r"\bricamar\b",
    r"\bnovey\b",
    r"\bdo\s?it\s?center\b",
    r"\bdoit\s?center\b",
    r"\bcochez\b",
    r"\bcochez\s?y\s?c[ií]a\b",
    r"\bdiscovery\s?center\b",
    r"\bcasa\s?de\s?las\s?bater[ií]as\b",
    r"\bferreter[ií]a\b",
    r"\bminiso\b",
    r"\bmumuso\b",
    r"\bilahui\b",
    r"\bzara\b",
    r"\bbershka\b",
    r"\bmassimo\s?dutti\b",
    r"\bpull\s?(?:and|&)?\s?bear\b",
    r"\bstradivarius\b",
    r"\bforever\s?21\b",
    r"\bh&m\b",
    r"\bpayless\b",
    r"\bsteve\s?madden\b",
    r"\baldo\b",
    r"\bnine\s?west\b",
    r"\bnike\b",
    r"\badidas\b",
    r"\bskechers\b",
    r"\bsally\s?beauty\b",
    r"\bmac\b",  # ambiguo
    r"\bl'?occitane\b",
    r"\bswarovski\b",
    r"\bpandora\b",
    r"\bdufry\b",
    # centros comerciales (aparecen mucho como parte de la dirección)
    r"\bmultiplaza\b",
    r"\balbrook\s?mall\b",
    r"\bmetromall\b",
    r"\baltaplaza\b",
    r"\bsoho\s?mall\b",
    r"\bwestland\s?mall\b",
    r"\blos\s?pueblos\b",
    r"\bmulticentro\b",
    r"\bmall\b",
    # =========================================================================
    # BANCA  (nómina SBP)
    # =========================================================================
    r"\bbanco\s?general\b",
    r"\bbg\b",  # ambiguo
    r"\bbanistmo\b",
    r"\bhsbc\b",
    r"\bbac\s?credomatic\b",
    r"\bbac\b",
    r"\bcredomatic\b",
    r"\bbanco\s?nacional\s?de\s?panam[aá]\b",
    r"\bbnp\b",
    r"\bcaja\s?de\s?ahorros\b",
    r"\bglobal\s?bank\b",
    r"\bmultibank\b",
    r"\bbanesco\b",
    r"\bbanco\s?aliado\b",
    r"\bcapital\s?bank\b",
    r"\bcredicorp\s?bank\b",
    r"\btowerbank\b",
    r"\btower\s?bank\b",
    r"\bmmg\s?bank\b",
    r"\bmetrobank\b",
    r"\bst\.?\s?georges\s?bank\b",
    r"\bla\s?hipotecaria\b",
    r"\bunibank\b",
    r"\bbanco\s?delta\b",
    r"\bficohsa\b",
    r"\blafise\b",
    r"\bmercantil\s?banco\b",
    r"\bbi[\s\-]?bank\b",
    r"\bbanco\s?pichincha\b",
    r"\bcitibank\b",
    r"\bscotiabank\b",
    r"\bbbva\b",
    r"\bbladex\b",
    r"\bsbp\b",
    r"\bsuperintendencia\s?de\s?bancos\b",
    r"\bcooperativa\s?de\s?ahorro\b",
    r"\bcoopeduc\b",
    r"\bcredicoop\b",
    # =========================================================================
    # MEDIOS DE PAGO  (# PA — Clave y Yappy son los dominantes)
    # =========================================================================
    r"\bclave\b",  # ambiguo — red nacional de cajeros/ATM
    r"\btelered\b",
    r"\byappy\b",
    r"\bnequi\b",
    r"\bach\s?xpress\b",
    r"\bwestern\s?union\b",
    r"\bmoneygram\b",
    r"\bmoney\s?gram\b",
    r"\bpanapass\b",  # PA: telepeaje
    r"\bcasa\s?de\s?cambio\b",
    # =========================================================================
    # SEGUROS Y PENSIONES
    # =========================================================================
    r"\bassa\b",
    r"\binternacional\s?de\s?seguros\b",
    r"\bmapfre\b",
    r"\bsura\b",
    r"\bpalig\b",
    r"\bpan[\s\-]?american\s?life\b",
    r"\banc[oó]n\s?seguros\b",
    r"\baseguradora\s?global\b",
    r"\bbanesco\s?seguros\b",
    r"\b[oó]ptima\s?seguros\b",
    r"\bgenerali\b",
    r"\bseguros\b",
    # =========================================================================
    # SALUD  (# PA — la CSS es el actor central)
    # =========================================================================
    r"\bcaja\s?de\s?seguro\s?social\b",
    r"\bcss\b",
    r"\bminsa\b",
    r"\bhospital\s?santo\s?tom[aá]s\b",
    r"\bcomplejo\s?hospitalario\b",
    r"\bhospital\s?punta\s?pac[ií]fica\b",
    r"\bpac[ií]fica\s?salud\b",
    r"\bhospital\s?nacional\b",
    r"\bhospital\s?san\s?fernando\b",
    r"\bcentro\s?m[eé]dico\s?paitilla\b",
    r"\bpaitilla\b",
    r"\bhospital\s?chiriqu[ií]\b",
    r"\bhospital\s?del\s?ni[nñ]o\b",
    r"\bion\b",
    r"\binstituto\s?oncol[oó]gico\b",
    r"\bminsa\s?capsi\b",
    r"\bcapsi\b",
    r"\bulaps\b",
    r"\bpolicentro\b",
    r"\bcentro\s?de\s?salud\b",
    r"\bsub\s?centro\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\blaboratorio\b",
    r"\bpolicl[ií]nica\b",
    # =========================================================================
    # TELECOMUNICACIONES
    # =========================================================================
    r"\bcable\s?(?:and|&)\s?wireless\b",
    r"\bc&w\b",
    r"\bcwp\b",
    r"\b\+m[oó]vil\b",
    r"\bmas\s?movil\b",
    r"\bm[aá]s\s?m[oó]vil\b",
    r"\btigo\b",
    r"\bmillicom\b",
    r"\bcable\s?onda\b",
    r"\bmovistar\b",
    r"\bclaro\b",
    r"\bdigicel\b",  # salieron/absorbidos
    r"\bstarlink\b",
    r"\basep\b",
    # =========================================================================
    # ENERGÍA Y AGUA
    # =========================================================================
    r"\bensa\b",
    r"\belektra\s?noreste\b",
    r"\bnaturgy\b",
    r"\bedemet\b",
    r"\bedechi\b",
    r"\buni[oó]n\s?fenosa\b",
    r"\betesa\b",
    r"\baes\s?panam[aá]\b",
    r"\bidaan\b",
    r"\binstituto\s?de\s?acueductos\b",
    # =========================================================================
    # CORREO, COURIER Y CASILLEROS  (# PA)
    # =========================================================================
    r"\bcotel\b",
    r"\bcorreos\s?y\s?tel[eé]grafos\b",
    r"\bmail\s?boxes\b",
    r"\bairbox\b",
    r"\bbox\s?express\b",
    r"\bpanama\s?box\b",
    r"\bdhl\b",
    r"\bfedex\b",
    r"\bups\b",
    # =========================================================================
    # TRANSPORTE  (# PA — corredores y Panapass)
    # =========================================================================
    r"\bcopa\s?airlines\b",
    r"\bcopa\b",  # ambiguo
    r"\bair\s?panama\b",
    r"\bwingo\b",
    r"\btocumen\b",
    r"\bmetro\s?de\s?panam[aá]\b",
    r"\bmibus\b",
    r"\bmetro\s?bus\b",
    r"\bmetrobus\b",
    r"\bdiablo\s?rojo\b",
    r"\bcorredor\s?norte\b",
    r"\bcorredor\s?sur\b",
    r"\bpeaje\b",
    r"\buber\b",
    r"\bindrive\b",
    r"\bcabify\b",
    r"\bhertz\b",
    r"\bavis\b",
    r"\bbudget\b",
    r"\bnational\s?car\b",
    r"\brent\s?a\s?car\b",
    # =========================================================================
    # HOTELERÍA Y ENTRETENCIÓN
    # =========================================================================
    r"\bhilton\b",
    r"\bmarriott\b",
    r"\bjw\s?marriott\b",
    r"\bwaldorf\s?astoria\b",
    r"\bsheraton\b",
    r"\bwestin\b",
    r"\bw\s?panama\b",
    r"\bhyatt\b",
    r"\bintercontinental\b",
    r"\bmiramar\b",
    r"\briu\b",
    r"\bmeli[aá]\b",
    r"\bsortis\b",
    r"\bmegapolis\b",
    r"\bhard\s?rock\s?hotel\b",
    r"\bbristol\b",
    r"\bamerican\s?trade\b",
    r"\bcentral\s?hotel\b",
    r"\bradisson\b",
    r"\bwyndham\b",
    r"\bholiday\s?inn(?:\s?express)?\b",
    r"\bcourtyard\b",
    r"\bcrowne\s?plaza\b",
    r"\bplaya\s?blanca\b",
    r"\bdecameron\b",
    r"\bdreams\s?playa\s?bonita\b",
    r"\bbuenaventura\b",
    r"\bairbnb\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\bapartahotel\b",
    r"\bmajestic\b",
    r"\bveneto\b",
    r"\bfiesta\s?casino\b",
    r"\bcrown\s?casino\b",
    r"\bgolden\s?lion\b",
    r"\broyal\s?casino\b",
    r"\bcasino\b",
    r"\bloter[ií]a\s?nacional\b",
    r"\blnb\b",
    r"\bchance\b",
    r"\bbillete\b",  # PA: lotería
    r"\bcin[eé]polis\b",
    r"\bcinemark\b",
    r"\bextreme\s?planet\b",
    r"\bpowerclub\b",
    r"\bpower\s?club\b",
    r"\bsmart\s?fit\b",
    r"\bsmartfit\b",
    r"\bgimnasio\b",
    r"\bcrossfit\b",
    # =========================================================================
    # EDUCACIÓN
    # =========================================================================
    r"\buniversidad\s?de\s?panam[aá]\b",
    r"\bup\b",  # ambiguo
    r"\butp\b",
    r"\busma\b",
    r"\bsanta\s?mar[ií]a\s?la\s?antigua\b",
    r"\buniversidad\s?latina\b",
    r"\budelas\b",
    r"\bunachi\b",
    r"\bqlu\b",
    r"\bquality\s?leadership\b",
    r"\bflorida\s?state\b",
    r"\bisae\b",
    r"\bcolumbus\s?university\b",
    r"\binadeh\b",
    r"\bitse\b",
    r"\bifarhu\b",
    r"\bmeduca\b",
    r"\buniversidad\b",
    r"\bcolegio\b",
    r"\bescuela\b",
    r"\bcentro\s?educativo\b",
    r"\bceba\b",
    # =========================================================================
    # INSTITUCIONES PÚBLICAS Y COMUNITARIAS  (# PA — "corregimiento")
    # =========================================================================
    r"\bmunicipio\s?de\s?panam[aá]\b",
    r"\balcald[ií]a\b",
    r"\bmunicipio\b",
    r"\bcorregimiento\b",  # PA: división administrativa clave
    r"\bjunta\s?comunal\b",
    r"\bjunta\s?local\b",
    r"\brepresentante\s?de\s?corregimiento\b",
    r"\bcasa\s?comunal\b",
    r"\bpolic[ií]a\s?nacional\b",
    r"\bsenafront\b",
    r"\bsenan\b",
    r"\bbomberos\b",
    r"\bsinaproc\b",
    r"\btribunal\s?electoral\b",
    r"\bregistro\s?p[uú]blico\b",
    r"\bdgi\b",
    r"\banati\b",
    r"\bmides\b",
    r"\bmitradel\b",
    r"\bmivi\b",
    r"\bmop\b",
    r"\bcontralor[ií]a\b",
    r"\bautoridad\s?del\s?canal\b",
    r"\bacp\b",
    r"\bzona\s?franca\b",
    r"\biglesia\b",
    r"\bparroquia\b",
    r"\bcentro\s?comunitario\b",
    # =========================================================================
    # COMODINES SECTORIALES (baja precisión: usar como última pasada)
    # =========================================================================
    r"\bagro",
    r"\bvet",
    r"\bforraj",
    r"\bvivero\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\balmac[eé]n\b",
    r"\bdep[oó]sito\b",
    r"\bcarnicer[ií]a\b",
    r"\bverduler[ií]a\b",
    r"\bel[eé]ctric",
    r"\belectr[oó]nic",
    r"\bcooperativa\b",
    r"\bs\.?a\.?\b",
    r"\bcorp\b",
    r"\binc\b",
]


# =============================================================================
# Patrones de ALTO riesgo de falso positivo (incluidos arriba).
#     SAFE_CHAIN_REGEX = [p for p in CHAIN_REGEX if p not in AMBIGUOUS_PATTERNS]
#
# Panamá tiene dos trampas propias: (1) marcas que son palabras corrientes
# ("Rey", "Clave", "Delta", "Metro", "Copa", "Xtra", "99"); (2) el inglés
# mezclado en razones sociales por la Zona Libre y el hub bancario, que hace
# que "corp", "inc", "bank" y "mall" aparezcan por todas partes.
# =============================================================================
AMBIGUOUS_PATTERNS = {
    r"\b99\b",
    r"\brey\b",
    r"\bxtra\b",
    r"\bmetro\b",
    r"\bdelta\b",
    r"\bpuma\b",
    r"\bclave\b",
    r"\bcopa\b",
    r"\bbomba\b",
    r"\bfelix\b",
    r"\bmelo\b",
    r"\bdur[aá]n\b",
    r"\bbibi\b",
    r"\bcollins\b",
    r"\bmac\b",
    r"\bbg\b",
    r"\bbac\b",
    r"\bbnp\b",
    r"\bcss\b",
    r"\bion\b",
    r"\bup\b",
    r"\butp\b",
    r"\bmop\b",
    r"\bacp\b",
    r"\bmall\b",
    r"\bcorp\b",
    r"\binc\b",
    r"\bs\.?a\.?\b",
    r"\bchance\b",
    r"\bbillete\b",
    r"\bmajestic\b",
    r"\bveneto\b",
    r"\bbristol\b",
    r"\bmiramar\b",
    r"\bbuenaventura\b",
    r"\bcentral\s?hotel\b",
    r"\bcasillero\b",
    r"\bzona\s?libre\b",
    r"\bzona\s?franca\b",
    r"\bbodeg[oó]n\b",
    r"\bseguros\b",
    r"\bsura\b",
    r"\bnequi\b",
    r"\bcomercial\b",
    r"\bdistribuidora\b",
    r"\bimportadora\b",
    r"\balmac[eé]n\b",
    r"\bdep[oó]sito\b",
    r"\bcooperativa\b",
    r"\bvivero\b",
    r"\bsupermercado\b",
    r"\bminisuper\b",
    r"\bmini\s?super\b",
    r"\babarroter[ií]a\b",
    r"\bfarmacia\b",
    r"\bbotica\b",
    r"\bdroguer[ií]a\b",
    r"\bhospital\b",
    r"\bcl[ií]nica\b",
    r"\bpolicl[ií]nica\b",
    r"\blaboratorio\b",
    r"\bcentro\s?de\s?salud\b",
    r"\bferreter[ií]a\b",
    r"\bcafeter[ií]a\b",
    r"\bpanader[ií]a\b",
    r"\bpasteler[ií]a\b",
    r"\bheladeria\b",
    r"\bhelader[ií]a\b",
    r"\bpizzer[ií]a\b",
    r"\bmarisquer[ií]a\b",
    r"\bcarnicer[ií]a\b",
    r"\bverduler[ií]a\b",
    r"\bhotel\b",
    r"\bhostal\b",
    r"\bapartahotel\b",
    r"\bcasino\b",
    r"\bgimnasio\b",
    r"\bescuela\b",
    r"\bcolegio\b",
    r"\buniversidad\b",
    r"\bcentro\s?educativo\b",
    r"\bceba\b",
    r"\bmunicipio\b",
    r"\biglesia\b",
    r"\bparroquia\b",
    r"\bpeaje\b",
    r"\brent\s?a\s?car\b",
}
