# config/settings.py
import importlib
from pathlib import Path

import yaml

# 1. Automatically define the project root directory.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# 2. Define the exact path to the YAML configuration file.
YAML_PATH = PROJECT_ROOT / "config.yaml"

# 3. Read and parse the YAML file safely.
with open(YAML_PATH, "r", encoding="utf-8") as file:
    config_data = yaml.safe_load(file)

# 4. Extract the main variables from the dictionary generated by YAML.
ACTIVE_COUNTRY = config_data["pipeline_settings"]["active_country"].lower()

# 5. Extract the path strings from the YAML.
_data_dir_path = config_data["paths"]["data_dir"]
_raw_data_path = config_data["paths"]["raw_data"]
_output_data_path = config_data["paths"]["output_data"]

# 6. Build exact, OS-independent file paths using pathlib.
DATA_DIR = PROJECT_ROOT / _data_dir_path
INPUT_FILE = PROJECT_ROOT / _raw_data_path
OUTPUT_FILE = PROJECT_ROOT / _output_data_path

# =================================================================
# 7. DYNAMIC IMPORTS (Patterns & Regex)
# =================================================================
_module_name = f"config.patterns_{ACTIVE_COUNTRY}"

try:
    _module = importlib.import_module(_module_name)

    # 1. Buscamos PATTERNS. Si no existe, asignamos una lista vacía [] silenciosamente.
    GLOBAL_PATTERNS = getattr(_module, f"PATTERNS_{ACTIVE_COUNTRY.upper()}", [])

    # 2. CHAIN_REGEX sí es obligatorio, así que este sí fallará si no lo encuentra.
    GLOBAL_CHAIN_REGEX = _module.CHAIN_REGEX

except ModuleNotFoundError:
    raise ValueError(
        f"ERROR: Could not find the file {_module_name}.py for the country '{ACTIVE_COUNTRY}'."
    )
except AttributeError as e:
    # Solo lanzará este error si falta CHAIN_REGEX
    raise ValueError(
        f"ERROR: The file {_module_name}.py is missing a required variable: {e}"
    )
